#!/usr/bin/env node
/**
 * `openapi/openapi.json` → `src/Models/*.php` and `src/Generated/*.php`.
 *
 * Design decision 3: generated models, our generator. This follows the Dart
 * generator (`packages/sdk-dart/tool/gen.mjs`) rule for rule — the same
 * `REQUEST_NAMES` table, the same shape-based dedupe so `Birth`,
 * `CalculationOptions` and `TimeWindow` exist once rather than 35 times, the
 * same hand-picked names for the four shapes that dedupe into something a
 * path-derived name would not describe, `LabelledId` shared, `null`-only
 * fields as the widest type the language has, `MaitriDocument` as a wrapper
 * around the map it is, and reference rows left untyped. The three SDKs are
 * read side by side, so a shape must not be `ChalitHouses` in Dart and
 * `ChalitDocumentEqual` here.
 *
 * Where the files go, and why they are not all in one directory:
 * `composer.json` maps the PSR-4 prefix `Kaaljyoti\` to `src/`, so PSR-4 looks
 * for `Kaaljyoti\Models\KundliDocument` in `src/Models/KundliDocument.php` —
 * a `src/Generated/Models/` directory could not hold it without a second
 * autoload entry. So the models take the namespace callers type
 * (`Kaaljyoti\Models`) and live in `src/Models/`, and the three files that are
 * plumbing rather than payload — the cast helpers, the operation table and the
 * version constants — take `Kaaljyoti\Generated` and live in `src/Generated/`.
 * `LabelledId` is plumbing by that rule and is generated into
 * `src/Generated/LabelledId.php`; every model that names an id imports it.
 *
 * What it writes:
 *
 *   src/Generated/Json.php        cast helpers (PHPStan level 9 rejects `mixed`)
 *   src/Generated/LabelledId.php  the one shape every document shares
 *   src/Generated/Operation.php   one row of the operation table
 *   src/Generated/Operations.php  the table itself, which the contract test walks
 *   src/Generated/Version.php     the two version constants
 *   src/Models/<ClassName>.php    one final readonly class per schema
 *
 * There is no PHP formatter in this workspace, so the emitted bytes are the
 * committed bytes: PSR-12 by construction (4-space indent, `declare`d strict
 * types, one class per file). `--check` regenerates into memory and compares
 * byte for byte, so CI fails on a stale file rather than shipping models that
 * describe an API we no longer have.
 *
 * Usage: `node tool/gen.mjs [--check]`.
 */

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const schemaFile = join(packageDir, '../../openapi/openapi.json');
const srcDir = join(packageDir, 'src');

/** The two directories this generator owns outright. */
const OUT_DIRS = ['Generated', 'Models'];

const MODELS_NAMESPACE = 'Kaaljyoti\\Models';
const GENERATED_NAMESPACE = 'Kaaljyoti\\Generated';

const HEADER = (what) => `<?php

/**
 * GENERATED by \`pnpm --filter sdk-php run gen\` from openapi/openapi.json.
 * Do not edit by hand: \`pnpm --filter sdk-php run gen:check\` fails the build
 * when this file and the snapshot disagree.
 *
 * ${what}
 */

declare(strict_types=1);
`;

// ---------------------------------------------------------------------------
// The shared naming contract
// ---------------------------------------------------------------------------

/**
 * Request and document names, mirroring `packages/sdk-ts/src/types.ts` and
 * `packages/sdk-dart/tool/gen.mjs`.
 *
 * The three SDKs are read side by side, so a shape must not be `DashaRequest`
 * in TypeScript and `KundliDashaRequest` here. The names follow the method
 * list in the design doc rather than the operation ids — `$kj->panchang
 * ->daily()` answers a `DailyPanchangDocument`, so that is what the class is
 * called even though the operation is `postPanchang`.
 *
 * A missing entry is a hard error rather than a guess: a new operation in the
 * snapshot should be named deliberately in all three SDKs.
 */
const REQUEST_NAMES = {
  postKundli: 'KundliRequest',
  postKundliDasha: 'DashaRequest',
  postKundliVargas: 'VargasRequest',
  postKundliChalit: 'ChalitRequest',
  postKundliYogas: 'YogasRequest',
  postKundliShadbala: 'ShadbalaRequest',
  postKundliBhavaBala: 'BhavaBalaRequest',
  postKundliAshtakavarga: 'AshtakavargaRequest',
  postKundliGrahaDrishti: 'GrahaDrishtiRequest',
  postKundliMaitri: 'MaitriRequest',
  postKundliPace: 'PaceRequest',
  postKundliSpecialLagnas: 'SpecialLagnasRequest',
  postKundliTripataki: 'TripatakiRequest',
  postKundliSarvatobhadra: 'SarvatobhadraRequest',
  postKundliNakshatra28: 'Nakshatra28Request',
  postKundliSadeSati: 'SadeSatiRequest',
  postKundliEvents: 'EventsRequest',
  postKundliKotaChakra: 'KotaChakraRequest',
  postKundliChart: 'KundliChartRequest',
  postPanchang: 'PanchangRequest',
  postPanchangMuhurta: 'MuhurtaRequest',
  postPanchangMonth: 'PanchangMonthRequest',
  postEphemerisMonth: 'EphemerisMonthRequest',
  postCalendarVikramSamvat: 'VikramSamvatRequest',
  postJaiminiKarakas: 'JaiminiKarakasRequest',
  postJaiminiArudhaPadas: 'JaiminiArudhaPadasRequest',
  postJaiminiAspects: 'JaiminiAspectsRequest',
  postJaiminiKarakamsha: 'JaiminiKarakamshaRequest',
  postKpChart: 'KpChartRequest',
  postVarshphal: 'VarshphalRequest',
  postVarshphalBala: 'VarshphalBalaRequest',
  postVarshphalSahams: 'VarshphalSahamsRequest',
  postVarshphalYogas: 'VarshphalYogasRequest',
  postVarshphalDasha: 'VarshphalDashaRequest',
  postTransitNow: 'TransitNowRequest',
  postTransitScan: 'TransitScanRequest',
  postTransitEvents: 'TransitEventsRequest',
  postMatchAshtakoot: 'MatchAshtakootRequest',
  postMatchCompare: 'MatchCompareRequest',
  postMatchBatch: 'MatchBatchRequest',
  postReportsLagna: 'ReportLagnaRequest',
  postReportsNakshatra: 'ReportNakshatraRequest',
  postHoroscope: 'HoroscopeRequest',
  postReportsHouseLords: 'ReportHouseLordsRequest',
  postReportsGrahas: 'ReportGrahasRequest',
  postReportsYogas: 'ReportYogasRequest',
  postReportsVimshottari: 'ReportVimshottariRequest',
  postReportsVarshphal: 'ReportVarshphalRequest',
  postReportsLifeAreas: 'ReportLifeAreasRequest',
  postReportsKundli: 'ReportKundliRequest',
  postPdfKundli: 'PdfKundliRequest',
  postPdfMatch: 'PdfMatchRequest',
  postPdfVarshphal: 'PdfVarshphalRequest',
  postPdfPanchangMonth: 'PdfPanchangMonthRequest',
};

/**
 * Names for the documents that are not `$ref`s to a named schema.
 *
 * Everything else takes its name from `components.schemas`, which already
 * agrees with the TypeScript aliases.
 */
const INLINE_DOCUMENT_NAMES = {
  getHealth: 'HealthDocument',
  getTimezone: 'TimezoneDocument',
  postMatchBatch: 'BatchDocument',
  getPlaces: 'PlacesDocument',
};

/**
 * Names for the `meta` members that are not a `$ref` either.
 *
 * `GET /v1/reference/{list}` and `GET /v1/timezone` report something narrower
 * than `Meta`: nothing was computed, so there is no ayanamsa and no timezone
 * to name.
 */
const INLINE_META_NAMES = {
  getReferenceList: 'ReferenceMeta',
  getTimezone: 'TimezoneMeta',
  getPlaces: 'PlacesMeta',
};

/**
 * Schemas whose own name is not used verbatim.
 *
 * `Error` is a class in PHP's root namespace. `Kaaljyoti\Models\Error` would
 * not collide with it outright, but a file that imports both reads as a trap,
 * and Dart cannot use the name at all — so both SDKs say `ErrorBody`.
 */
const SCHEMA_RENAMES = { Error: 'ErrorBody' };

/** Nested shapes worth a hand-picked name instead of a path-derived one. */
const NESTED_RENAMES = {
  ErrorBodyError: 'ErrorDetail',
  // `MaitriDocument` is a map of maps, so the path-derived name for the leaf
  // is `MaitriDocumentValueValue`, which says nothing.
  MaitriDocumentValueValue: 'MaitriRelation',
  // `{start, end}` — the muhurta windows of both panchang documents.
  DailyPanchangDocumentAbhijitMuhurta: 'TimeWindow',
  // One house system's cusps in `ChalitDocument`, which publishes four.
  ChalitDocumentEqual: 'ChalitHouses',
  // Pratyantardasha, sookshma and pran dasha (levels 3–5) nest one `children[]` deeper each; the path-derived
  // names grow a `ChildrenItem` per level and outrun the line length.
  DashaDocumentSystemsVimshottariPeriodsItemChildrenItemChildrenItem:
    'DashaVimshottariPratyantardasha',
  DashaVimshottariPratyantardashaChildrenItem: 'DashaVimshottariSookshma',
  DashaVimshottariSookshmaChildrenItem: 'DashaVimshottariPran',
  DashaDocumentSystemsCharaPeriodsItemChildrenItemChildrenItem: 'DashaCharaPratyantardasha',
  DashaCharaPratyantardashaChildrenItem: 'DashaCharaSookshma',
  DashaCharaSookshmaChildrenItem: 'DashaCharaPran',
  // `options.disclaimer` in its object form, `{name, url?}`.
  CalculationOptionsDisclaimer: 'Disclaimer',
  ReadingLagnaDocumentLagna: 'ReadingLagna',
  ReadingLagnaEntry: 'ReadingEntry',
  // `{en?, hi?}`: every text the report routes write, keyed by language.
  ReadingEntryText: 'LocalizedText',
  ReadingNakshatraDocumentNakshatra: 'ReadingNakshatra',
  // One house of the house-lords reading: its sign, the lord, where the lord sits.
  ReadingHouseLordsDocumentHouseLordsItem: 'HouseLord',
  // The summaries (API 0.9.1): `{level, text}` overall, and `{area, level,
  // text}` per life area — the same two shapes in the horoscope and the
  // varshphal reading, whichever of the two the generator meets first.
  HoroscopeDocumentSummary: 'ReadingSummary',
  VarshphalReadingDocumentSummary: 'ReadingSummary',
  HoroscopeDocumentAreasItem: 'AreaSummary',
  VarshphalReadingDocumentAreasItem: 'AreaSummary',
  // One transit behind a horoscope: for the site, not the reader.
  HoroscopeDocumentBasisItem: 'HoroscopeTransit',
  // One graha of the grahas reading; one yoga of the yogas reading.
  ReadingGrahasDocumentGrahasItem: 'GrahaReading',
  ReadingYogasDocumentYogasItem: 'YogaReading',
  // One mahadasha of the Vimshottari reading, its antardashas, and the
  // houses it acts on.
  VimshottariReadingDocumentPeriodsItem: 'MahadashaReading',
  MahadashaReadingAntardashasItem: 'AntardashaReading',
  MahadashaReadingAreasItem: 'MahadashaArea',
  // One period (mudda dasha) of the varshphal year.
  VarshphalReadingDocumentMonthsItem: 'VarshphalPeriod',
  // One ingress or station of the year's transit calendar.
  TransitEventsDocumentEventsItem: 'TransitEvent',
  // The life-areas reading: its summary, one area, and a dasha period that
  // brings the area forward.
  LifeAreasDocumentSummary: 'LifeAreasSummary',
  LifeAreasDocumentAreasItem: 'LifeArea',
  LifeAreaPeriodsItem: 'LifeAreaPeriod',
  // The kundli report's parts. The gateway infers their schemas apart from
  // the parts' own routes, so they are not always the same shapes; they get
  // names of their own rather than the generated `KundliReportDocument…`.
  KundliReportDocumentGrahasItem: 'KundliReportGraha',
  KundliReportDocumentHouseLordsItem: 'KundliReportHouseLord',
  KundliReportDocumentLifeAreas: 'KundliReportLifeAreas',
  KundliReportDocumentVarshphal: 'KundliReportVarshphal',
  KundliReportDocumentVimshottari: 'KundliReportVimshottari',
  KundliReportVimshottariPeriodsItem: 'KundliReportMahadasha',
  PlacesDocumentPlacesItem: 'Place',
  // A PDF's letterhead (API 0.14): the same shape on all four PDF routes, so
  // one class rather than one per request.
  PdfKundliRequestBranding: 'PdfBranding',
};

/**
 * Prose for the shapes the snapshot writes inline and therefore never
 * describes. Everything else takes its doc comment from the schema.
 */
const DESCRIPTIONS = {
  Birth: [
    'A wall clock, a place, and at most one of `timezone` / `utcOffset`.',
    '',
    'Every birth-based operation takes the same object, so it is worth',
    'building once and passing everywhere. The "at most one zone" rule is the',
    "API's: sending both is a `400`.",
  ].join('\n'),
  CalculationOptions: [
    'Ayanamsa, label languages, engine pin and disclaimer.',
    '',
    'Every field is optional; the gateway applies its own defaults',
    '(`lahiri`, `en`) for the ones left out. The house system is not here:',
    'only the kundli PDF takes one, on `PdfKundliOptions`.',
  ].join('\n'),
  PdfKundliOptions: [
    "The kundli PDF's options: `CalculationOptions` plus `houseSystem`.",
    '',
    '`houseSystem` picks the bhava chalit the PDF prints (default',
    '`placidus`); every other route refuses it with a `400`.',
  ].join('\n'),
  'CalculationOptions.language': [
    'The languages labels should come back in. Always a list here —',
    "`language: ['en', 'hi']` — and a single language is written to the wire",
    'as the bare string the API documents.',
  ].join(' '),
};
DESCRIPTIONS['PdfKundliOptions.language'] = DESCRIPTIONS['CalculationOptions.language'];

/** `GET /v1/reference/{list}` rows are open by design — no class for them. */
const OPERATIONS_WITHOUT_DOCUMENT = new Set(['getReferenceList']);

// ---------------------------------------------------------------------------
// Names
// ---------------------------------------------------------------------------

/**
 * Words PHP will not accept as a property name.
 *
 * Far shorter than Dart's list: PHP has kept reserved words legal as member
 * names since 7.0, and `$this` is the only one a property cannot be called.
 * The snapshot has no such key today; the guard is here so a future one is
 * renamed instead of emitting a parse error.
 */
const RESERVED = new Set(['this']);

/** `utc_offset` / `UtcOffset` / `utcOffset` → `['utc', 'offset']`. */
function words(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
}

function pascal(name) {
  return words(name)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

function camel(name) {
  const p = pascal(name);
  const lower = p[0].toLowerCase() + p.slice(1);
  return RESERVED.has(lower) ? `${lower}Value` : lower;
}

/** `whole_sign` → `WHOLE_SIGN`, the name a PHP class constant goes by. */
function constantName(value) {
  return words(value)
    .map((w) => w.toUpperCase())
    .join('_');
}

// ---------------------------------------------------------------------------
// PHP source helpers
// ---------------------------------------------------------------------------

function quote(text) {
  return `'${String(text).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** PSR-12's soft limit, which the emitted lines keep to wherever they can. */
const WIDTH = 120;

/** `text` broken on spaces into lines of at most `width` characters. */
function wrap(text, width) {
  const out = [];
  let line = '';
  for (const word of text.split(' ')) {
    if (line === '') line = word;
    else if (`${line} ${word}`.length <= width) line = `${line} ${word}`;
    else {
      out.push(line);
      line = word;
    }
  }
  if (line !== '') out.push(line);
  return out;
}

/**
 * A description as a `/** … *\/` block, with the blank lines OpenAPI allows.
 *
 * The snapshot writes a schema description as one long line; it is wrapped
 * here, and a tag that has to wrap continues indented the way PHPDoc does it.
 */
function docBlock(lines, indent = '') {
  const body = lines.filter((line) => line !== null);
  if (body.length === 0) return [];
  const width = WIDTH - indent.length - 3;
  const wrapped = [];
  for (const line of body) {
    if (line.length <= width) {
      wrapped.push(line);
      continue;
    }
    const [first, ...rest] = wrap(line, width);
    wrapped.push(first);
    for (const more of wrap(rest.join(' '), width - 4)) {
      wrapped.push(line.startsWith('@') ? `    ${more}` : more);
    }
  }
  return [
    `${indent}/**`,
    ...wrapped.map((line) => (line ? `${indent} * ${line}` : `${indent} *`)),
    `${indent} */`,
  ];
}

/**
 * One statement, broken over several lines when it is too long to read.
 *
 * Only `array_map()` ever gets long enough to matter — a map of lists of a
 * class names that class three times in one line — so that is the one call
 * this knows how to open up.
 */
function wrapStatement(line) {
  if (line.length <= WIDTH) return [line];
  const at = line.indexOf('array_map(');
  if (at < 0) return [line];
  const open = at + 'array_map('.length - 1;
  let depth = 0;
  let close = -1;
  for (let i = open; i < line.length; i += 1) {
    if (line[i] === '(') depth += 1;
    else if (line[i] === ')') {
      depth -= 1;
      if (depth === 0) {
        close = i;
        break;
      }
    }
  }
  if (close < 0) return [line];

  const inner = line.slice(open + 1, close);
  const args = [];
  let level = 0;
  let start = 0;
  for (let i = 0; i < inner.length; i += 1) {
    if (inner[i] === '(') level += 1;
    else if (inner[i] === ')') level -= 1;
    else if (inner[i] === ',' && level === 0) {
      args.push(inner.slice(start, i).trim());
      start = i + 1;
    }
  }
  args.push(inner.slice(start).trim());

  const indent = /^\s*/.exec(line)[0];
  const out = [`${line.slice(0, at)}array_map(`];
  for (const arg of args) {
    const closure = /^(static fn \([^)]*\): \S+ )=> (.*)$/.exec(arg);
    if (closure && `${indent}    ${arg},`.length > WIDTH) {
      out.push(`${indent}    ${closure[1].trimEnd()}`);
      out.push(`${indent}        => ${closure[2]},`);
    } else {
      out.push(`${indent}    ${arg},`);
    }
  }
  out.push(`${indent})${line.slice(close + 1)}`);
  return out;
}

/** A schema description, trimmed, as the lines of a doc block. */
function prose(text) {
  if (!text) return [];
  return String(text)
    .trim()
    .split('\n')
    .map((line) => line.replace(/\s+$/, ''));
}

/** A description squashed onto one line, for an `@param` tag. */
function oneLine(text) {
  if (!text) return '';
  return String(text).trim().replace(/\s+/g, ' ');
}

// ---------------------------------------------------------------------------
// Structural identity
// ---------------------------------------------------------------------------

/**
 * A schema reduced to the part of it PHP can see.
 *
 * `birth` and `options` are written out inline in 35-odd request bodies, and
 * two of those copies differ only in a `default` (`KP` defaults the ayanamsa
 * to `krishnamurti`). Validation keywords, defaults and prose change nothing
 * about the generated class, so they are dropped before comparing: what is
 * left is the shape, and equal shapes share one class.
 */
function shapeKey(schema) {
  // At the root, `{"type": ["null", "object"]}` and `{"type": "object"}` are
  // the same class: whether the *field* may be null is the field's business.
  // Inside, nullability is kept — `{a: string}` and `{a: string | null}` are
  // different classes.
  return JSON.stringify(shapeOf(schema, true));
}

function shapeOf(schema, root = false) {
  if (!schema || typeof schema !== 'object') return schema ?? null;
  if (schema.$ref) return { $ref: schema.$ref };
  const out = {};
  if (schema.type !== undefined) {
    let declared = Array.isArray(schema.type) ? [...schema.type].sort() : schema.type;
    if (root && Array.isArray(declared)) {
      const real = declared.filter((t) => t !== 'null');
      declared = real.length === 1 ? real[0] : real.length === 0 ? 'null' : real;
    }
    out.type = declared;
  }
  if (schema.anyOf) out.anyOf = schema.anyOf.map((branch) => shapeOf(branch));
  if (schema.properties) {
    out.properties = {};
    for (const key of Object.keys(schema.properties).sort()) {
      out.properties[key] = shapeOf(schema.properties[key]);
    }
  }
  if (schema.required) out.required = [...schema.required].sort();
  if (schema.items) out.items = shapeOf(schema.items);
  if (schema.additionalProperties === true) out.additionalProperties = true;
  else if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
    out.additionalProperties = shapeOf(schema.additionalProperties);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A resolved PHP type.
 *
 * `kind` drives the `fromArray()` / `toArray()` expressions; `declared` is
 * what the promoted property is typed as and `doc` is what PHPDoc says, which
 * is where the generics live — PHP's own `array` says nothing about what is
 * inside it and PHPStan at level 9 insists on knowing.
 */
function type(kind, extra = {}) {
  return { kind, nullable: false, ...extra };
}

/** The PHP type declaration for `t`. */
function declared(t) {
  const q = t.nullable ? '?' : '';
  switch (t.kind) {
    case 'string':
      return `${q}string`;
    case 'int':
      return `${q}int`;
    case 'float':
      return `${q}float`;
    case 'bool':
      return `${q}bool`;
    case 'class':
      return `${q}${t.name}`;
    case 'stringOrClass':
      // A union takes no `?`; null is spelled out.
      return `string|${t.of.name}${t.nullable ? '|null' : ''}`;
    case 'stringList':
    case 'list':
    case 'map':
    case 'json':
      return `${q}array`;
    case 'any':
      // `mixed` already includes null; `?mixed` is a parse error.
      return 'mixed';
    default:
      throw new Error(`unknown kind ${t.kind}`);
  }
}

/** The PHPDoc type for `t`, generics included. */
function docType(t) {
  const suffix = t.nullable && t.kind !== 'any' ? '|null' : '';
  switch (t.kind) {
    case 'string':
      return `string${suffix}`;
    case 'int':
      return `int${suffix}`;
    case 'float':
      return `float${suffix}`;
    case 'bool':
      return `bool${suffix}`;
    case 'class':
      return `${t.name}${suffix}`;
    case 'stringOrClass':
      return `string|${t.of.name}${suffix}`;
    case 'stringList':
      return `list<string>${suffix}`;
    case 'list':
      return `list<${docType(t.of)}>${suffix}`;
    case 'map':
      return `array<string, ${docType(t.of)}>${suffix}`;
    case 'json':
      return `array<string, mixed>${suffix}`;
    case 'any':
      return 'mixed';
    default:
      throw new Error(`unknown kind ${t.kind}`);
  }
}

/** True when PHP's own type declaration already says everything PHPDoc would. */
function needsDocType(t) {
  return ['stringList', 'list', 'map', 'json'].includes(t.kind);
}

/** True when a value of `t` is already array-and-scalar and needs no mapping. */
function writesPlainly(t) {
  if (['string', 'int', 'float', 'bool', 'json', 'any', 'stringList'].includes(t.kind)) return true;
  if (t.kind === 'list' || t.kind === 'map') return writesPlainly(t.of);
  return false;
}

/** The names the nested `foreach`es use, one pair per level. */
function loopNames(depth) {
  if (depth === 0) return ['$key', '$value'];
  if (depth === 1) return ['$innerKey', '$innerValue'];
  return [`$key${depth + 1}`, `$value${depth + 1}`];
}

/** The name a nested closure gives its parameter, one per level. */
function closureName(depth) {
  return depth === 0 ? '$v' : depth === 1 ? '$item' : `$v${depth + 1}`;
}

/**
 * The expression that reads `expr` (a `mixed`) as a `t`.
 *
 * Everything but a map is one expression; maps are a `foreach`, which the
 * caller hoists into a local before the `return new self(…)`.
 */
function readExpr(t, expr, depth = 0) {
  if (t.nullable) {
    switch (t.kind) {
      case 'string':
        return `Json::stringOrNull(${expr})`;
      case 'int':
        return `Json::intOrNull(${expr})`;
      case 'float':
        return `Json::floatOrNull(${expr})`;
      case 'bool':
        return `Json::boolOrNull(${expr})`;
      case 'stringList':
        return `Json::languagesOrNull(${expr})`;
      case 'json':
        return `Json::objectOrNull(${expr})`;
      case 'any':
        return expr;
      default:
        // A class or a list: the guard has to be written out, so `expr` is
        // always a plain variable by the time it gets here.
        return `${expr} === null ? null : ${readNonNull(t, expr, depth)}`;
    }
  }
  return readNonNull(t, expr, depth);
}

function readNonNull(t, expr, depth) {
  switch (t.kind) {
    case 'string':
      return `Json::string(${expr})`;
    case 'int':
      return `Json::int(${expr})`;
    case 'float':
      return `Json::float(${expr})`;
    case 'bool':
      return `Json::bool(${expr})`;
    case 'stringList':
      return `Json::languages(${expr})`;
    case 'json':
      return `Json::object(${expr})`;
    case 'any':
      return expr;
    case 'class':
      return `${t.name}::fromArray(Json::object(${expr}))`;
    case 'stringOrClass':
      return `is_string(${expr}) ? ${expr} : ${t.of.name}::fromArray(Json::object(${expr}))`;
    case 'list': {
      const name = closureName(depth);
      const element = readExpr(t.of, name, depth + 1);
      const cast = `static fn (mixed ${name}): ${declared(t.of)} => ${element}`;
      return `array_map(${cast}, Json::list(${expr}))`;
    }
    default:
      throw new Error(`${t.kind} is read with a foreach, not an expression`);
  }
}

/** Reads a map (and any map nested inside it) into `target`. */
function readMapLines(target, t, source, indent, depth = 0) {
  const [key, value] = loopNames(depth);
  const lines = [
    `${indent}${target} = [];`,
    `${indent}foreach (Json::object(${source}) as ${key} => ${value}) {`,
  ];
  if (t.of.kind === 'map' && !t.of.nullable) {
    const inner = depth === 0 ? '$inner' : `$inner${depth + 1}`;
    lines.push(...readMapLines(inner, t.of, value, `${indent}    `, depth + 1));
    lines.push(`${indent}    ${target}[${key}] = ${inner};`);
  } else {
    lines.push(`${indent}    ${target}[${key}] = ${readExpr(t.of, value, depth + 1)};`);
  }
  lines.push(`${indent}}`);
  return lines;
}

/**
 * The expression that turns a value of `t` back into JSON.
 *
 * Answers `{pre, expr}`: `pre` is the statements that have to run first, which
 * is how a container of containers is written without an un-annotated
 * `array` closure parameter (PHPStan level 9 rejects those).
 */
function writeValue(t, source, varName, indent, depth = 0) {
  if (writesPlainly(t)) return { pre: [], expr: source };
  if (t.kind === 'class') return { pre: [], expr: `${source}->toArray()` };
  if (t.kind === 'stringOrClass') {
    return { pre: [], expr: `is_string(${source}) ? ${source} : ${source}->toArray()` };
  }
  if (t.kind === 'list' || t.kind === 'map') {
    if (t.of.kind === 'class' && !t.of.nullable) {
      const name = closureName(depth);
      const cast = `static fn (${t.of.name} ${name}): array => ${name}->toArray()`;
      return { pre: [], expr: `array_map(${cast}, ${source})` };
    }
    const [key, value] = loopNames(depth);
    const inner = writeValue(t.of, value, `${varName}Item`, `${indent}    `, depth + 1);
    return {
      pre: [
        `${indent}$${varName} = [];`,
        `${indent}foreach (${source} as ${key} => ${value}) {`,
        ...inner.pre,
        `${indent}    $${varName}[${key}] = ${inner.expr};`,
        `${indent}}`,
      ],
      expr: `$${varName}`,
    };
  }
  throw new Error(`cannot write kind ${t.kind}`);
}

// ---------------------------------------------------------------------------
// The model graph
// ---------------------------------------------------------------------------

const doc = JSON.parse(await readFile(schemaFile, 'utf8'));
const pkg = JSON.parse(await readFile(join(packageDir, 'package.json'), 'utf8'));
const sdkVersion = pkg.version;
if (!sdkVersion) throw new Error('package.json has no version');

/** name → { name, description, origin, fields } for every class but `LabelledId`. */
const classes = new Map();
/** shapeKey → class name, so one shape is one class. */
const shapes = new Map();
/** Constructs the generator could not represent exactly, reported at the end. */
const fallbacks = [];

function refName(ref) {
  const raw = ref.replace('#/components/schemas/', '');
  return SCHEMA_RENAMES[raw] ?? raw;
}

/**
 * Resolve one schema to a PHP type, defining classes as it goes.
 *
 * `hint` is the name a class would get if this schema turns out to need one:
 * the owning class plus the property, so `KundliDocument.birth` is
 * `KundliDocumentBirth` and the value type of its `positions` map is
 * `KundliDocumentPositionsValue`.
 */
function resolve(schema, hint, origin) {
  if (!schema || typeof schema !== 'object') return type('any');
  if (schema.$ref) return type('class', { name: refName(schema.$ref) });

  if (schema.anyOf) return resolveAnyOf(schema, hint, origin);

  const listed = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const nullable = listed.includes('null');
  const rest = listed.filter((t) => t !== 'null');

  if (rest.length === 0 && nullable) {
    // `{"type": "null"}`: the engine always answers null here (choghadiya's
    // `planet`). There is no PHP type for "always null" worth having, so the
    // field is a `mixed` the caller can ignore.
    fallbacks.push(`${origin}: \`type: "null"\` → mixed`);
    return type('any', { nullable: true });
  }
  if (rest.length > 1) {
    fallbacks.push(`${origin}: \`type: ${JSON.stringify(listed)}\` → mixed`);
    return type('any', { nullable: true });
  }

  const base = rest[0] ?? (schema.properties ? 'object' : schema.items ? 'array' : undefined);
  let resolved;
  switch (base) {
    case 'string':
      resolved = type('string');
      break;
    case 'integer':
      resolved = type('int');
      break;
    case 'number':
      // `number` is `float`, except where the schema enumerates whole
      // numbers (`levels: 1 | 2 | 3 | 4 | 5`) and an int reads better on the wire.
      resolved = type(allIntegerEnum(schema) ? 'int' : 'float');
      break;
    case 'boolean':
      resolved = type('bool');
      break;
    case 'array':
      resolved = type('list', { of: resolve(schema.items, `${hint}Item`, `${origin}[]`) });
      break;
    case 'object':
      resolved = resolveObject(schema, hint, origin);
      break;
    default:
      fallbacks.push(`${origin}: no \`type\` → mixed`);
      resolved = type('any', { nullable: true });
  }
  return nullable ? { ...resolved, nullable: true } : resolved;
}

function allIntegerEnum(schema) {
  return Array.isArray(schema.enum) && schema.enum.every((v) => Number.isInteger(v));
}

function resolveObject(schema, hint, origin) {
  if (schema.properties) return type('class', { name: defineClass(schema, hint, origin) });
  const extra = schema.additionalProperties;
  if (extra && typeof extra === 'object') {
    return type('map', { of: resolve(extra, `${hint}Value`, `${origin}{}`) });
  }
  // `additionalProperties: true`, or no properties at all: an open row.
  return type('json');
}

function resolveAnyOf(schema, hint, origin) {
  const branches = schema.anyOf;
  const isNull = (b) =>
    b.type === 'null' ||
    (Array.isArray(b.type) && !b.type.includes('object') && b.type.every((t) => t === 'null'));
  const nullable =
    branches.some(isNull) || branches.some((b) => Array.isArray(b.type) && b.type.includes('null'));
  const real = branches.filter((b) => !isNull(b));

  // `options.language`: `'en'` or `['en', 'hi']` on the wire. Callers get one
  // type — a list — and a single-element list goes out as the bare string.
  const stringOrList =
    real.length === 2 &&
    real.some((b) => b.type === 'string') &&
    real.some((b) => b.type === 'array' && b.items?.type === 'string');
  if (stringOrList) return type('stringList', { nullable });

  if (real.length === 1) return { ...resolve(real[0], hint, origin), nullable: true };

  // `options.disclaimer`: `'default'` / `'off'`, or `{name, url?}`. PHP can
  // say that exactly, so it gets a union rather than a `mixed`.
  const stringOrObject =
    real.length === 2 &&
    real.some((b) => b.type === 'string') &&
    real.some((b) => b.type === 'object' && b.properties);
  if (stringOrObject) {
    const object = real.find((b) => b.type === 'object');
    return type('stringOrClass', { nullable, of: resolve(object, hint, origin) });
  }

  // `levels: 1 | 2 | 3 | 4 | 5` arrives as five single-value `number` branches.
  if (real.length > 1 && real.every((b) => b.type === 'number' && allIntegerEnum(b))) {
    return type('int', { nullable });
  }
  if (real.length > 1 && real.every((b) => b.type === real[0].type && !b.properties)) {
    return { ...resolve(real[0], hint, origin), nullable };
  }

  fallbacks.push(`${origin}: \`anyOf\` of ${real.length} unrelated shapes → mixed`);
  return type('any', { nullable: true });
}

/**
 * Define (or reuse) the class for an object schema and answer its name.
 *
 * Equal shapes share a class, which is what keeps `Birth` and
 * `CalculationOptions` single classes instead of 35 copies apiece.
 */
function defineClass(schema, preferred, origin) {
  const key = shapeKey(schema);
  const existing = shapes.get(key);
  if (existing) return existing;

  let name = NESTED_RENAMES[preferred] ?? preferred;
  if (classes.has(name)) {
    let n = 2;
    while (classes.has(`${name}${n}`)) n += 1;
    fallbacks.push(`${origin}: name ${name} was taken → ${name}${n}`);
    name = `${name}${n}`;
  }

  const entry = {
    name,
    description: DESCRIPTIONS[name] ?? schema.description,
    origin,
    fields: [],
  };
  classes.set(name, entry);
  shapes.set(key, name);

  if (!schema.properties) {
    // A document that is a bare map (`MaitriDocument` is planet → planet →
    // relation). A PHP array has no place to hang `fromArray()`, so the class
    // wraps the map and reads through to it; `toArray()` still answers the
    // map itself, so the wire shape is unchanged.
    entry.valueType = resolve(
      schema.additionalProperties && typeof schema.additionalProperties === 'object'
        ? schema.additionalProperties
        : {},
      `${name}Value`,
      `${origin}{}`,
    );
    return name;
  }

  const required = new Set(schema.required ?? []);
  const used = new Map();
  for (const [wire, propSchema] of Object.entries(schema.properties)) {
    let phpName = camel(wire);
    if (used.has(phpName)) {
      fallbacks.push(
        `${name}: \`${wire}\` and \`${used.get(phpName)}\` both camelCase to ${phpName}`,
      );
      phpName = `${phpName}${pascal(wire)}`;
    }
    used.set(phpName, wire);
    const fieldType = resolve(propSchema, name + pascal(wire), `${name}.${wire}`);
    entry.fields.push({
      wire,
      name: phpName,
      description: DESCRIPTIONS[`${name}.${wire}`] ?? propSchema.description,
      // Anything the schema does not require, and anything it requires but
      // allows to be null, is optional in PHP: the gateway omits keys it has
      // nothing to say about.
      type: { ...fieldType, nullable: fieldType.nullable || !required.has(wire) },
    });
  }
  // PHP will not take a required parameter after an optional one, so the
  // fields the schema requires come first. Callers use named arguments, so
  // the order is the constructor's business and nobody else's.
  entry.fields.sort((a, b) => Number(a.type.nullable) - Number(b.type.nullable));
  return name;
}

// ---------------------------------------------------------------------------
// Walk the document
// ---------------------------------------------------------------------------

const schemas = doc.components.schemas;
const bodyOf = (op) => op.requestBody?.content?.['application/json']?.schema;
const okOf = (op) => op.responses?.['200']?.content?.['application/json']?.schema;

// `birth` and `options` first, so the 35 inline copies find them already
// defined and every request refers to the same two classes.
const kundliBody = bodyOf(doc.paths['/v1/kundli'].post);
defineClass(kundliBody.properties.birth, 'Birth', 'POST /v1/kundli birth');
defineClass(kundliBody.properties.options, 'CalculationOptions', 'POST /v1/kundli options');
// The kundli PDF's options add `house_system` (the chalit it prints), which no
// other route takes; after `CalculationOptions`, so its `disclaimer` object
// finds `Disclaimer` already defined.
const pdfKundliBody = bodyOf(doc.paths['/v1/pdf/kundli'].post);
defineClass(pdfKundliBody.properties.options, 'PdfKundliOptions', 'POST /v1/pdf/kundli options');

// A `/v1/panchang/month` day carries the same `{amanta, purnimanta}` pair as
// `masa` that `/v1/calendar/vikram-samvat` answers, and `PanchangMonthDocument`
// comes first; name the pair after the document so the day reuses it.
defineClass(
  schemas.VikramSamvatDocument,
  'VikramSamvatDocument',
  '#/components/schemas/VikramSamvatDocument',
);

for (const [rawName, schema] of Object.entries(schemas)) {
  if (rawName === 'LabelledId') continue; // its own file, written out below
  defineClass(schema, SCHEMA_RENAMES[rawName] ?? rawName, `#/components/schemas/${rawName}`);
}

const operations = [];
for (const [path, item] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(item)) {
    if (!op.operationId) continue;
    const id = op.operationId;
    const body = bodyOf(op);
    let requestType = null;
    if (body) {
      const name = REQUEST_NAMES[id];
      if (!name) throw new Error(`${id} has a request body but no name in REQUEST_NAMES`);
      requestType = defineClass(body, name, `${method.toUpperCase()} ${path} body`);
    }

    let documentType = null;
    const ok = okOf(op);
    if (ok && !OPERATIONS_WITHOUT_DOCUMENT.has(id)) {
      const data = ok.properties?.data ?? ok;
      const name = INLINE_DOCUMENT_NAMES[id];
      documentType = data.$ref
        ? refName(data.$ref)
        : defineClass(
            data,
            name ?? `${pascal(id)}Document`,
            `${method.toUpperCase()} ${path} data`,
          );
    }
    const metaName = INLINE_META_NAMES[id];
    if (metaName && ok?.properties?.meta && !ok.properties.meta.$ref) {
      defineClass(ok.properties.meta, metaName, `${method.toUpperCase()} ${path} meta`);
    }

    operations.push({
      id,
      method: method.toUpperCase(),
      path,
      tag: op.tags?.[0] ?? '',
      requestType,
      documentType,
    });
  }
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

/** The `@param` block of a promoted constructor. */
function constructorDoc(fields) {
  const tags = [];
  for (const f of fields) {
    if (!needsDocType(f.type) && !f.description) continue;
    const description = oneLine(f.description);
    tags.push(`@param ${docType(f.type)} $${f.name}${description ? ` ${description}` : ''}`);
  }
  return docBlock(tags, '    ');
}

function emitConstructor(entry) {
  const out = [...constructorDoc(entry.fields)];
  out.push('    public function __construct(');
  for (const f of entry.fields) {
    const suffix = f.type.nullable ? ' = null' : '';
    out.push(`        public ${declared(f.type)} $${f.name}${suffix},`);
  }
  out.push('    ) {');
  out.push('    }');
  return out;
}

function emitFromArray(entry) {
  const out = [
    ...docBlock(['@param array<string, mixed> $data'], '    '),
    '    public static function fromArray(array $data): self',
    '    {',
  ];
  const pre = [];
  const args = [];
  for (const f of entry.fields) {
    const raw = `$data[${quote(f.wire)}] ?? null`;
    if (f.type.kind === 'map') {
      if (f.type.nullable) {
        pre.push(`        $${f.name}Raw = ${raw};`);
        pre.push(`        $${f.name} = null;`);
        pre.push(`        if ($${f.name}Raw !== null) {`);
        pre.push(...readMapLines(`$${f.name}`, f.type, `$${f.name}Raw`, '            '));
        pre.push('        }');
      } else {
        pre.push(...readMapLines(`$${f.name}`, f.type, raw, '        '));
      }
      args.push(`            ${f.name}: $${f.name},`);
      continue;
    }
    if (f.type.kind === 'stringOrClass') {
      // Two guards on one value read better as their own statement than as a
      // nested ternary, which PHP 8 will not parse without parentheses anyway.
      const guard = f.type.nullable
        ? `is_string($${f.name}Raw) || $${f.name}Raw === null`
        : `is_string($${f.name}Raw)`;
      pre.push(`        $${f.name}Raw = ${raw};`);
      pre.push(`        $${f.name} = ${guard}`);
      pre.push(`            ? $${f.name}Raw`);
      pre.push(`            : ${f.type.of.name}::fromArray(Json::object($${f.name}Raw));`);
      args.push(`            ${f.name}: $${f.name},`);
      continue;
    }
    if (f.type.nullable && ['class', 'list'].includes(f.type.kind)) {
      // The guard mentions the value twice, so it is read into a local first.
      pre.push(`        $${f.name}Raw = ${raw};`);
      args.push(`            ${f.name}: ${readExpr(f.type, `$${f.name}Raw`)},`);
      continue;
    }
    args.push(`            ${f.name}: ${readExpr(f.type, raw)},`);
  }
  out.push(...pre);
  if (pre.length > 0) out.push('');
  out.push('        return new self(');
  out.push(...args);
  out.push('        );');
  out.push('    }');
  return out;
}

function emitToArray(entry) {
  const out = [
    ...docBlock(
      ['This value as an array, with every null key left out.', '', '@return array<string, mixed>'],
      '    ',
    ),
    '    public function toArray(): array',
    '    {',
    '        $out = [];',
  ];
  for (const f of entry.fields) {
    const property = `$this->${f.name}`;
    if (!f.type.nullable) {
      const value = writeValue(f.type, property, f.name, '        ');
      out.push(...value.pre);
      out.push(`        $out[${quote(f.wire)}] = ${value.expr};`);
      continue;
    }
    out.push(`        if (${property} !== null) {`);
    if (f.type.kind === 'stringList') {
      // A single language goes out as the bare string the gateway documents.
      out.push(
        `            $out[${quote(f.wire)}] = count(${property}) === 1 ? ${property}[0] : ${property};`,
      );
    } else {
      const value = writeValue({ ...f.type, nullable: false }, property, f.name, '            ');
      out.push(...value.pre);
      out.push(`            $out[${quote(f.wire)}] = ${value.expr};`);
    }
    out.push('        }');
  }
  out.push('');
  out.push('        return $out;');
  out.push('    }');
  return out;
}

/** A document that is a bare map: the class wraps it and reads through. */
function emitMapClass(entry) {
  const value = entry.valueType;
  const out = [
    ...docBlock([`@param array<string, ${docType(value)}> $values`], '    '),
    '    public function __construct(',
    '        public array $values,',
    '    ) {',
    '    }',
    '',
    ...docBlock(
      ['Reads the map, keyed as the API keys it.', '', '@param array<string, mixed> $data'],
      '    ',
    ),
    '    public static function fromArray(array $data): self',
    '    {',
  ];
  if (value.kind === 'map' && !value.nullable) {
    out.push('        $values = [];');
    out.push('        foreach ($data as $key => $value) {');
    out.push(...readMapLines('$inner', value, '$value', '            ', 1));
    out.push('            $values[$key] = $inner;');
    out.push('        }');
  } else {
    out.push('        $values = [];');
    out.push('        foreach ($data as $key => $value) {');
    out.push(`            $values[$key] = ${readExpr(value, '$value', 1)};`);
    out.push('        }');
  }
  out.push('');
  out.push('        return new self($values);');
  out.push('    }');
  out.push('');
  out.push(
    ...docBlock(
      [
        'The entry under $key, or null when the API left it out.',
        '',
        `@return ${docType({ ...value, nullable: true })}`,
      ],
      '    ',
    ),
  );
  out.push(
    `    public function get(string $key): ${declared({ ...value, nullable: true })}`,
    '    {',
    '        return $this->values[$key] ?? null;',
    '    }',
    '',
  );
  out.push(...docBlock(['This document as an array.', '', '@return array<string, mixed>'], '    '));
  out.push('    public function toArray(): array');
  out.push('    {');
  const written = writeValue(value, '$value', 'values', '            ', 1);
  if (writesPlainly(value)) {
    out.push('        return $this->values;');
  } else {
    out.push('        $out = [];');
    out.push('        foreach ($this->values as $key => $value) {');
    out.push(...written.pre);
    out.push(`            $out[$key] = ${written.expr};`);
    out.push('        }');
    out.push('');
    out.push('        return $out;');
  }
  out.push('    }');
  return out;
}

function emitClass(entry) {
  const raw = entry.valueType
    ? emitMapClass(entry)
    : [...emitConstructor(entry), '', ...emitFromArray(entry), '', ...emitToArray(entry)];
  const body = raw.flatMap(wrapStatement);
  const description = prose(entry.description);
  return [
    ...docBlock([
      ...description,
      ...(description.length > 0 ? [''] : []),
      `Wire shape: \`${entry.origin}\`.`,
    ]),
    `final readonly class ${entry.name}`,
    '{',
    ...body,
    '}',
  ].join('\n');
}

/**
 * A holder of the string constants an enum property accepts.
 *
 * Enums stay `string` on the fields themselves — the gateway adds values
 * between SDK releases and a PHP enum would turn that into a crash — but the
 * values it lists today are worth spelling once so callers can autocomplete
 * them instead of quoting a slug from the docs.
 */
function emitConstants(name, description, values) {
  const out = [...docBlock(prose(description)), `final class ${name}`, '{'];
  for (const value of values) {
    out.push(`    public const ${constantName(value)} = ${quote(value)};`);
  }
  out.push('');
  out.push(
    ...docBlock(['Every value the snapshot lists, in its order.', '', '@var list<string>'], '    '),
  );
  out.push('    public const VALUES = [');
  for (const value of values) out.push(`        ${quote(value)},`);
  out.push('    ];');
  out.push('}');
  return out.join('\n');
}

/** A model file: header, namespace, the imports the body turns out to need. */
function modelFile(name, what, body) {
  const imports = [];
  if (/\bJson::/.test(body)) imports.push(`use ${GENERATED_NAMESPACE}\\Json;`);
  if (/\bLabelledId\b/.test(body)) imports.push(`use ${GENERATED_NAMESPACE}\\LabelledId;`);
  return [
    HEADER(what),
    `namespace ${MODELS_NAMESPACE};`,
    '',
    ...(imports.length > 0 ? [imports.join('\n'), ''] : []),
    body,
    '',
  ].join('\n');
}

const files = {};

for (const entry of [...classes.values()].sort((a, b) => (a.name < b.name ? -1 : 1))) {
  files[`Models/${entry.name}.php`] = modelFile(
    entry.name,
    `\`${entry.origin}\` as a PHP class.`,
    emitClass(entry),
  );
}

files['Models/Ayanamsa.php'] = modelFile(
  'Ayanamsa',
  'The `ayanamsa` values the snapshot lists.',
  emitConstants(
    'Ayanamsa',
    'The ayanamsas `CalculationOptions::$ayanamsa` accepts.',
    kundliBody.properties.options.properties.ayanamsa.enum,
  ),
);

files['Models/HouseSystem.php'] = modelFile(
  'HouseSystem',
  'The `house_system` values the snapshot lists.',
  emitConstants(
    'HouseSystem',
    'The house systems `PdfKundliOptions::$houseSystem` accepts.',
    pdfKundliBody.properties.options.properties.house_system.enum,
  ),
);

files['Models/Varga.php'] = modelFile(
  'Varga',
  'The divisional chart ids the snapshot lists.',
  emitConstants(
    'Varga',
    'The divisional charts `KundliChartRequest::$varga` and `VargasRequest::$vargas` accept.',
    bodyOf(doc.paths['/v1/kundli/chart'].post).properties.varga.enum,
  ),
);

files['Models/ChartStyle.php'] = modelFile(
  'ChartStyle',
  'The `style` values the snapshot lists.',
  emitConstants(
    'ChartStyle',
    'The styles `KundliChartRequest::$style` accepts.',
    bodyOf(doc.paths['/v1/kundli/chart'].post).properties.style.enum,
  ),
);

// ---------------------------------------------------------------------------
// The hand-written half of the output
// ---------------------------------------------------------------------------

const labelled = schemas.LabelledId;

files['Generated/LabelledId.php'] = `${HEADER(
  '`LabelledId`, the shape every named id in every document shares.',
)}
namespace ${GENERATED_NAMESPACE};

${docBlock([...prose(labelled.description), '', 'Wire shape: `#/components/schemas/LabelledId`.']).join('\n')}
final readonly class LabelledId
{
${docBlock(
  [
    `@param string $id ${oneLine(labelled.properties.id.description)}`,
    `@param string $name ${oneLine(labelled.properties.name.description)}`,
    `@param array<string, string>|null $names ${oneLine(labelled.properties.names.description)}`,
  ],
  '    ',
).join('\n')}
    public function __construct(
        public string $id,
        public string $name,
        public ?array $names = null,
    ) {
    }

    /**
     * Reads an \`{id, name, names?}\` object.
     *
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $namesRaw = $data['names'] ?? null;
        $names = null;
        if ($namesRaw !== null) {
            $names = [];
            foreach (Json::object($namesRaw) as $key => $value) {
                $names[$key] = Json::string($value);
            }
        }

        return new self(
            id: Json::string($data['id'] ?? null),
            name: Json::string($data['name'] ?? null),
            names: $names,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['id'] = $this->id;
        $out['name'] = $this->name;
        if ($this->names !== null) {
            $out['names'] = $this->names;
        }

        return $out;
    }
}
`;

files['Generated/Json.php'] = `${HEADER(
  'Cast helpers. `json_decode()` answers `mixed`, and PHPStan at level 9 will\n * not let a `mixed` reach a `string` parameter; narrowing here keeps every\n * generated `fromArray()` one expression per field and puts a readable\n * message on a malformed payload instead of a `TypeError` three frames away.',
)}
namespace ${GENERATED_NAMESPACE};

use UnexpectedValueException;

/**
 * Reads the values a decoded JSON body holds, or says what was wrong with one.
 */
final class Json
{
    /**
     * A JSON object, with the string keys JSON gives it.
     *
     * \`json_decode($body, true)\` turns a key that looks like an integer into
     * one, so the keys are put back the way the API wrote them.
     *
     * @return array<string, mixed>
     */
    public static function object(mixed $value): array
    {
        if (!is_array($value)) {
            self::fail('an object', $value);
        }

        $out = [];
        foreach ($value as $key => $item) {
            $out[(string) $key] = $item;
        }

        return $out;
    }

    /**
     * A JSON array.
     *
     * @return list<mixed>
     */
    public static function list(mixed $value): array
    {
        if (!is_array($value) || !array_is_list($value)) {
            self::fail('an array', $value);
        }

        return $value;
    }

    /** A string. */
    public static function string(mixed $value): string
    {
        if (!is_string($value)) {
            self::fail('a string', $value);
        }

        return $value;
    }

    /** An integer, accepting the whole \`float\` a large JSON number decodes to. */
    public static function int(mixed $value): int
    {
        if (is_int($value)) {
            return $value;
        }
        if (is_float($value) && floor($value) === $value) {
            return (int) $value;
        }

        self::fail('an integer', $value);
    }

    /** A number, accepting the \`int\` JSON writes for a whole one. */
    public static function float(mixed $value): float
    {
        if (is_float($value)) {
            return $value;
        }
        if (is_int($value)) {
            return (float) $value;
        }

        self::fail('a number', $value);
    }

    /** A boolean. */
    public static function bool(mixed $value): bool
    {
        if (!is_bool($value)) {
            self::fail('a boolean', $value);
        }

        return $value;
    }

    /**
     * The SDK's list-of-languages shape: the API writes a lone language as a
     * bare string and several as an array.
     *
     * @return list<string>
     */
    public static function languages(mixed $value): array
    {
        if (is_string($value)) {
            return [$value];
        }

        return array_map(static fn (mixed $item): string => self::string($item), self::list($value));
    }

    /**
     * @return array<string, mixed>|null
     */
    public static function objectOrNull(mixed $value): ?array
    {
        return $value === null ? null : self::object($value);
    }

    /**
     * @return list<mixed>|null
     */
    public static function listOrNull(mixed $value): ?array
    {
        return $value === null ? null : self::list($value);
    }

    /** A string, or null. */
    public static function stringOrNull(mixed $value): ?string
    {
        return $value === null ? null : self::string($value);
    }

    /** An integer, or null. */
    public static function intOrNull(mixed $value): ?int
    {
        return $value === null ? null : self::int($value);
    }

    /** A number, or null. */
    public static function floatOrNull(mixed $value): ?float
    {
        return $value === null ? null : self::float($value);
    }

    /** A boolean, or null. */
    public static function boolOrNull(mixed $value): ?bool
    {
        return $value === null ? null : self::bool($value);
    }

    /**
     * @return list<string>|null
     */
    public static function languagesOrNull(mixed $value): ?array
    {
        return $value === null ? null : self::languages($value);
    }

    /** Says what the schema promised and what arrived instead. */
    private static function fail(string $wanted, mixed $value): never
    {
        $got = get_debug_type($value);
        if (is_scalar($value)) {
            $got .= ' (' . var_export($value, true) . ')';
        }

        throw new UnexpectedValueException(sprintf('expected %s, got %s', $wanted, $got));
    }
}
`;

files['Generated/Operation.php'] = `${HEADER('One row of the operation table.')}
namespace ${GENERATED_NAMESPACE};

/**
 * One operation of the Kaal Jyoti API, as \`openapi/openapi.json\` describes it.
 */
final readonly class Operation
{
    /**
     * @param string $id The \`operationId\` from the snapshot, e.g. \`postKundliDasha\`.
     * @param string $method The HTTP verb, upper case.
     * @param string $path The path, with its \`{list}\` placeholders intact.
     * @param string $tag The tag the operation is grouped under, which is the client namespace.
     * @param string|null $requestType The request class, or null when the operation takes no JSON body.
     * @param string|null $documentType The \`data\` class, or null when the answer has no named shape.
     */
    public function __construct(
        public string $id,
        public string $method,
        public string $path,
        public string $tag,
        public ?string $requestType = null,
        public ?string $documentType = null,
    ) {
    }

    public function __toString(): string
    {
        return $this->method . ' ' . $this->path . ' (' . $this->id . ')';
    }
}
`;

const operationRows = operations
  .map((op) =>
    [
      '            new Operation(',
      `                id: ${quote(op.id)},`,
      `                method: ${quote(op.method)},`,
      `                path: ${quote(op.path)},`,
      `                tag: ${quote(op.tag)},`,
      ...(op.requestType ? [`                requestType: ${quote(op.requestType)},`] : []),
      ...(op.documentType ? [`                documentType: ${quote(op.documentType)},`] : []),
      '            ),',
    ].join('\n'),
  )
  .join('\n');

files['Generated/Operations.php'] = `${HEADER(
  'The operation table: what the client calls and what the contract test walks.',
)}
namespace ${GENERATED_NAMESPACE};

use InvalidArgumentException;

/**
 * Every operation in the snapshot, in the order the document lists them.
 */
final class Operations
{
    /** @var list<Operation>|null */
    private static ?array $all = null;

    /**
     * The whole table, built once.
     *
     * @return list<Operation>
     */
    public static function all(): array
    {
        return self::$all ??= [
${operationRows}
        ];
    }

    /**
     * The operation with this \`operationId\`.
     *
     * @throws InvalidArgumentException when the snapshot has no such operation.
     */
    public static function byId(string $id): Operation
    {
        foreach (self::all() as $operation) {
            if ($operation->id === $id) {
                return $operation;
            }
        }

        throw new InvalidArgumentException(sprintf('no operation %s in the snapshot', $id));
    }
}
`;

files['Generated/Version.php'] = `${HEADER(
  'The two versions the client reports and the contract test pins.',
)}
namespace ${GENERATED_NAMESPACE};

/**
 * What this package is, and what it was generated from.
 */
final class Version
{
    /**
     * The version of this package, from \`package.json\`.
     *
     * Sent as the \`sdk-php/<version>\` half of the \`X-KJ-Client\` header.
     */
    public const SDK = ${quote(sdkVersion)};

    /** The \`info.version\` of the OpenAPI snapshot these models were built from. */
    public const OPENAPI = ${quote(doc.info.version)};
}
`;

// ---------------------------------------------------------------------------
// Write, or compare
// ---------------------------------------------------------------------------

async function existing() {
  const found = [];
  for (const dir of OUT_DIRS) {
    const names = await readdir(join(srcDir, dir)).catch(() => []);
    for (const name of names) found.push(`${dir}/${name}`);
  }
  return found;
}

const check = process.argv.includes('--check');

if (check) {
  const differ = [];
  for (const [name, source] of Object.entries(files)) {
    const current = await readFile(join(srcDir, name), 'utf8').catch(() => null);
    if (current === null) differ.push(`${name} (missing)`);
    else if (current !== source) differ.push(name);
  }
  for (const name of await existing()) {
    if (!(name in files)) differ.push(`${name} (not generated any more)`);
  }

  if (differ.length > 0) {
    console.error(
      'src/Generated and src/Models are out of date with openapi/openapi.json:\n' +
        differ.map((name) => `  - ${name}`).join('\n') +
        '\nRun: pnpm --filter sdk-php run gen',
    );
    process.exit(1);
  }
  console.log(`src/Generated and src/Models are current (${Object.keys(files).length} files).`);
} else {
  // The two directories are generated outright, so a class the snapshot has
  // dropped leaves with it rather than lingering as an orphan file.
  for (const name of await existing()) {
    if (!(name in files)) await rm(join(srcDir, name));
  }
  for (const dir of OUT_DIRS) await mkdir(join(srcDir, dir), { recursive: true });
  for (const [name, source] of Object.entries(files)) {
    await writeFile(join(srcDir, name), source);
  }
  console.log(
    `Wrote ${Object.keys(files).length} files, ${classes.size + 1} classes, ` +
      `${operations.length} operations from openapi ${doc.info.version}.`,
  );
  if (fallbacks.length > 0) {
    console.log('Constructs with no exact PHP shape:');
    for (const line of [...new Set(fallbacks)]) console.log(`  - ${line}`);
  }
}
