<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocument.areas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VarshphalReadingDocument.areas[]`.
 */
final readonly class AreaSummary
{
    /**
     * @param list<AreaSummaryRulesItem> $rules
     * @param LocalizedText $text One piece of text, keyed by language: one entry for each language in
     *     `options.language`, in that order (`{"hi": "…"}` or `{"en": "…", "hi": "…"}`).
     */
    public function __construct(
        public string $area,
        public string $level,
        public array $rules,
        public LocalizedText $text,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            area: Json::string($data['area'] ?? null),
            level: Json::string($data['level'] ?? null),
            rules: array_map(
                static fn (mixed $v): AreaSummaryRulesItem => AreaSummaryRulesItem::fromArray(Json::object($v)),
                Json::list($data['rules'] ?? null),
            ),
            text: LocalizedText::fromArray(Json::object($data['text'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['area'] = $this->area;
        $out['level'] = $this->level;
        $out['rules'] = array_map(static fn (AreaSummaryRulesItem $v): array => $v->toArray(), $this->rules);
        $out['text'] = $this->text->toArray();

        return $out;
    }
}
