<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `AreaSummary.rules[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `AreaSummary.rules[]`.
 */
final readonly class AreaSummaryRulesItem
{
    public function __construct(
        public string $id,
        public ?bool $good = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: Json::string($data['id'] ?? null),
            good: Json::boolOrNull($data['good'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['id'] = $this->id;
        if ($this->good !== null) {
            $out['good'] = $this->good;
        }

        return $out;
    }
}
