<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/AshtakavargaDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `ashtakavarga` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/AshtakavargaDocument`.
 */
final readonly class AshtakavargaDocument
{
    /**
     * @param array<string, list<int>> $bav
     * @param list<int> $sav
     */
    public function __construct(
        public array $bav,
        public array $sav,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $bav = [];
        foreach (Json::object($data['bav'] ?? null) as $key => $value) {
            $bav[$key] = array_map(static fn (mixed $item): int => Json::int($item), Json::list($value));
        }

        return new self(
            bav: $bav,
            sav: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['sav'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['bav'] = $this->bav;
        $out['sav'] = $this->sav;

        return $out;
    }
}
