<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/BatchMeta` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Like `Meta`, without a single `timezone`.
 *
 * Wire shape: `#/components/schemas/BatchMeta`.
 */
final readonly class BatchMeta
{
    /**
     * @param bool $cached The answer came from the cache.
     * @param string $engine Engine version the answer was computed with.
     * @param list<string> $languageFallback Languages that were asked for but have no labels.
     * @param int $credits Credits this request cost: one pair's price for each pair.
     */
    public function __construct(
        public bool $cached,
        public MetaAyanamsa $ayanamsa,
        public string $engine,
        public int $computeMs,
        public array $languageFallback,
        public int $credits,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            cached: Json::bool($data['cached'] ?? null),
            ayanamsa: MetaAyanamsa::fromArray(Json::object($data['ayanamsa'] ?? null)),
            engine: Json::string($data['engine'] ?? null),
            computeMs: Json::int($data['compute_ms'] ?? null),
            languageFallback: array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($data['language_fallback'] ?? null),
            ),
            credits: Json::int($data['credits'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['cached'] = $this->cached;
        $out['ayanamsa'] = $this->ayanamsa->toArray();
        $out['engine'] = $this->engine;
        $out['compute_ms'] = $this->computeMs;
        $out['language_fallback'] = $this->languageFallback;
        $out['credits'] = $this->credits;

        return $out;
    }
}
