<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `BatchDocumentResultsItem.error` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Present instead of `data` when this pair could not be answered.
 *
 * Wire shape: `BatchDocumentResultsItem.error`.
 */
final readonly class BatchDocumentResultsItemError
{
    public function __construct(
        public string $code,
        public string $message,
        public ?string $field = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            code: Json::string($data['code'] ?? null),
            message: Json::string($data['message'] ?? null),
            field: Json::stringOrNull($data['field'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['code'] = $this->code;
        $out['message'] = $this->message;
        if ($this->field !== null) {
            $out['field'] = $this->field;
        }

        return $out;
    }
}
