<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/BhavaBalaDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `bhava_bala` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/BhavaBalaDocument`.
 */
final readonly class BhavaBalaDocument
{
    /**
     * @param list<BhavaBalaDocumentHousesItem> $houses
     */
    public function __construct(
        public array $houses,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            houses: array_map(
                static fn (mixed $v): BhavaBalaDocumentHousesItem
                    => BhavaBalaDocumentHousesItem::fromArray(Json::object($v)),
                Json::list($data['houses'] ?? null),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['houses'] = array_map(static fn (BhavaBalaDocumentHousesItem $v): array => $v->toArray(), $this->houses);

        return $out;
    }
}
