<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `ChalitDocument.equal` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `ChalitDocument.equal`.
 */
final readonly class ChalitHouses
{
    /**
     * @param array<string, int> $houseOf
     * @param list<float> $madhya
     * @param list<string> $madhyaDms
     * @param list<int> $madhyaRank
     * @param list<list<LabelledId>> $planetsInHouse
     * @param list<float> $sandhi
     * @param list<string> $sandhiDms
     * @param list<string> $signOfHouse
     */
    public function __construct(
        public array $houseOf,
        public array $madhya,
        public array $madhyaDms,
        public array $madhyaRank,
        public array $planetsInHouse,
        public array $sandhi,
        public array $sandhiDms,
        public array $signOfHouse,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $houseOf = [];
        foreach (Json::object($data['house_of'] ?? null) as $key => $value) {
            $houseOf[$key] = Json::int($value);
        }

        return new self(
            houseOf: $houseOf,
            madhya: array_map(static fn (mixed $v): float => Json::float($v), Json::list($data['madhya'] ?? null)),
            madhyaDms: array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($data['madhya_dms'] ?? null),
            ),
            madhyaRank: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['madhya_rank'] ?? null)),
            planetsInHouse: array_map(
                static fn (mixed $v): array
                    => array_map(static fn (mixed $item): LabelledId => LabelledId::fromArray(Json::object($item)), Json::list($v)),
                Json::list($data['planets_in_house'] ?? null),
            ),
            sandhi: array_map(static fn (mixed $v): float => Json::float($v), Json::list($data['sandhi'] ?? null)),
            sandhiDms: array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($data['sandhi_dms'] ?? null),
            ),
            signOfHouse: array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($data['sign_of_house'] ?? null),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['house_of'] = $this->houseOf;
        $out['madhya'] = $this->madhya;
        $out['madhya_dms'] = $this->madhyaDms;
        $out['madhya_rank'] = $this->madhyaRank;
        $planetsInHouse = [];
        foreach ($this->planetsInHouse as $key => $value) {
            $planetsInHouse[$key] = array_map(static fn (LabelledId $item): array => $item->toArray(), $value);
        }
        $out['planets_in_house'] = $planetsInHouse;
        $out['sandhi'] = $this->sandhi;
        $out['sandhi_dms'] = $this->sandhiDms;
        $out['sign_of_house'] = $this->signOfHouse;

        return $out;
    }
}
