<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * The `style` values the snapshot lists.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

/**
 * The styles `KundliChartRequest::$style` accepts.
 */
final class ChartStyle
{
    public const NORTH = 'north';
    public const SOUTH = 'south';
    public const CIRCULAR = 'circular';

    /**
     * Every value the snapshot lists, in its order.
     *
     * @var list<string>
     */
    public const VALUES = [
        'north',
        'south',
        'circular',
    ];
}
