<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/ChartDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * The document the `chart` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/ChartDocument`.
 */
final readonly class ChartDocument
{
    public function __construct(
        public string $firstHouse,
        public LabelledId $firstHouseSign,
        public int $height,
        public string $lang,
        public bool $showDegrees,
        public int $size,
        public string $style,
        public string $svg,
        public string $title,
        public string $varga,
        public int $width,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            firstHouse: Json::string($data['first_house'] ?? null),
            firstHouseSign: LabelledId::fromArray(Json::object($data['first_house_sign'] ?? null)),
            height: Json::int($data['height'] ?? null),
            lang: Json::string($data['lang'] ?? null),
            showDegrees: Json::bool($data['show_degrees'] ?? null),
            size: Json::int($data['size'] ?? null),
            style: Json::string($data['style'] ?? null),
            svg: Json::string($data['svg'] ?? null),
            title: Json::string($data['title'] ?? null),
            varga: Json::string($data['varga'] ?? null),
            width: Json::int($data['width'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['first_house'] = $this->firstHouse;
        $out['first_house_sign'] = $this->firstHouseSign->toArray();
        $out['height'] = $this->height;
        $out['lang'] = $this->lang;
        $out['show_degrees'] = $this->showDegrees;
        $out['size'] = $this->size;
        $out['style'] = $this->style;
        $out['svg'] = $this->svg;
        $out['title'] = $this->title;
        $out['varga'] = $this->varga;
        $out['width'] = $this->width;

        return $out;
    }
}
