<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `CompareDocumentFindingsItem.params` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `CompareDocumentFindingsItem.params`.
 */
final readonly class CompareDocumentFindingsItemParams
{
    public function __construct(
        public ?string $dignity = null,
        public ?string $house = null,
        public ?string $lord = null,
        public ?string $nakshatra = null,
        public ?string $pada = null,
        public ?string $planet = null,
        public ?string $sign = null,
        public ?string $system = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            dignity: Json::stringOrNull($data['dignity'] ?? null),
            house: Json::stringOrNull($data['house'] ?? null),
            lord: Json::stringOrNull($data['lord'] ?? null),
            nakshatra: Json::stringOrNull($data['nakshatra'] ?? null),
            pada: Json::stringOrNull($data['pada'] ?? null),
            planet: Json::stringOrNull($data['planet'] ?? null),
            sign: Json::stringOrNull($data['sign'] ?? null),
            system: Json::stringOrNull($data['system'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->dignity !== null) {
            $out['dignity'] = $this->dignity;
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }
        if ($this->lord !== null) {
            $out['lord'] = $this->lord;
        }
        if ($this->nakshatra !== null) {
            $out['nakshatra'] = $this->nakshatra;
        }
        if ($this->pada !== null) {
            $out['pada'] = $this->pada;
        }
        if ($this->planet !== null) {
            $out['planet'] = $this->planet;
        }
        if ($this->sign !== null) {
            $out['sign'] = $this->sign;
        }
        if ($this->system !== null) {
            $out['system'] = $this->system;
        }

        return $out;
    }
}
