<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `DailyPanchangDocument.positions{}` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `DailyPanchangDocument.positions{}`.
 */
final readonly class DailyPanchangDocumentPositionsValue
{
    public function __construct(
        public float $latitude,
        public float $longitude,
        public string $longitudeDms,
        public float $speed,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            latitude: Json::float($data['latitude'] ?? null),
            longitude: Json::float($data['longitude'] ?? null),
            longitudeDms: Json::string($data['longitude_dms'] ?? null),
            speed: Json::float($data['speed'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['latitude'] = $this->latitude;
        $out['longitude'] = $this->longitude;
        $out['longitude_dms'] = $this->longitudeDms;
        $out['speed'] = $this->speed;

        return $out;
    }
}
