<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/kundli/dasha body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/kundli/dasha body`.
 */
final readonly class DashaRequest
{
    /**
     * @param Birth $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its zone
     *     (`timezone` or `utc_offset`, not both).
     * @param string $system The dasha system, required (one per call): `vimshottari`, `yogini`, or one of the three
     *     Jaimini dashas, `chara`, `sthira` and `mandook`.
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     * @param int|null $levels Depth of the tree: 1 mahadasha, 2 antardasha (default), 3 pratyantardasha, 4 sookshma, 5
     *     pran. Levels 4 and 5 need a `from`/`to` window. Each level down is only as good as the birth time: a pran
     *     dasha lasts hours.
     * @param string|null $from Start of a window to cut the tree to: a UTC instant, `YYYY-MM-DDTHH:MM:SS` (optionally
     *     `.sss`), `Z` optional, e.g. `2026-01-01T00:00:00Z`. Give both `from` and `to`, or neither; levels 4 and 5
     *     require them. Default: the whole tree.
     * @param string|null $to End of that window: a UTC instant, `YYYY-MM-DDTHH:MM:SS` (optionally `.sss`), `Z`
     *     optional, e.g. `2026-01-01T00:00:00Z`; after `from` and at most 366 days later.
     */
    public function __construct(
        public Birth $birth,
        public string $system,
        public ?CalculationOptions $options = null,
        public ?int $levels = null,
        public ?string $from = null,
        public ?string $to = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;

        return new self(
            birth: Birth::fromArray(Json::object($data['birth'] ?? null)),
            system: Json::string($data['system'] ?? null),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
            levels: Json::intOrNull($data['levels'] ?? null),
            from: Json::stringOrNull($data['from'] ?? null),
            to: Json::stringOrNull($data['to'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['birth'] = $this->birth->toArray();
        $out['system'] = $this->system;
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }
        if ($this->levels !== null) {
            $out['levels'] = $this->levels;
        }
        if ($this->from !== null) {
            $out['from'] = $this->from;
        }
        if ($this->to !== null) {
            $out['to'] = $this->to;
        }

        return $out;
    }
}
