<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `DashaDocument.sthira_bala` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `DashaDocument.sthira_bala`.
 */
final readonly class DashaDocumentSthiraBala
{
    /**
     * @param array<string, int> $amsaBala
     * @param array<string, int> $charaBala
     * @param array<string, int> $drishtiBala
     * @param array<string, int> $grahaBala
     * @param array<string, string> $karakas
     * @param array<string, int> $kendradiBala
     * @param array<string, int> $lordBala
     * @param array<string, int> $mulatrikonadiBala
     * @param array<string, int> $rashiBala
     * @param array<string, int> $sthiraBala
     */
    public function __construct(
        public array $amsaBala,
        public LabelledId $brahma,
        public array $charaBala,
        public array $drishtiBala,
        public array $grahaBala,
        public array $karakas,
        public array $kendradiBala,
        public array $lordBala,
        public LabelledId $maheshwara,
        public array $mulatrikonadiBala,
        public array $rashiBala,
        public LabelledId $rudra,
        public array $sthiraBala,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $amsaBala = [];
        foreach (Json::object($data['amsa_bala'] ?? null) as $key => $value) {
            $amsaBala[$key] = Json::int($value);
        }
        $charaBala = [];
        foreach (Json::object($data['chara_bala'] ?? null) as $key => $value) {
            $charaBala[$key] = Json::int($value);
        }
        $drishtiBala = [];
        foreach (Json::object($data['drishti_bala'] ?? null) as $key => $value) {
            $drishtiBala[$key] = Json::int($value);
        }
        $grahaBala = [];
        foreach (Json::object($data['graha_bala'] ?? null) as $key => $value) {
            $grahaBala[$key] = Json::int($value);
        }
        $karakas = [];
        foreach (Json::object($data['karakas'] ?? null) as $key => $value) {
            $karakas[$key] = Json::string($value);
        }
        $kendradiBala = [];
        foreach (Json::object($data['kendradi_bala'] ?? null) as $key => $value) {
            $kendradiBala[$key] = Json::int($value);
        }
        $lordBala = [];
        foreach (Json::object($data['lord_bala'] ?? null) as $key => $value) {
            $lordBala[$key] = Json::int($value);
        }
        $mulatrikonadiBala = [];
        foreach (Json::object($data['mulatrikonadi_bala'] ?? null) as $key => $value) {
            $mulatrikonadiBala[$key] = Json::int($value);
        }
        $rashiBala = [];
        foreach (Json::object($data['rashi_bala'] ?? null) as $key => $value) {
            $rashiBala[$key] = Json::int($value);
        }
        $sthiraBala = [];
        foreach (Json::object($data['sthira_bala'] ?? null) as $key => $value) {
            $sthiraBala[$key] = Json::int($value);
        }

        return new self(
            amsaBala: $amsaBala,
            brahma: LabelledId::fromArray(Json::object($data['brahma'] ?? null)),
            charaBala: $charaBala,
            drishtiBala: $drishtiBala,
            grahaBala: $grahaBala,
            karakas: $karakas,
            kendradiBala: $kendradiBala,
            lordBala: $lordBala,
            maheshwara: LabelledId::fromArray(Json::object($data['maheshwara'] ?? null)),
            mulatrikonadiBala: $mulatrikonadiBala,
            rashiBala: $rashiBala,
            rudra: LabelledId::fromArray(Json::object($data['rudra'] ?? null)),
            sthiraBala: $sthiraBala,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['amsa_bala'] = $this->amsaBala;
        $out['brahma'] = $this->brahma->toArray();
        $out['chara_bala'] = $this->charaBala;
        $out['drishti_bala'] = $this->drishtiBala;
        $out['graha_bala'] = $this->grahaBala;
        $out['karakas'] = $this->karakas;
        $out['kendradi_bala'] = $this->kendradiBala;
        $out['lord_bala'] = $this->lordBala;
        $out['maheshwara'] = $this->maheshwara->toArray();
        $out['mulatrikonadi_bala'] = $this->mulatrikonadiBala;
        $out['rashi_bala'] = $this->rashiBala;
        $out['rudra'] = $this->rudra->toArray();
        $out['sthira_bala'] = $this->sthiraBala;

        return $out;
    }
}
