<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `DashaDocumentSystems.chara` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `DashaDocumentSystems.chara`.
 */
final readonly class DashaDocumentSystemsChara
{
    /**
     * @param list<DashaDocumentSystemsCharaChainItem> $chain
     * @param list<DashaDocumentSystemsCharaPeriodsItem> $periods
     */
    public function __construct(
        public array $chain,
        public array $periods,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            chain: array_map(
                static fn (mixed $v): DashaDocumentSystemsCharaChainItem
                    => DashaDocumentSystemsCharaChainItem::fromArray(Json::object($v)),
                Json::list($data['chain'] ?? null),
            ),
            periods: array_map(
                static fn (mixed $v): DashaDocumentSystemsCharaPeriodsItem
                    => DashaDocumentSystemsCharaPeriodsItem::fromArray(Json::object($v)),
                Json::list($data['periods'] ?? null),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['chain'] = array_map(
            static fn (DashaDocumentSystemsCharaChainItem $v): array => $v->toArray(),
            $this->chain,
        );
        $out['periods'] = array_map(
            static fn (DashaDocumentSystemsCharaPeriodsItem $v): array => $v->toArray(),
            $this->periods,
        );

        return $out;
    }
}
