<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `DashaDocumentSystemsCharaPeriodsItem.children[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `DashaDocumentSystemsCharaPeriodsItem.children[]`.
 */
final readonly class DashaDocumentSystemsCharaPeriodsItemChildrenItem
{
    /**
     * @param list<DashaCharaPratyantardasha> $children
     */
    public function __construct(
        public array $children,
        public string $end,
        public int $level,
        public string $lordLabel,
        public string $start,
        public mixed $planet = null,
        public ?LabelledId $sign = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $signRaw = $data['sign'] ?? null;

        return new self(
            children: array_map(
                static fn (mixed $v): DashaCharaPratyantardasha
                    => DashaCharaPratyantardasha::fromArray(Json::object($v)),
                Json::list($data['children'] ?? null),
            ),
            end: Json::string($data['end'] ?? null),
            level: Json::int($data['level'] ?? null),
            lordLabel: Json::string($data['lord_label'] ?? null),
            start: Json::string($data['start'] ?? null),
            planet: $data['planet'] ?? null,
            sign: $signRaw === null ? null : LabelledId::fromArray(Json::object($signRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['children'] = array_map(static fn (DashaCharaPratyantardasha $v): array => $v->toArray(), $this->children);
        $out['end'] = $this->end;
        $out['level'] = $this->level;
        $out['lord_label'] = $this->lordLabel;
        $out['start'] = $this->start;
        if ($this->planet !== null) {
            $out['planet'] = $this->planet;
        }
        if ($this->sign !== null) {
            $out['sign'] = $this->sign->toArray();
        }

        return $out;
    }
}
