<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `DashaDocument.mandook_context` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `DashaDocument.mandook_context`.
 */
final readonly class DashaDocumentMandookContext
{
    public function __construct(
        public bool $applicable,
        public bool $direct,
        public int $kendraGrahas,
        public LabelledId $startSign,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            applicable: Json::bool($data['applicable'] ?? null),
            direct: Json::bool($data['direct'] ?? null),
            kendraGrahas: Json::int($data['kendra_grahas'] ?? null),
            startSign: LabelledId::fromArray(Json::object($data['start_sign'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['applicable'] = $this->applicable;
        $out['direct'] = $this->direct;
        $out['kendra_grahas'] = $this->kendraGrahas;
        $out['start_sign'] = $this->startSign->toArray();

        return $out;
    }
}
