<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `DashaDocument.systems` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `DashaDocument.systems`.
 */
final readonly class DashaDocumentSystems
{
    public function __construct(
        public ?DashaDocumentSystemsChara $chara = null,
        public ?DashaDocumentSystemsChara $mandook = null,
        public ?DashaDocumentSystemsChara $sthira = null,
        public ?DashaDocumentSystemsVimshottari $vimshottari = null,
        public ?DashaDocumentSystemsVimshottari $yogini = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $charaRaw = $data['chara'] ?? null;
        $mandookRaw = $data['mandook'] ?? null;
        $sthiraRaw = $data['sthira'] ?? null;
        $vimshottariRaw = $data['vimshottari'] ?? null;
        $yoginiRaw = $data['yogini'] ?? null;

        return new self(
            chara: $charaRaw === null ? null : DashaDocumentSystemsChara::fromArray(Json::object($charaRaw)),
            mandook: $mandookRaw === null ? null : DashaDocumentSystemsChara::fromArray(Json::object($mandookRaw)),
            sthira: $sthiraRaw === null ? null : DashaDocumentSystemsChara::fromArray(Json::object($sthiraRaw)),
            vimshottari: $vimshottariRaw === null ? null : DashaDocumentSystemsVimshottari::fromArray(Json::object($vimshottariRaw)),
            yogini: $yoginiRaw === null ? null : DashaDocumentSystemsVimshottari::fromArray(Json::object($yoginiRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->chara !== null) {
            $out['chara'] = $this->chara->toArray();
        }
        if ($this->mandook !== null) {
            $out['mandook'] = $this->mandook->toArray();
        }
        if ($this->sthira !== null) {
            $out['sthira'] = $this->sthira->toArray();
        }
        if ($this->vimshottari !== null) {
            $out['vimshottari'] = $this->vimshottari->toArray();
        }
        if ($this->yogini !== null) {
            $out['yogini'] = $this->yogini->toArray();
        }

        return $out;
    }
}
