<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `CalculationOptions.disclaimer` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `CalculationOptions.disclaimer`.
 */
final readonly class Disclaimer
{
    /**
     * @param string $name Who to consult, as the reader should see it, e.g. `Acharya Amit Verma`; 1 to 80 characters.
     * @param string|null $url Where to find them: an `http` or `https` URL, up to 200 characters, printed in brackets
     *     after the name.
     */
    public function __construct(
        public string $name,
        public ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: Json::string($data['name'] ?? null),
            url: Json::stringOrNull($data['url'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['name'] = $this->name;
        if ($this->url !== null) {
            $out['url'] = $this->url;
        }

        return $out;
    }
}
