<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/EphemerisMonthDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `ephemeris_month` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/EphemerisMonthDocument`.
 */
final readonly class EphemerisMonthDocument
{
    public function __construct(
        public ?EphemerisMonthDocumentNirayan $nirayan = null,
        public ?EphemerisMonthDocumentSayan $sayan = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $nirayanRaw = $data['nirayan'] ?? null;
        $sayanRaw = $data['sayan'] ?? null;

        return new self(
            nirayan: $nirayanRaw === null ? null : EphemerisMonthDocumentNirayan::fromArray(Json::object($nirayanRaw)),
            sayan: $sayanRaw === null ? null : EphemerisMonthDocumentSayan::fromArray(Json::object($sayanRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->nirayan !== null) {
            $out['nirayan'] = $this->nirayan->toArray();
        }
        if ($this->sayan !== null) {
            $out['sayan'] = $this->sayan->toArray();
        }

        return $out;
    }
}
