<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `EphemerisMonthDocument.nirayan` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `EphemerisMonthDocument.nirayan`.
 */
final readonly class EphemerisMonthDocumentNirayan
{
    /**
     * @param list<EphemerisMonthDocumentNirayanDaysItem> $days
     * @param list<EphemerisMonthDocumentNirayanEventsItem> $events
     */
    public function __construct(
        public int $ayanamsaId,
        public array $days,
        public array $events,
        public int $month,
        public string $system,
        public int $year,
        public ?float $ayanamsaOnFirst = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            ayanamsaId: Json::int($data['ayanamsa_id'] ?? null),
            days: array_map(
                static fn (mixed $v): EphemerisMonthDocumentNirayanDaysItem
                    => EphemerisMonthDocumentNirayanDaysItem::fromArray(Json::object($v)),
                Json::list($data['days'] ?? null),
            ),
            events: array_map(
                static fn (mixed $v): EphemerisMonthDocumentNirayanEventsItem
                    => EphemerisMonthDocumentNirayanEventsItem::fromArray(Json::object($v)),
                Json::list($data['events'] ?? null),
            ),
            month: Json::int($data['month'] ?? null),
            system: Json::string($data['system'] ?? null),
            year: Json::int($data['year'] ?? null),
            ayanamsaOnFirst: Json::floatOrNull($data['ayanamsa_on_first'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['ayanamsa_id'] = $this->ayanamsaId;
        $out['days'] = array_map(
            static fn (EphemerisMonthDocumentNirayanDaysItem $v): array => $v->toArray(),
            $this->days,
        );
        $out['events'] = array_map(
            static fn (EphemerisMonthDocumentNirayanEventsItem $v): array => $v->toArray(),
            $this->events,
        );
        $out['month'] = $this->month;
        $out['system'] = $this->system;
        $out['year'] = $this->year;
        if ($this->ayanamsaOnFirst !== null) {
            $out['ayanamsa_on_first'] = $this->ayanamsaOnFirst;
        }

        return $out;
    }
}
