<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `EphemerisMonthDocumentNirayan.days[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `EphemerisMonthDocumentNirayan.days[]`.
 */
final readonly class EphemerisMonthDocumentNirayanDaysItem
{
    /**
     * @param array<string, DailyPanchangDocumentPositionsValue> $positions
     */
    public function __construct(
        public float $ascendant,
        public string $ascendantDms,
        public int $day,
        public array $positions,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $positions = [];
        foreach (Json::object($data['positions'] ?? null) as $key => $value) {
            $positions[$key] = DailyPanchangDocumentPositionsValue::fromArray(Json::object($value));
        }

        return new self(
            ascendant: Json::float($data['ascendant'] ?? null),
            ascendantDms: Json::string($data['ascendant_dms'] ?? null),
            day: Json::int($data['day'] ?? null),
            positions: $positions,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['ascendant'] = $this->ascendant;
        $out['ascendant_dms'] = $this->ascendantDms;
        $out['day'] = $this->day;
        $out['positions'] = array_map(
            static fn (DailyPanchangDocumentPositionsValue $v): array => $v->toArray(),
            $this->positions,
        );

        return $out;
    }
}
