<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `EventsDocument.events[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `EventsDocument.events[]`.
 */
final readonly class EventsDocumentEventsItem
{
    public function __construct(
        public EventsDocumentEventsItemDetail $detail,
        public string $source,
        public string $time,
        public ?int $dashaLevel = null,
        public ?LabelledId $planet = null,
        public ?string $transitKind = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $planetRaw = $data['planet'] ?? null;

        return new self(
            detail: EventsDocumentEventsItemDetail::fromArray(Json::object($data['detail'] ?? null)),
            source: Json::string($data['source'] ?? null),
            time: Json::string($data['time'] ?? null),
            dashaLevel: Json::intOrNull($data['dasha_level'] ?? null),
            planet: $planetRaw === null ? null : LabelledId::fromArray(Json::object($planetRaw)),
            transitKind: Json::stringOrNull($data['transit_kind'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['detail'] = $this->detail->toArray();
        $out['source'] = $this->source;
        $out['time'] = $this->time;
        if ($this->dashaLevel !== null) {
            $out['dasha_level'] = $this->dashaLevel;
        }
        if ($this->planet !== null) {
            $out['planet'] = $this->planet->toArray();
        }
        if ($this->transitKind !== null) {
            $out['transit_kind'] = $this->transitKind;
        }

        return $out;
    }
}
