<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/EventsDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * The document the `events` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/EventsDocument`.
 */
final readonly class EventsDocument
{
    /**
     * @param list<EventsDocumentEventsItem> $events
     */
    public function __construct(
        public LabelledId $dashaSystem,
        public array $events,
        public string $from,
        public string $to,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            dashaSystem: LabelledId::fromArray(Json::object($data['dasha_system'] ?? null)),
            events: array_map(
                static fn (mixed $v): EventsDocumentEventsItem => EventsDocumentEventsItem::fromArray(Json::object($v)),
                Json::list($data['events'] ?? null),
            ),
            from: Json::string($data['from'] ?? null),
            to: Json::string($data['to'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['dasha_system'] = $this->dashaSystem->toArray();
        $out['events'] = array_map(static fn (EventsDocumentEventsItem $v): array => $v->toArray(), $this->events);
        $out['from'] = $this->from;
        $out['to'] = $this->to;

        return $out;
    }
}
