<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `EventsDocumentEventsItemDetail.event` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `EventsDocumentEventsItemDetail.event`.
 */
final readonly class EventsDocumentEventsItemDetailEvent
{
    public function __construct(
        public string $kind,
        public string $label,
        public string $time,
        public ?int $drishti = null,
        public ?string $natalPoint = null,
        public ?LabelledId $planet = null,
        public ?LabelledId $sign = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $planetRaw = $data['planet'] ?? null;
        $signRaw = $data['sign'] ?? null;

        return new self(
            kind: Json::string($data['kind'] ?? null),
            label: Json::string($data['label'] ?? null),
            time: Json::string($data['time'] ?? null),
            drishti: Json::intOrNull($data['drishti'] ?? null),
            natalPoint: Json::stringOrNull($data['natal_point'] ?? null),
            planet: $planetRaw === null ? null : LabelledId::fromArray(Json::object($planetRaw)),
            sign: $signRaw === null ? null : LabelledId::fromArray(Json::object($signRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['kind'] = $this->kind;
        $out['label'] = $this->label;
        $out['time'] = $this->time;
        if ($this->drishti !== null) {
            $out['drishti'] = $this->drishti;
        }
        if ($this->natalPoint !== null) {
            $out['natal_point'] = $this->natalPoint;
        }
        if ($this->planet !== null) {
            $out['planet'] = $this->planet->toArray();
        }
        if ($this->sign !== null) {
            $out['sign'] = $this->sign->toArray();
        }

        return $out;
    }
}
