<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `GrahaDrishtiDocument.on_house{}[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `GrahaDrishtiDocument.on_house{}[]`.
 */
final readonly class GrahaDrishtiDocumentOnHouseValueItem
{
    public function __construct(
        public int $distance,
        public LabelledId $from,
        public int $toSignIdx,
        public mixed $to = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            distance: Json::int($data['distance'] ?? null),
            from: LabelledId::fromArray(Json::object($data['from'] ?? null)),
            toSignIdx: Json::int($data['to_sign_idx'] ?? null),
            to: $data['to'] ?? null,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['distance'] = $this->distance;
        $out['from'] = $this->from->toArray();
        $out['to_sign_idx'] = $this->toSignIdx;
        if ($this->to !== null) {
            $out['to'] = $this->to;
        }

        return $out;
    }
}
