<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/GrahaDrishtiDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `graha_drishti` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/GrahaDrishtiDocument`.
 */
final readonly class GrahaDrishtiDocument
{
    /**
     * @param array<string, list<GrahaDrishtiDocumentCastValueItem>> $cast
     * @param array<string, int> $houseOf
     * @param array<string, list<GrahaDrishtiDocumentOnHouseValueItem>> $onHouse
     * @param array<string, list<GrahaDrishtiDocumentCastValueItem>> $received
     */
    public function __construct(
        public array $cast,
        public array $houseOf,
        public int $lagnaIdx,
        public array $onHouse,
        public array $received,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $cast = [];
        foreach (Json::object($data['cast'] ?? null) as $key => $value) {
            $cast[$key] = array_map(
                static fn (mixed $item): GrahaDrishtiDocumentCastValueItem
                    => GrahaDrishtiDocumentCastValueItem::fromArray(Json::object($item)),
                Json::list($value),
            );
        }
        $houseOf = [];
        foreach (Json::object($data['house_of'] ?? null) as $key => $value) {
            $houseOf[$key] = Json::int($value);
        }
        $onHouse = [];
        foreach (Json::object($data['on_house'] ?? null) as $key => $value) {
            $onHouse[$key] = array_map(
                static fn (mixed $item): GrahaDrishtiDocumentOnHouseValueItem
                    => GrahaDrishtiDocumentOnHouseValueItem::fromArray(Json::object($item)),
                Json::list($value),
            );
        }
        $received = [];
        foreach (Json::object($data['received'] ?? null) as $key => $value) {
            $received[$key] = array_map(
                static fn (mixed $item): GrahaDrishtiDocumentCastValueItem
                    => GrahaDrishtiDocumentCastValueItem::fromArray(Json::object($item)),
                Json::list($value),
            );
        }

        return new self(
            cast: $cast,
            houseOf: $houseOf,
            lagnaIdx: Json::int($data['lagna_idx'] ?? null),
            onHouse: $onHouse,
            received: $received,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $cast = [];
        foreach ($this->cast as $key => $value) {
            $cast[$key] = array_map(
                static fn (GrahaDrishtiDocumentCastValueItem $item): array => $item->toArray(),
                $value,
            );
        }
        $out['cast'] = $cast;
        $out['house_of'] = $this->houseOf;
        $out['lagna_idx'] = $this->lagnaIdx;
        $onHouse = [];
        foreach ($this->onHouse as $key => $value) {
            $onHouse[$key] = array_map(
                static fn (GrahaDrishtiDocumentOnHouseValueItem $item): array => $item->toArray(),
                $value,
            );
        }
        $out['on_house'] = $onHouse;
        $received = [];
        foreach ($this->received as $key => $value) {
            $received[$key] = array_map(
                static fn (GrahaDrishtiDocumentCastValueItem $item): array => $item->toArray(),
                $value,
            );
        }
        $out['received'] = $received;

        return $out;
    }
}
