<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `HealthDocument.supported_range` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The dates the API answers for, from its ephemeris data: calendar dates at the place, whole months;
 * `first_year`/`last_year` bound the whole-year fields (a Varshphal `year`). A date outside is a 400.
 *
 * Wire shape: `HealthDocument.supported_range`.
 */
final readonly class HealthDocumentSupportedRange
{
    public function __construct(
        public string $firstDate,
        public string $lastDate,
        public int $firstYear,
        public int $lastYear,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            firstDate: Json::string($data['first_date'] ?? null),
            lastDate: Json::string($data['last_date'] ?? null),
            firstYear: Json::int($data['first_year'] ?? null),
            lastYear: Json::int($data['last_year'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['first_date'] = $this->firstDate;
        $out['last_date'] = $this->lastDate;
        $out['first_year'] = $this->firstYear;
        $out['last_year'] = $this->lastYear;

        return $out;
    }
}
