<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `GET /v1/health data` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `GET /v1/health data`.
 */
final readonly class HealthDocument
{
    /**
     * @param HealthDocumentSupportedRange $supportedRange The dates the API answers for, from its ephemeris data:
     *     calendar dates at the place, whole months; `first_year`/`last_year` bound the whole-year fields (a Varshphal
     *     `year`). A date outside is a 400.
     */
    public function __construct(
        public string $status,
        public string $engine,
        public string $ephemeris,
        public int $ops,
        public HealthDocumentSupportedRange $supportedRange,
        public int $uptimeS,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            status: Json::string($data['status'] ?? null),
            engine: Json::string($data['engine'] ?? null),
            ephemeris: Json::string($data['ephemeris'] ?? null),
            ops: Json::int($data['ops'] ?? null),
            supportedRange: HealthDocumentSupportedRange::fromArray(Json::object($data['supported_range'] ?? null)),
            uptimeS: Json::int($data['uptime_s'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['status'] = $this->status;
        $out['engine'] = $this->engine;
        $out['ephemeris'] = $this->ephemeris;
        $out['ops'] = $this->ops;
        $out['supported_range'] = $this->supportedRange->toArray();
        $out['uptime_s'] = $this->uptimeS;

        return $out;
    }
}
