<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/horoscope body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/horoscope body`.
 */
final readonly class HoroscopeRequest
{
    /**
     * @param string $sign The reader's Moon sign, e.g. `cancer`, required. Each transit is counted as a house from it.
     * @param string|null $period How long the horoscope reads for: `daily` (the day of `date`, the default), `weekly`
     *     (seven days from `date`), `monthly` (the calendar month of `date`) or `yearly` (its calendar year).
     * @param string|null $date The date the period is taken from, `YYYY-MM-DD`, e.g. `2026-06-01`, in the zone below.
     *     Default: today there (and an answer without `date` is never cached).
     * @param string|null $timezone IANA time zone whose local midnights bound the days, e.g. `America/New_York`.
     *     Default `Asia/Kolkata` when `utc_offset` is absent too. Give this or `utc_offset`, not both.
     * @param string|null $utcOffset Fixed offset whose midnights bound the days instead, `±HH:MM`, e.g. `+05:30`; from
     *     `-14:00` to `+14:00`. Give this or `timezone`, not both.
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     */
    public function __construct(
        public string $sign,
        public ?string $period = null,
        public ?string $date = null,
        public ?string $timezone = null,
        public ?string $utcOffset = null,
        public ?CalculationOptions $options = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;

        return new self(
            sign: Json::string($data['sign'] ?? null),
            period: Json::stringOrNull($data['period'] ?? null),
            date: Json::stringOrNull($data['date'] ?? null),
            timezone: Json::stringOrNull($data['timezone'] ?? null),
            utcOffset: Json::stringOrNull($data['utc_offset'] ?? null),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['sign'] = $this->sign;
        if ($this->period !== null) {
            $out['period'] = $this->period;
        }
        if ($this->date !== null) {
            $out['date'] = $this->date;
        }
        if ($this->timezone !== null) {
            $out['timezone'] = $this->timezone;
        }
        if ($this->utcOffset !== null) {
            $out['utc_offset'] = $this->utcOffset;
        }
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }

        return $out;
    }
}
