<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/HoroscopeDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * The document the `horoscope` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/HoroscopeDocument`.
 */
final readonly class HoroscopeDocument
{
    /**
     * @param list<AreaSummary> $areas
     * @param list<HoroscopeTransit> $basis
     * @param LocalizedText|null $disclaimer The closing line: "these predictions are indicative…", naming the
     *     astrologer in `options.disclaimer` when one is given. Absent when `options.disclaimer` is `"off"`.
     */
    public function __construct(
        public array $areas,
        public array $basis,
        public string $from,
        public string $period,
        public LabelledId $sign,
        public ReadingSummary $summary,
        public string $to,
        public ?LocalizedText $disclaimer = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $disclaimerRaw = $data['disclaimer'] ?? null;

        return new self(
            areas: array_map(
                static fn (mixed $v): AreaSummary => AreaSummary::fromArray(Json::object($v)),
                Json::list($data['areas'] ?? null),
            ),
            basis: array_map(
                static fn (mixed $v): HoroscopeTransit => HoroscopeTransit::fromArray(Json::object($v)),
                Json::list($data['basis'] ?? null),
            ),
            from: Json::string($data['from'] ?? null),
            period: Json::string($data['period'] ?? null),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            summary: ReadingSummary::fromArray(Json::object($data['summary'] ?? null)),
            to: Json::string($data['to'] ?? null),
            disclaimer: $disclaimerRaw === null ? null : LocalizedText::fromArray(Json::object($disclaimerRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = array_map(static fn (AreaSummary $v): array => $v->toArray(), $this->areas);
        $out['basis'] = array_map(static fn (HoroscopeTransit $v): array => $v->toArray(), $this->basis);
        $out['from'] = $this->from;
        $out['period'] = $this->period;
        $out['sign'] = $this->sign->toArray();
        $out['summary'] = $this->summary->toArray();
        $out['to'] = $this->to;
        if ($this->disclaimer !== null) {
            $out['disclaimer'] = $this->disclaimer->toArray();
        }

        return $out;
    }
}
