<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `ReadingHouseLordsDocument.house_lords[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `ReadingHouseLordsDocument.house_lords[]`.
 */
final readonly class HouseLord
{
    public function __construct(
        public ReadingEntry $entry,
        public int $house,
        public int $inHouse,
        public LabelledId $lord,
        public LabelledId $sign,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            entry: ReadingEntry::fromArray(Json::object($data['entry'] ?? null)),
            house: Json::int($data['house'] ?? null),
            inHouse: Json::int($data['in_house'] ?? null),
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['entry'] = $this->entry->toArray();
        $out['house'] = $this->house;
        $out['in_house'] = $this->inHouse;
        $out['lord'] = $this->lord->toArray();
        $out['sign'] = $this->sign->toArray();

        return $out;
    }
}
