<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * The `house_system` values the snapshot lists.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

/**
 * The house systems `PdfKundliOptions::$houseSystem` accepts.
 */
final class HouseSystem
{
    public const WHOLE_SIGN = 'whole_sign';
    public const PLACIDUS = 'placidus';
    public const PORPHYRY = 'porphyry';
    public const EQUAL = 'equal';
    public const SRIPATI = 'sripati';
    public const KP = 'kp';

    /**
     * Every value the snapshot lists, in its order.
     *
     * @var list<string>
     */
    public const VALUES = [
        'whole_sign',
        'placidus',
        'porphyry',
        'equal',
        'sripati',
        'kp',
    ];
}
