<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/JaiminiPadasDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `jaimini` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/JaiminiPadasDocument`.
 */
final readonly class JaiminiPadasDocument
{
    /**
     * @param list<JaiminiPadasDocumentPadasItem> $padas
     * @param array<string, list<string>> $padaLabelsBySign
     */
    public function __construct(
        public array $padas,
        public JaiminiPadasDocumentVargaPadas $vargaPadas,
        public array $padaLabelsBySign,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $padaLabelsBySign = [];
        foreach (Json::object($data['pada_labels_by_sign'] ?? null) as $key => $value) {
            $padaLabelsBySign[$key] = array_map(
                static fn (mixed $item): string => Json::string($item),
                Json::list($value),
            );
        }

        return new self(
            padas: array_map(
                static fn (mixed $v): JaiminiPadasDocumentPadasItem
                    => JaiminiPadasDocumentPadasItem::fromArray(Json::object($v)),
                Json::list($data['padas'] ?? null),
            ),
            vargaPadas: JaiminiPadasDocumentVargaPadas::fromArray(Json::object($data['varga_padas'] ?? null)),
            padaLabelsBySign: $padaLabelsBySign,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['padas'] = array_map(static fn (JaiminiPadasDocumentPadasItem $v): array => $v->toArray(), $this->padas);
        $out['varga_padas'] = $this->vargaPadas->toArray();
        $out['pada_labels_by_sign'] = $this->padaLabelsBySign;

        return $out;
    }
}
