<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/JaiminiKarakasDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * The document the `jaimini` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/JaiminiKarakasDocument`.
 */
final readonly class JaiminiKarakasDocument
{
    /**
     * @param array<string, string> $karakas
     */
    public function __construct(
        public array $karakas,
        public LabelledId $atmakaraka,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $karakas = [];
        foreach (Json::object($data['karakas'] ?? null) as $key => $value) {
            $karakas[$key] = Json::string($value);
        }

        return new self(
            karakas: $karakas,
            atmakaraka: LabelledId::fromArray(Json::object($data['atmakaraka'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['karakas'] = $this->karakas;
        $out['atmakaraka'] = $this->atmakaraka->toArray();

        return $out;
    }
}
