<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `JaiminiKarakamshaDocument.karakamsha` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `JaiminiKarakamshaDocument.karakamsha`.
 */
final readonly class JaiminiKarakamshaDocumentKarakamsha
{
    public function __construct(
        public LabelledId $atmakaraka,
        public LabelledId $sign,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            atmakaraka: LabelledId::fromArray(Json::object($data['atmakaraka'] ?? null)),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['atmakaraka'] = $this->atmakaraka->toArray();
        $out['sign'] = $this->sign->toArray();

        return $out;
    }
}
