<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/JaiminiAspectsDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `jaimini` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/JaiminiAspectsDocument`.
 */
final readonly class JaiminiAspectsDocument
{
    /**
     * @param list<JaiminiAspectsDocumentAspectsItem> $aspects
     * @param array<string, list<string>> $rashiDrishti
     */
    public function __construct(
        public array $aspects,
        public array $rashiDrishti,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $rashiDrishti = [];
        foreach (Json::object($data['rashi_drishti'] ?? null) as $key => $value) {
            $rashiDrishti[$key] = array_map(static fn (mixed $item): string => Json::string($item), Json::list($value));
        }

        return new self(
            aspects: array_map(
                static fn (mixed $v): JaiminiAspectsDocumentAspectsItem
                    => JaiminiAspectsDocumentAspectsItem::fromArray(Json::object($v)),
                Json::list($data['aspects'] ?? null),
            ),
            rashiDrishti: $rashiDrishti,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['aspects'] = array_map(
            static fn (JaiminiAspectsDocumentAspectsItem $v): array => $v->toArray(),
            $this->aspects,
        );
        $out['rashi_drishti'] = $this->rashiDrishti;

        return $out;
    }
}
