<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/KotaDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * The document the `kota` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/KotaDocument`.
 */
final readonly class KotaDocument
{
    /**
     * @param array<string, list<string>> $natal
     * @param array<string, list<string>> $transit
     */
    public function __construct(
        public string $at,
        public int $janmaNak28,
        public LabelledId $kotaPala,
        public LabelledId $kotaSwami,
        public array $natal,
        public array $transit,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $natal = [];
        foreach (Json::object($data['natal'] ?? null) as $key => $value) {
            $natal[$key] = array_map(static fn (mixed $item): string => Json::string($item), Json::list($value));
        }
        $transit = [];
        foreach (Json::object($data['transit'] ?? null) as $key => $value) {
            $transit[$key] = array_map(static fn (mixed $item): string => Json::string($item), Json::list($value));
        }

        return new self(
            at: Json::string($data['at'] ?? null),
            janmaNak28: Json::int($data['janma_nak28'] ?? null),
            kotaPala: LabelledId::fromArray(Json::object($data['kota_pala'] ?? null)),
            kotaSwami: LabelledId::fromArray(Json::object($data['kota_swami'] ?? null)),
            natal: $natal,
            transit: $transit,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['at'] = $this->at;
        $out['janma_nak28'] = $this->janmaNak28;
        $out['kota_pala'] = $this->kotaPala->toArray();
        $out['kota_swami'] = $this->kotaSwami->toArray();
        $out['natal'] = $this->natal;
        $out['transit'] = $this->transit;

        return $out;
    }
}
