<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KpDocument.planet_significators[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KpDocument.planet_significators[]`.
 */
final readonly class KpDocumentPlanetSignificatorsItem
{
    /**
     * @param list<int> $all
     * @param list<int> $owns
     * @param list<int> $starLordOwns
     */
    public function __construct(
        public array $all,
        public int $house,
        public array $owns,
        public LabelledId $planet,
        public int $starLordHouse,
        public array $starLordOwns,
        public bool $untenanted,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            all: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['all'] ?? null)),
            house: Json::int($data['house'] ?? null),
            owns: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['owns'] ?? null)),
            planet: LabelledId::fromArray(Json::object($data['planet'] ?? null)),
            starLordHouse: Json::int($data['star_lord_house'] ?? null),
            starLordOwns: array_map(
                static fn (mixed $v): int => Json::int($v),
                Json::list($data['star_lord_owns'] ?? null),
            ),
            untenanted: Json::bool($data['untenanted'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['all'] = $this->all;
        $out['house'] = $this->house;
        $out['owns'] = $this->owns;
        $out['planet'] = $this->planet->toArray();
        $out['star_lord_house'] = $this->starLordHouse;
        $out['star_lord_owns'] = $this->starLordOwns;
        $out['untenanted'] = $this->untenanted;

        return $out;
    }
}
