<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KpDocument.ruling` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KpDocument.ruling`.
 */
final readonly class KpDocumentRuling
{
    /**
     * @param list<LabelledId> $distinct
     */
    public function __construct(
        public LabelledId $dayLord,
        public array $distinct,
        public LabelledId $lagnaSignLord,
        public LabelledId $lagnaStarLord,
        public LabelledId $lagnaSubLord,
        public LabelledId $moonSignLord,
        public LabelledId $moonStarLord,
        public LabelledId $moonSubLord,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            dayLord: LabelledId::fromArray(Json::object($data['day_lord'] ?? null)),
            distinct: array_map(
                static fn (mixed $v): LabelledId => LabelledId::fromArray(Json::object($v)),
                Json::list($data['distinct'] ?? null),
            ),
            lagnaSignLord: LabelledId::fromArray(Json::object($data['lagna_sign_lord'] ?? null)),
            lagnaStarLord: LabelledId::fromArray(Json::object($data['lagna_star_lord'] ?? null)),
            lagnaSubLord: LabelledId::fromArray(Json::object($data['lagna_sub_lord'] ?? null)),
            moonSignLord: LabelledId::fromArray(Json::object($data['moon_sign_lord'] ?? null)),
            moonStarLord: LabelledId::fromArray(Json::object($data['moon_star_lord'] ?? null)),
            moonSubLord: LabelledId::fromArray(Json::object($data['moon_sub_lord'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['day_lord'] = $this->dayLord->toArray();
        $out['distinct'] = array_map(static fn (LabelledId $v): array => $v->toArray(), $this->distinct);
        $out['lagna_sign_lord'] = $this->lagnaSignLord->toArray();
        $out['lagna_star_lord'] = $this->lagnaStarLord->toArray();
        $out['lagna_sub_lord'] = $this->lagnaSubLord->toArray();
        $out['moon_sign_lord'] = $this->moonSignLord->toArray();
        $out['moon_star_lord'] = $this->moonStarLord->toArray();
        $out['moon_sub_lord'] = $this->moonSubLord->toArray();

        return $out;
    }
}
