<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KpDocumentCuspsItem.lords` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KpDocumentCuspsItem.lords`.
 */
final readonly class KpDocumentCuspsItemLords
{
    public function __construct(
        public LabelledId $nakshatra,
        public LabelledId $signLord,
        public LabelledId $starLord,
        public LabelledId $subLord,
        public LabelledId $subSubLord,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            nakshatra: LabelledId::fromArray(Json::object($data['nakshatra'] ?? null)),
            signLord: LabelledId::fromArray(Json::object($data['sign_lord'] ?? null)),
            starLord: LabelledId::fromArray(Json::object($data['star_lord'] ?? null)),
            subLord: LabelledId::fromArray(Json::object($data['sub_lord'] ?? null)),
            subSubLord: LabelledId::fromArray(Json::object($data['sub_sub_lord'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['nakshatra'] = $this->nakshatra->toArray();
        $out['sign_lord'] = $this->signLord->toArray();
        $out['star_lord'] = $this->starLord->toArray();
        $out['sub_lord'] = $this->subLord->toArray();
        $out['sub_sub_lord'] = $this->subSubLord->toArray();

        return $out;
    }
}
