<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KpDocument.cusps[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KpDocument.cusps[]`.
 */
final readonly class KpDocumentCuspsItem
{
    public function __construct(
        public int $house,
        public float $longitude,
        public string $longitudeDms,
        public KpDocumentCuspsItemLords $lords,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            house: Json::int($data['house'] ?? null),
            longitude: Json::float($data['longitude'] ?? null),
            longitudeDms: Json::string($data['longitude_dms'] ?? null),
            lords: KpDocumentCuspsItemLords::fromArray(Json::object($data['lords'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['house'] = $this->house;
        $out['longitude'] = $this->longitude;
        $out['longitude_dms'] = $this->longitudeDms;
        $out['lords'] = $this->lords->toArray();

        return $out;
    }
}
