<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KpDocument.significators[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KpDocument.significators[]`.
 */
final readonly class KpDocumentSignificatorsItem
{
    /**
     * @param list<LabelledId> $inStarOfOccupants
     * @param list<LabelledId> $inStarOfOwner
     * @param list<LabelledId> $occupants
     */
    public function __construct(
        public int $house,
        public array $inStarOfOccupants,
        public array $inStarOfOwner,
        public array $occupants,
        public LabelledId $owner,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            house: Json::int($data['house'] ?? null),
            inStarOfOccupants: array_map(
                static fn (mixed $v): LabelledId => LabelledId::fromArray(Json::object($v)),
                Json::list($data['in_star_of_occupants'] ?? null),
            ),
            inStarOfOwner: array_map(
                static fn (mixed $v): LabelledId => LabelledId::fromArray(Json::object($v)),
                Json::list($data['in_star_of_owner'] ?? null),
            ),
            occupants: array_map(
                static fn (mixed $v): LabelledId => LabelledId::fromArray(Json::object($v)),
                Json::list($data['occupants'] ?? null),
            ),
            owner: LabelledId::fromArray(Json::object($data['owner'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['house'] = $this->house;
        $out['in_star_of_occupants'] = array_map(
            static fn (LabelledId $v): array => $v->toArray(),
            $this->inStarOfOccupants,
        );
        $out['in_star_of_owner'] = array_map(static fn (LabelledId $v): array => $v->toArray(), $this->inStarOfOwner);
        $out['occupants'] = array_map(static fn (LabelledId $v): array => $v->toArray(), $this->occupants);
        $out['owner'] = $this->owner->toArray();

        return $out;
    }
}
