<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportDocumentInDepthItem.grahas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportDocumentInDepthItem.grahas[]`.
 */
final readonly class KundliReportDocumentInDepthItemGrahasItem
{
    public function __construct(
        public LabelledId $sign,
        public ?ReadingEntry $entry = null,
        public ?LabelledId $graha = null,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $entryRaw = $data['entry'] ?? null;
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            entry: $entryRaw === null ? null : ReadingEntry::fromArray(Json::object($entryRaw)),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['sign'] = $this->sign->toArray();
        if ($this->entry !== null) {
            $out['entry'] = $this->entry->toArray();
        }
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
