<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVarshphalBasis.muntha` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportVarshphalBasis.muntha`.
 */
final readonly class KundliReportVarshphalBasisMuntha
{
    /**
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $reasons
     */
    public function __construct(
        public string $class,
        public LabelledId $lord,
        public int $lordHouse,
        public array $reasons,
        public float $score,
        public LabelledId $sign,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            class: Json::string($data['class'] ?? null),
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            lordHouse: Json::int($data['lord_house'] ?? null),
            reasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            score: Json::float($data['score'] ?? null),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['class'] = $this->class;
        $out['lord'] = $this->lord->toArray();
        $out['lord_house'] = $this->lordHouse;
        $out['reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->reasons,
        );
        $out['score'] = $this->score;
        $out['sign'] = $this->sign->toArray();
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
