<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/kundli body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/kundli body`.
 */
final readonly class KundliRequest
{
    /**
     * @param Birth $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its zone
     *     (`timezone` or `utc_offset`, not both).
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     */
    public function __construct(
        public Birth $birth,
        public ?CalculationOptions $options = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;

        return new self(
            birth: Birth::fromArray(Json::object($data['birth'] ?? null)),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['birth'] = $this->birth->toArray();
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }

        return $out;
    }
}
