<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVimshottariBasisFunctionalValue.eighth_lord` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportVimshottariBasisFunctionalValue.eighth_lord`.
 */
final readonly class KundliReportVimshottariBasisFunctionalValueEighthLord
{
    public function __construct(
        public KundliReportVimshottariBasisFunctionalValueEighthLordAlso $also,
        public bool $placedInEighth,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            also: KundliReportVimshottariBasisFunctionalValueEighthLordAlso::fromArray(Json::object($data['also'] ?? null)),
            placedInEighth: Json::bool($data['placed_in_eighth'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['also'] = $this->also->toArray();
        $out['placed_in_eighth'] = $this->placedInEighth;

        return $out;
    }
}
