<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/kundli/chart body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/kundli/chart body`.
 */
final readonly class KundliChartRequest
{
    /**
     * @param Birth $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its zone
     *     (`timezone` or `utc_offset`, not both).
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     * @param string|null $varga The chart to draw: one of the sixteen vargas, from `d1` (the rashi chart, the default)
     *     to `d60`, e.g. `d9` for the navamsa.
     * @param string|null $style How the chart is drawn: `north` (North Indian, houses fixed; the default), `south`
     *     (South Indian, signs fixed) or `circular`.
     * @param int|null $size Width and height of the square SVG, in pixels, from 200 to 2000; default 600. The SVG
     *     scales, so this sets the numbers, not the sharpness.
     * @param array<string, string>|null $theme Colour overrides, as CSS custom properties, e.g. `{"--kj-bg": "#000000",
     *     "--kj-line": "#FFFFFF"}`. Properties: `--kj-bg`, `--kj-line`, `--kj-text`, `--kj-muted`, `--kj-planet`,
     *     `--kj-retro`, `--kj-lagna`, and `--kj-planet-<graha>` for one graha (`--kj-planet-sun` … `--kj-planet-ketu`).
     *     A name is `--` then letters, digits, `-` or `_`; a value is a colour: `#rgb`, `#rgba`, `#rrggbb` or
     *     `#rrggbbaa`, `rgb()`/`rgba()`/`hsl()`/`hsla()` with plain numbers or percentages, or a CSS colour name
     *     (letters only, e.g. `red`). Names and values up to 64 characters; anything else is refused. Default: the
     *     classic palette.
     * @param bool|null $showDegrees Print each graha's degree in its sign. Default `true`. D1 only: any other varga
     *     answers `show_degrees: false`, since a divisional chart has no degrees.
     * @param bool|null $embedFont Embed the Devanagari font subset (about 55 KB) in the SVG instead of importing it
     *     from Google Fonts, for a page that cannot load fonts. Default `false`. Refused for publishable (`kj_pub_…`)
     *     keys.
     * @param string|null $firstHouse What house 1 is drawn from ("rotate from"): `lagna` (default); a graha id, `sun`
     *     to `ketu`, whose sign in this varga becomes house 1 (`moon`: the Chandra kundli); or `house_2` to `house_12`,
     *     the sign of that house from the lagna (bhavat bhavam). The grahas never move, and the ascendant marker stays
     *     in the lagna's sign.
     */
    public function __construct(
        public Birth $birth,
        public ?CalculationOptions $options = null,
        public ?string $varga = null,
        public ?string $style = null,
        public ?int $size = null,
        public ?array $theme = null,
        public ?bool $showDegrees = null,
        public ?bool $embedFont = null,
        public ?string $firstHouse = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;
        $themeRaw = $data['theme'] ?? null;
        $theme = null;
        if ($themeRaw !== null) {
            $theme = [];
            foreach (Json::object($themeRaw) as $key => $value) {
                $theme[$key] = Json::string($value);
            }
        }

        return new self(
            birth: Birth::fromArray(Json::object($data['birth'] ?? null)),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
            varga: Json::stringOrNull($data['varga'] ?? null),
            style: Json::stringOrNull($data['style'] ?? null),
            size: Json::intOrNull($data['size'] ?? null),
            theme: $theme,
            showDegrees: Json::boolOrNull($data['show_degrees'] ?? null),
            embedFont: Json::boolOrNull($data['embed_font'] ?? null),
            firstHouse: Json::stringOrNull($data['first_house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['birth'] = $this->birth->toArray();
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }
        if ($this->varga !== null) {
            $out['varga'] = $this->varga;
        }
        if ($this->style !== null) {
            $out['style'] = $this->style;
        }
        if ($this->size !== null) {
            $out['size'] = $this->size;
        }
        if ($this->theme !== null) {
            $out['theme'] = $this->theme;
        }
        if ($this->showDegrees !== null) {
            $out['show_degrees'] = $this->showDegrees;
        }
        if ($this->embedFont !== null) {
            $out['embed_font'] = $this->embedFont;
        }
        if ($this->firstHouse !== null) {
            $out['first_house'] = $this->firstHouse;
        }

        return $out;
    }
}
