<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVimshottari.periods[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportVimshottari.periods[]`.
 */
final readonly class KundliReportMahadasha
{
    /**
     * @param list<KundliReportMahadashaAntardashasItem> $antardashas
     * @param list<KundliReportMahadashaAreasItem> $areas
     */
    public function __construct(
        public array $antardashas,
        public array $areas,
        public bool $current,
        public string $from,
        public string $level,
        public LabelledId $lord,
        public string $stage,
        public string $to,
        public ?string $tara = null,
        public ?LocalizedText $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $textRaw = $data['text'] ?? null;

        return new self(
            antardashas: array_map(
                static fn (mixed $v): KundliReportMahadashaAntardashasItem
                    => KundliReportMahadashaAntardashasItem::fromArray(Json::object($v)),
                Json::list($data['antardashas'] ?? null),
            ),
            areas: array_map(
                static fn (mixed $v): KundliReportMahadashaAreasItem
                    => KundliReportMahadashaAreasItem::fromArray(Json::object($v)),
                Json::list($data['areas'] ?? null),
            ),
            current: Json::bool($data['current'] ?? null),
            from: Json::string($data['from'] ?? null),
            level: Json::string($data['level'] ?? null),
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            stage: Json::string($data['stage'] ?? null),
            to: Json::string($data['to'] ?? null),
            tara: Json::stringOrNull($data['tara'] ?? null),
            text: $textRaw === null ? null : LocalizedText::fromArray(Json::object($textRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['antardashas'] = array_map(
            static fn (KundliReportMahadashaAntardashasItem $v): array => $v->toArray(),
            $this->antardashas,
        );
        $out['areas'] = array_map(static fn (KundliReportMahadashaAreasItem $v): array => $v->toArray(), $this->areas);
        $out['current'] = $this->current;
        $out['from'] = $this->from;
        $out['level'] = $this->level;
        $out['lord'] = $this->lord->toArray();
        $out['stage'] = $this->stage;
        $out['to'] = $this->to;
        if ($this->tara !== null) {
            $out['tara'] = $this->tara;
        }
        if ($this->text !== null) {
            $out['text'] = $this->text->toArray();
        }

        return $out;
    }
}
