<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportDocument.life_areas` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportDocument.life_areas`.
 */
final readonly class KundliReportLifeAreas
{
    /**
     * @param list<LifeArea> $areas
     */
    public function __construct(
        public array $areas,
        public LifeAreasSummary $summary,
        public KundliReportLifeAreasSwitches $switches,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            areas: array_map(
                static fn (mixed $v): LifeArea => LifeArea::fromArray(Json::object($v)),
                Json::list($data['areas'] ?? null),
            ),
            summary: LifeAreasSummary::fromArray(Json::object($data['summary'] ?? null)),
            switches: KundliReportLifeAreasSwitches::fromArray(Json::object($data['switches'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = array_map(static fn (LifeArea $v): array => $v->toArray(), $this->areas);
        $out['summary'] = $this->summary->toArray();
        $out['switches'] = $this->switches->toArray();

        return $out;
    }
}
