<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportDocument.varshphal` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportDocument.varshphal`.
 */
final readonly class KundliReportVarshphal
{
    /**
     * @param list<AreaSummary> $areas
     * @param list<VarshphalPeriod> $months
     */
    public function __construct(
        public array $areas,
        public KundliReportVarshphalBasis $basis,
        public string $from,
        public array $months,
        public ReadingSummary $summary,
        public string $to,
        public int $varshaYear,
        public int $year,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            areas: array_map(
                static fn (mixed $v): AreaSummary => AreaSummary::fromArray(Json::object($v)),
                Json::list($data['areas'] ?? null),
            ),
            basis: KundliReportVarshphalBasis::fromArray(Json::object($data['basis'] ?? null)),
            from: Json::string($data['from'] ?? null),
            months: array_map(
                static fn (mixed $v): VarshphalPeriod => VarshphalPeriod::fromArray(Json::object($v)),
                Json::list($data['months'] ?? null),
            ),
            summary: ReadingSummary::fromArray(Json::object($data['summary'] ?? null)),
            to: Json::string($data['to'] ?? null),
            varshaYear: Json::int($data['varsha_year'] ?? null),
            year: Json::int($data['year'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = array_map(static fn (AreaSummary $v): array => $v->toArray(), $this->areas);
        $out['basis'] = $this->basis->toArray();
        $out['from'] = $this->from;
        $out['months'] = array_map(static fn (VarshphalPeriod $v): array => $v->toArray(), $this->months);
        $out['summary'] = $this->summary->toArray();
        $out['to'] = $this->to;
        $out['varsha_year'] = $this->varshaYear;
        $out['year'] = $this->year;

        return $out;
    }
}
