<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportDocumentNowNext.transits[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportDocumentNowNext.transits[]`.
 */
final readonly class KundliReportDocumentNowNextTransitsItem
{
    /**
     * @param list<KundliReportDocumentNowNextTransitsItemStaysItem> $stays
     */
    public function __construct(
        public KundliReportDocumentNowNextTransitsItemAreas $areas,
        public LabelledId $from,
        public LabelledId $sign,
        public array $stays,
        public LabelledId $to,
        public ?LabelledId $graha = null,
        public ?int $house = null,
        public ?LocalizedText $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;
        $textRaw = $data['text'] ?? null;

        return new self(
            areas: KundliReportDocumentNowNextTransitsItemAreas::fromArray(Json::object($data['areas'] ?? null)),
            from: LabelledId::fromArray(Json::object($data['from'] ?? null)),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            stays: array_map(
                static fn (mixed $v): KundliReportDocumentNowNextTransitsItemStaysItem
                    => KundliReportDocumentNowNextTransitsItemStaysItem::fromArray(Json::object($v)),
                Json::list($data['stays'] ?? null),
            ),
            to: LabelledId::fromArray(Json::object($data['to'] ?? null)),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
            house: Json::intOrNull($data['house'] ?? null),
            text: $textRaw === null ? null : LocalizedText::fromArray(Json::object($textRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = $this->areas->toArray();
        $out['from'] = $this->from->toArray();
        $out['sign'] = $this->sign->toArray();
        $out['stays'] = array_map(
            static fn (KundliReportDocumentNowNextTransitsItemStaysItem $v): array => $v->toArray(),
            $this->stays,
        );
        $out['to'] = $this->to->toArray();
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }
        if ($this->text !== null) {
            $out['text'] = $this->text->toArray();
        }

        return $out;
    }
}
