<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVimshottariBasisFunctionalValueEighthLord.also` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportVimshottariBasisFunctionalValueEighthLord.also`.
 */
final readonly class KundliReportVimshottariBasisFunctionalValueEighthLordAlso
{
    public function __construct(
        public string $kind,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            kind: Json::string($data['kind'] ?? null),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['kind'] = $this->kind;
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
