<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVimshottariBasis.functional{}` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportVimshottariBasis.functional{}`.
 */
final readonly class KundliReportVimshottariBasisFunctionalValue
{
    /**
     * @param list<KundliReportVimshottariBasisFunctionalValueBlemishesItem> $blemishes
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $dashaRoleReasons
     * @param list<int> $housesOwned
     * @param list<int> $kendraLord
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $reasons
     * @param list<int> $trikonaLord
     */
    public function __construct(
        public array $blemishes,
        public string $class,
        public string $dashaRole,
        public array $dashaRoleReasons,
        public int $houseOccupied,
        public array $housesOwned,
        public array $kendraLord,
        public string $natural,
        public string $net,
        public LabelledId $planet,
        public array $reasons,
        public array $trikonaLord,
        public ?KundliReportVimshottariBasisFunctionalValueEighthLord $eighthLord = null,
        public ?KundliReportVimshottariBasisFunctionalValueKendradhipatiDosha $kendradhipatiDosha = null,
        public ?KundliReportVimshottariBasisFunctionalValueMaraka $maraka = null,
        public ?KundliReportVimshottariBasisFunctionalValueNodeProxy $nodeProxy = null,
        public ?string $rajaYogaPartner = null,
        public ?KundliReportVimshottariBasisFunctionalValueSecondTwelfth $secondTwelfth = null,
        public ?VimshottariReadingDocumentBasisFunctionalValueTrishadayaLord $trishadayaLord = null,
        public ?VimshottariReadingDocumentBasisFunctionalValueYogakaraka $yogakaraka = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $eighthLordRaw = $data['eighth_lord'] ?? null;
        $kendradhipatiDoshaRaw = $data['kendradhipati_dosha'] ?? null;
        $marakaRaw = $data['maraka'] ?? null;
        $nodeProxyRaw = $data['node_proxy'] ?? null;
        $secondTwelfthRaw = $data['second_twelfth'] ?? null;
        $trishadayaLordRaw = $data['trishadaya_lord'] ?? null;
        $yogakarakaRaw = $data['yogakaraka'] ?? null;

        return new self(
            blemishes: array_map(
                static fn (mixed $v): KundliReportVimshottariBasisFunctionalValueBlemishesItem
                    => KundliReportVimshottariBasisFunctionalValueBlemishesItem::fromArray(Json::object($v)),
                Json::list($data['blemishes'] ?? null),
            ),
            class: Json::string($data['class'] ?? null),
            dashaRole: Json::string($data['dasha_role'] ?? null),
            dashaRoleReasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['dasha_role_reasons'] ?? null),
            ),
            houseOccupied: Json::int($data['house_occupied'] ?? null),
            housesOwned: array_map(
                static fn (mixed $v): int => Json::int($v),
                Json::list($data['houses_owned'] ?? null),
            ),
            kendraLord: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['kendra_lord'] ?? null)),
            natural: Json::string($data['natural'] ?? null),
            net: Json::string($data['net'] ?? null),
            planet: LabelledId::fromArray(Json::object($data['planet'] ?? null)),
            reasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            trikonaLord: array_map(
                static fn (mixed $v): int => Json::int($v),
                Json::list($data['trikona_lord'] ?? null),
            ),
            eighthLord: $eighthLordRaw === null ? null : KundliReportVimshottariBasisFunctionalValueEighthLord::fromArray(Json::object($eighthLordRaw)),
            kendradhipatiDosha: $kendradhipatiDoshaRaw === null ? null : KundliReportVimshottariBasisFunctionalValueKendradhipatiDosha::fromArray(Json::object($kendradhipatiDoshaRaw)),
            maraka: $marakaRaw === null ? null : KundliReportVimshottariBasisFunctionalValueMaraka::fromArray(Json::object($marakaRaw)),
            nodeProxy: $nodeProxyRaw === null ? null : KundliReportVimshottariBasisFunctionalValueNodeProxy::fromArray(Json::object($nodeProxyRaw)),
            rajaYogaPartner: Json::stringOrNull($data['raja_yoga_partner'] ?? null),
            secondTwelfth: $secondTwelfthRaw === null ? null : KundliReportVimshottariBasisFunctionalValueSecondTwelfth::fromArray(Json::object($secondTwelfthRaw)),
            trishadayaLord: $trishadayaLordRaw === null ? null : VimshottariReadingDocumentBasisFunctionalValueTrishadayaLord::fromArray(Json::object($trishadayaLordRaw)),
            yogakaraka: $yogakarakaRaw === null ? null : VimshottariReadingDocumentBasisFunctionalValueYogakaraka::fromArray(Json::object($yogakarakaRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['blemishes'] = array_map(
            static fn (KundliReportVimshottariBasisFunctionalValueBlemishesItem $v): array => $v->toArray(),
            $this->blemishes,
        );
        $out['class'] = $this->class;
        $out['dasha_role'] = $this->dashaRole;
        $out['dasha_role_reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->dashaRoleReasons,
        );
        $out['house_occupied'] = $this->houseOccupied;
        $out['houses_owned'] = $this->housesOwned;
        $out['kendra_lord'] = $this->kendraLord;
        $out['natural'] = $this->natural;
        $out['net'] = $this->net;
        $out['planet'] = $this->planet->toArray();
        $out['reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->reasons,
        );
        $out['trikona_lord'] = $this->trikonaLord;
        if ($this->eighthLord !== null) {
            $out['eighth_lord'] = $this->eighthLord->toArray();
        }
        if ($this->kendradhipatiDosha !== null) {
            $out['kendradhipati_dosha'] = $this->kendradhipatiDosha->toArray();
        }
        if ($this->maraka !== null) {
            $out['maraka'] = $this->maraka->toArray();
        }
        if ($this->nodeProxy !== null) {
            $out['node_proxy'] = $this->nodeProxy->toArray();
        }
        if ($this->rajaYogaPartner !== null) {
            $out['raja_yoga_partner'] = $this->rajaYogaPartner;
        }
        if ($this->secondTwelfth !== null) {
            $out['second_twelfth'] = $this->secondTwelfth->toArray();
        }
        if ($this->trishadayaLord !== null) {
            $out['trishadaya_lord'] = $this->trishadayaLord->toArray();
        }
        if ($this->yogakaraka !== null) {
            $out['yogakaraka'] = $this->yogakaraka->toArray();
        }

        return $out;
    }
}
