<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliDocument.positions{}` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliDocument.positions{}`.
 */
final readonly class KundliDocumentPositionsValue
{
    public function __construct(
        public float $degreesInSign,
        public string $degreesInSignDms,
        public bool $isRetrograde,
        public float $latitude,
        public float $longitude,
        public string $longitudeDms,
        public LabelledId $nakshatra,
        public int $pada,
        public LabelledId $planet,
        public LabelledId $sign,
        public float $speed,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            degreesInSign: Json::float($data['degrees_in_sign'] ?? null),
            degreesInSignDms: Json::string($data['degrees_in_sign_dms'] ?? null),
            isRetrograde: Json::bool($data['is_retrograde'] ?? null),
            latitude: Json::float($data['latitude'] ?? null),
            longitude: Json::float($data['longitude'] ?? null),
            longitudeDms: Json::string($data['longitude_dms'] ?? null),
            nakshatra: LabelledId::fromArray(Json::object($data['nakshatra'] ?? null)),
            pada: Json::int($data['pada'] ?? null),
            planet: LabelledId::fromArray(Json::object($data['planet'] ?? null)),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            speed: Json::float($data['speed'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['degrees_in_sign'] = $this->degreesInSign;
        $out['degrees_in_sign_dms'] = $this->degreesInSignDms;
        $out['is_retrograde'] = $this->isRetrograde;
        $out['latitude'] = $this->latitude;
        $out['longitude'] = $this->longitude;
        $out['longitude_dms'] = $this->longitudeDms;
        $out['nakshatra'] = $this->nakshatra->toArray();
        $out['pada'] = $this->pada;
        $out['planet'] = $this->planet->toArray();
        $out['sign'] = $this->sign->toArray();
        $out['speed'] = $this->speed;

        return $out;
    }
}
