<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVimshottariBasisFunctionalValue.node_proxy` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportVimshottariBasisFunctionalValue.node_proxy`.
 */
final readonly class KundliReportVimshottariBasisFunctionalValueNodeProxy
{
    /**
     * @param list<string> $companions
     */
    public function __construct(
        public array $companions,
        public string $follows,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            companions: array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($data['companions'] ?? null),
            ),
            follows: Json::string($data['follows'] ?? null),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['companions'] = $this->companions;
        $out['follows'] = $this->follows;
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
