<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVimshottari.basis` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportVimshottari.basis`.
 */
final readonly class KundliReportVimshottariBasis
{
    /**
     * @param array<string, KundliReportVimshottariBasisFunctionalValue> $functional
     */
    public function __construct(
        public array $functional,
        public VimshottariReadingDocumentBasisSwitches $switches,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $functional = [];
        foreach (Json::object($data['functional'] ?? null) as $key => $value) {
            $functional[$key] = KundliReportVimshottariBasisFunctionalValue::fromArray(Json::object($value));
        }

        return new self(
            functional: $functional,
            switches: VimshottariReadingDocumentBasisSwitches::fromArray(Json::object($data['switches'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['functional'] = array_map(
            static fn (KundliReportVimshottariBasisFunctionalValue $v): array => $v->toArray(),
            $this->functional,
        );
        $out['switches'] = $this->switches->toArray();

        return $out;
    }
}
