<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVarshphalBasisAreas.education` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportVarshphalBasisAreas.education`.
 */
final readonly class KundliReportVarshphalBasisAreasEducation
{
    /**
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $reasons
     * @param list<KundliReportVarshphalBasisAreasEducationYogasItem> $yogas
     */
    public function __construct(
        public bool $danger,
        public string $factor,
        public LabelledId $karyesha,
        public KundliReportVarshphalBasisAreasEducationNatalGuard $natalGuard,
        public array $reasons,
        public float $score,
        public array $yogas,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            danger: Json::bool($data['danger'] ?? null),
            factor: Json::string($data['factor'] ?? null),
            karyesha: LabelledId::fromArray(Json::object($data['karyesha'] ?? null)),
            natalGuard: KundliReportVarshphalBasisAreasEducationNatalGuard::fromArray(Json::object($data['natal_guard'] ?? null)),
            reasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            score: Json::float($data['score'] ?? null),
            yogas: array_map(
                static fn (mixed $v): KundliReportVarshphalBasisAreasEducationYogasItem
                    => KundliReportVarshphalBasisAreasEducationYogasItem::fromArray(Json::object($v)),
                Json::list($data['yogas'] ?? null),
            ),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['danger'] = $this->danger;
        $out['factor'] = $this->factor;
        $out['karyesha'] = $this->karyesha->toArray();
        $out['natal_guard'] = $this->natalGuard->toArray();
        $out['reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->reasons,
        );
        $out['score'] = $this->score;
        $out['yogas'] = array_map(
            static fn (KundliReportVarshphalBasisAreasEducationYogasItem $v): array => $v->toArray(),
            $this->yogas,
        );
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
