<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVarshphalBasisAreasEducation.natal_guard` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportVarshphalBasisAreasEducation.natal_guard`.
 */
final readonly class KundliReportVarshphalBasisAreasEducationNatalGuard
{
    /**
     * @param list<string> $afflictions
     */
    public function __construct(
        public array $afflictions,
        public bool $capped,
        public LabelledId $lord,
        public bool $on,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            afflictions: array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($data['afflictions'] ?? null),
            ),
            capped: Json::bool($data['capped'] ?? null),
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            on: Json::bool($data['on'] ?? null),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['afflictions'] = $this->afflictions;
        $out['capped'] = $this->capped;
        $out['lord'] = $this->lord->toArray();
        $out['on'] = $this->on;
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
