<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVarshphalBasis.five_lords[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportVarshphalBasis.five_lords[]`.
 */
final readonly class KundliReportVarshphalBasisFiveLordsItem
{
    /**
     * @param list<string> $roles
     */
    public function __construct(
        public array $roles,
        public bool $strong,
        public float $vb,
        public bool $weak,
        public ?LabelledId $graha = null,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            roles: array_map(static fn (mixed $v): string => Json::string($v), Json::list($data['roles'] ?? null)),
            strong: Json::bool($data['strong'] ?? null),
            vb: Json::float($data['vb'] ?? null),
            weak: Json::bool($data['weak'] ?? null),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['roles'] = $this->roles;
        $out['strong'] = $this->strong;
        $out['vb'] = $this->vb;
        $out['weak'] = $this->weak;
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
