<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVarshphalBasis.areas` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportVarshphalBasis.areas`.
 */
final readonly class KundliReportVarshphalBasisAreas
{
    public function __construct(
        public KundliReportVarshphalBasisAreasEducation $education,
        public KundliReportVarshphalBasisAreasEducation $health,
        public KundliReportVarshphalBasisAreasEducation $home,
        public KundliReportVarshphalBasisAreasEducation $money,
        public KundliReportVarshphalBasisAreasEducation $relationships,
        public KundliReportVarshphalBasisAreasEducation $travel,
        public KundliReportVarshphalBasisAreasEducation $work,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            education: KundliReportVarshphalBasisAreasEducation::fromArray(Json::object($data['education'] ?? null)),
            health: KundliReportVarshphalBasisAreasEducation::fromArray(Json::object($data['health'] ?? null)),
            home: KundliReportVarshphalBasisAreasEducation::fromArray(Json::object($data['home'] ?? null)),
            money: KundliReportVarshphalBasisAreasEducation::fromArray(Json::object($data['money'] ?? null)),
            relationships: KundliReportVarshphalBasisAreasEducation::fromArray(Json::object($data['relationships'] ?? null)),
            travel: KundliReportVarshphalBasisAreasEducation::fromArray(Json::object($data['travel'] ?? null)),
            work: KundliReportVarshphalBasisAreasEducation::fromArray(Json::object($data['work'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['education'] = $this->education->toArray();
        $out['health'] = $this->health->toArray();
        $out['home'] = $this->home->toArray();
        $out['money'] = $this->money->toArray();
        $out['relationships'] = $this->relationships->toArray();
        $out['travel'] = $this->travel->toArray();
        $out['work'] = $this->work->toArray();

        return $out;
    }
}
