<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportDocument.grahas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliReportDocument.grahas[]`.
 */
final readonly class KundliReportGraha
{
    public function __construct(
        public ReadingEntry $inHouse,
        public ReadingEntry $inSign,
        public LabelledId $sign,
        public ?LabelledId $graha = null,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            inHouse: ReadingEntry::fromArray(Json::object($data['in_house'] ?? null)),
            inSign: ReadingEntry::fromArray(Json::object($data['in_sign'] ?? null)),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['in_house'] = $this->inHouse->toArray();
        $out['in_sign'] = $this->inSign->toArray();
        $out['sign'] = $this->sign->toArray();
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
