<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportDocument.in_depth[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportDocument.in_depth[]`.
 */
final readonly class KundliReportDocumentInDepthItem
{
    /**
     * @param list<string> $areas
     * @param list<KundliReportDocumentInDepthItemGrahasItem> $grahas
     * @param list<int> $houses
     * @param list<KundliReportHouseLord> $lords
     */
    public function __construct(
        public array $areas,
        public array $grahas,
        public array $houses,
        public array $lords,
        public string $topic,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            areas: array_map(static fn (mixed $v): string => Json::string($v), Json::list($data['areas'] ?? null)),
            grahas: array_map(
                static fn (mixed $v): KundliReportDocumentInDepthItemGrahasItem
                    => KundliReportDocumentInDepthItemGrahasItem::fromArray(Json::object($v)),
                Json::list($data['grahas'] ?? null),
            ),
            houses: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['houses'] ?? null)),
            lords: array_map(
                static fn (mixed $v): KundliReportHouseLord => KundliReportHouseLord::fromArray(Json::object($v)),
                Json::list($data['lords'] ?? null),
            ),
            topic: Json::string($data['topic'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = $this->areas;
        $out['grahas'] = array_map(
            static fn (KundliReportDocumentInDepthItemGrahasItem $v): array => $v->toArray(),
            $this->grahas,
        );
        $out['houses'] = $this->houses;
        $out['lords'] = array_map(static fn (KundliReportHouseLord $v): array => $v->toArray(), $this->lords);
        $out['topic'] = $this->topic;

        return $out;
    }
}
