<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVarshphalBasis.switches` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportVarshphalBasis.switches`.
 */
final readonly class KundliReportVarshphalBasisSwitches
{
    public function __construct(
        public VimshottariReadingDocumentBasisSwitchesFunctional $functional,
        public VarshphalReadingDocumentBasisSwitchesVarsha $varsha,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            functional: VimshottariReadingDocumentBasisSwitchesFunctional::fromArray(Json::object($data['functional'] ?? null)),
            varsha: VarshphalReadingDocumentBasisSwitchesVarsha::fromArray(Json::object($data['varsha'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['functional'] = $this->functional->toArray();
        $out['varsha'] = $this->varsha->toArray();

        return $out;
    }
}
