<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliReportVarshphal.basis` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `KundliReportVarshphal.basis`.
 */
final readonly class KundliReportVarshphalBasis
{
    /**
     * @param list<KundliReportVarshphalBasisFiveLordsItem> $fiveLords
     * @param list<VarshphalReadingDocumentBasisMonthsItem> $months
     */
    public function __construct(
        public KundliReportVarshphalBasisAreas $areas,
        public array $fiveLords,
        public array $months,
        public KundliReportVarshphalBasisMuntha $muntha,
        public VarshphalReadingDocumentBasisOverall $overall,
        public KundliReportVarshphalBasisSwitches $switches,
        public KundliReportVarshphalBasisYearLord $yearLord,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            areas: KundliReportVarshphalBasisAreas::fromArray(Json::object($data['areas'] ?? null)),
            fiveLords: array_map(
                static fn (mixed $v): KundliReportVarshphalBasisFiveLordsItem
                    => KundliReportVarshphalBasisFiveLordsItem::fromArray(Json::object($v)),
                Json::list($data['five_lords'] ?? null),
            ),
            months: array_map(
                static fn (mixed $v): VarshphalReadingDocumentBasisMonthsItem
                    => VarshphalReadingDocumentBasisMonthsItem::fromArray(Json::object($v)),
                Json::list($data['months'] ?? null),
            ),
            muntha: KundliReportVarshphalBasisMuntha::fromArray(Json::object($data['muntha'] ?? null)),
            overall: VarshphalReadingDocumentBasisOverall::fromArray(Json::object($data['overall'] ?? null)),
            switches: KundliReportVarshphalBasisSwitches::fromArray(Json::object($data['switches'] ?? null)),
            yearLord: KundliReportVarshphalBasisYearLord::fromArray(Json::object($data['year_lord'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = $this->areas->toArray();
        $out['five_lords'] = array_map(
            static fn (KundliReportVarshphalBasisFiveLordsItem $v): array => $v->toArray(),
            $this->fiveLords,
        );
        $out['months'] = array_map(
            static fn (VarshphalReadingDocumentBasisMonthsItem $v): array => $v->toArray(),
            $this->months,
        );
        $out['muntha'] = $this->muntha->toArray();
        $out['overall'] = $this->overall->toArray();
        $out['switches'] = $this->switches->toArray();
        $out['year_lord'] = $this->yearLord->toArray();

        return $out;
    }
}
