<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `KundliDocument.panchang` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `KundliDocument.panchang`.
 */
final readonly class KundliDocumentPanchang
{
    public function __construct(
        public int $amantaMonthIndex,
        public bool $isAdhikMaasa,
        public int $karanaIndex,
        public LabelledId $karanaName,
        public LabelledId $nakshatra,
        public int $pada,
        public LabelledId $paksha,
        public int $samvatYear,
        public int $tithiIndex,
        public LabelledId $tithiName,
        public LabelledId $vara,
        public int $varaIndex,
        public int $yogaIndex,
        public LabelledId $yogaName,
        public ?string $nextSunrise = null,
        public ?string $sunrise = null,
        public ?string $sunset = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            amantaMonthIndex: Json::int($data['amanta_month_index'] ?? null),
            isAdhikMaasa: Json::bool($data['is_adhik_maasa'] ?? null),
            karanaIndex: Json::int($data['karana_index'] ?? null),
            karanaName: LabelledId::fromArray(Json::object($data['karana_name'] ?? null)),
            nakshatra: LabelledId::fromArray(Json::object($data['nakshatra'] ?? null)),
            pada: Json::int($data['pada'] ?? null),
            paksha: LabelledId::fromArray(Json::object($data['paksha'] ?? null)),
            samvatYear: Json::int($data['samvat_year'] ?? null),
            tithiIndex: Json::int($data['tithi_index'] ?? null),
            tithiName: LabelledId::fromArray(Json::object($data['tithi_name'] ?? null)),
            vara: LabelledId::fromArray(Json::object($data['vara'] ?? null)),
            varaIndex: Json::int($data['vara_index'] ?? null),
            yogaIndex: Json::int($data['yoga_index'] ?? null),
            yogaName: LabelledId::fromArray(Json::object($data['yoga_name'] ?? null)),
            nextSunrise: Json::stringOrNull($data['next_sunrise'] ?? null),
            sunrise: Json::stringOrNull($data['sunrise'] ?? null),
            sunset: Json::stringOrNull($data['sunset'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['amanta_month_index'] = $this->amantaMonthIndex;
        $out['is_adhik_maasa'] = $this->isAdhikMaasa;
        $out['karana_index'] = $this->karanaIndex;
        $out['karana_name'] = $this->karanaName->toArray();
        $out['nakshatra'] = $this->nakshatra->toArray();
        $out['pada'] = $this->pada;
        $out['paksha'] = $this->paksha->toArray();
        $out['samvat_year'] = $this->samvatYear;
        $out['tithi_index'] = $this->tithiIndex;
        $out['tithi_name'] = $this->tithiName->toArray();
        $out['vara'] = $this->vara->toArray();
        $out['vara_index'] = $this->varaIndex;
        $out['yoga_index'] = $this->yogaIndex;
        $out['yoga_name'] = $this->yogaName->toArray();
        if ($this->nextSunrise !== null) {
            $out['next_sunrise'] = $this->nextSunrise;
        }
        if ($this->sunrise !== null) {
            $out['sunrise'] = $this->sunrise;
        }
        if ($this->sunset !== null) {
            $out['sunset'] = $this->sunset;
        }

        return $out;
    }
}
