<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/LifeAreasDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `life_areas` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/LifeAreasDocument`.
 */
final readonly class LifeAreasDocument
{
    /**
     * @param list<LifeArea> $areas
     * @param LocalizedText|null $disclaimer The closing line: "these predictions are indicative…", naming the
     *     astrologer in `options.disclaimer` when one is given. Absent when `options.disclaimer` is `"off"`.
     */
    public function __construct(
        public array $areas,
        public LifeAreasSummary $summary,
        public LifeAreasDocumentSwitches $switches,
        public ?LocalizedText $disclaimer = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $disclaimerRaw = $data['disclaimer'] ?? null;

        return new self(
            areas: array_map(
                static fn (mixed $v): LifeArea => LifeArea::fromArray(Json::object($v)),
                Json::list($data['areas'] ?? null),
            ),
            summary: LifeAreasSummary::fromArray(Json::object($data['summary'] ?? null)),
            switches: LifeAreasDocumentSwitches::fromArray(Json::object($data['switches'] ?? null)),
            disclaimer: $disclaimerRaw === null ? null : LocalizedText::fromArray(Json::object($disclaimerRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = array_map(static fn (LifeArea $v): array => $v->toArray(), $this->areas);
        $out['summary'] = $this->summary->toArray();
        $out['switches'] = $this->switches->toArray();
        if ($this->disclaimer !== null) {
            $out['disclaimer'] = $this->disclaimer->toArray();
        }

        return $out;
    }
}
