<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreaBasisVarga.checks[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `LifeAreaBasisVarga.checks[]`.
 */
final readonly class LifeAreaBasisVargaChecksItem
{
    public function __construct(
        public string $reason,
        public string $role,
        public LabelledId $sign,
        public string $status,
        public string $varga,
        public ?LabelledId $graha = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            reason: Json::string($data['reason'] ?? null),
            role: Json::string($data['role'] ?? null),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            status: Json::string($data['status'] ?? null),
            varga: Json::string($data['varga'] ?? null),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['reason'] = $this->reason;
        $out['role'] = $this->role;
        $out['sign'] = $this->sign->toArray();
        $out['status'] = $this->status;
        $out['varga'] = $this->varga;
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }

        return $out;
    }
}
