<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreaBasis.reasons[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `LifeAreaBasis.reasons[]`.
 */
final readonly class LifeAreaBasisReasonsItem
{
    public function __construct(
        public string $code,
        public string $group,
        public string $source,
        public float $weight,
        public ?LabelledId $graha = null,
        public ?int $house = null,
        public ?string $yoga = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            code: Json::string($data['code'] ?? null),
            group: Json::string($data['group'] ?? null),
            source: Json::string($data['source'] ?? null),
            weight: Json::float($data['weight'] ?? null),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
            house: Json::intOrNull($data['house'] ?? null),
            yoga: Json::stringOrNull($data['yoga'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['code'] = $this->code;
        $out['group'] = $this->group;
        $out['source'] = $this->source;
        $out['weight'] = $this->weight;
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }
        if ($this->yoga !== null) {
            $out['yoga'] = $this->yoga;
        }

        return $out;
    }
}
