<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreaBasis.aspects[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `LifeAreaBasis.aspects[]`.
 */
final readonly class LifeAreaBasisAspectsItem
{
    public function __construct(
        public int $nature,
        public ?LabelledId $graha = null,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            nature: Json::int($data['nature'] ?? null),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['nature'] = $this->nature;
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
