<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeArea.basis` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `LifeArea.basis`.
 */
final readonly class LifeAreaBasis
{
    /**
     * @param list<LifeAreaBasisAspectsItem> $aspects
     * @param list<string> $factors
     * @param list<int> $houses
     * @param list<LifeAreaBasisKarakasItem> $karakas
     * @param list<LifeAreaBasisAspectsItem> $occupants
     * @param list<LifeAreaBasisLord> $otherLords
     * @param list<LifeAreaBasisReasonsItem> $reasons
     * @param list<string> $yogas
     */
    public function __construct(
        public array $aspects,
        public float $baseline,
        public array $factors,
        public array $houses,
        public array $karakas,
        public LifeAreaBasisLord $lord,
        public array $occupants,
        public array $otherLords,
        public array $reasons,
        public float $relative,
        public float $score,
        public LifeAreaBasisVarga $varga,
        public array $yogas,
        public ?string $pressure = null,
        public ?string $support = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            aspects: array_map(
                static fn (mixed $v): LifeAreaBasisAspectsItem => LifeAreaBasisAspectsItem::fromArray(Json::object($v)),
                Json::list($data['aspects'] ?? null),
            ),
            baseline: Json::float($data['baseline'] ?? null),
            factors: array_map(static fn (mixed $v): string => Json::string($v), Json::list($data['factors'] ?? null)),
            houses: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['houses'] ?? null)),
            karakas: array_map(
                static fn (mixed $v): LifeAreaBasisKarakasItem => LifeAreaBasisKarakasItem::fromArray(Json::object($v)),
                Json::list($data['karakas'] ?? null),
            ),
            lord: LifeAreaBasisLord::fromArray(Json::object($data['lord'] ?? null)),
            occupants: array_map(
                static fn (mixed $v): LifeAreaBasisAspectsItem => LifeAreaBasisAspectsItem::fromArray(Json::object($v)),
                Json::list($data['occupants'] ?? null),
            ),
            otherLords: array_map(
                static fn (mixed $v): LifeAreaBasisLord => LifeAreaBasisLord::fromArray(Json::object($v)),
                Json::list($data['other_lords'] ?? null),
            ),
            reasons: array_map(
                static fn (mixed $v): LifeAreaBasisReasonsItem => LifeAreaBasisReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            relative: Json::float($data['relative'] ?? null),
            score: Json::float($data['score'] ?? null),
            varga: LifeAreaBasisVarga::fromArray(Json::object($data['varga'] ?? null)),
            yogas: array_map(static fn (mixed $v): string => Json::string($v), Json::list($data['yogas'] ?? null)),
            pressure: Json::stringOrNull($data['pressure'] ?? null),
            support: Json::stringOrNull($data['support'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['aspects'] = array_map(static fn (LifeAreaBasisAspectsItem $v): array => $v->toArray(), $this->aspects);
        $out['baseline'] = $this->baseline;
        $out['factors'] = $this->factors;
        $out['houses'] = $this->houses;
        $out['karakas'] = array_map(static fn (LifeAreaBasisKarakasItem $v): array => $v->toArray(), $this->karakas);
        $out['lord'] = $this->lord->toArray();
        $out['occupants'] = array_map(
            static fn (LifeAreaBasisAspectsItem $v): array => $v->toArray(),
            $this->occupants,
        );
        $out['other_lords'] = array_map(static fn (LifeAreaBasisLord $v): array => $v->toArray(), $this->otherLords);
        $out['reasons'] = array_map(static fn (LifeAreaBasisReasonsItem $v): array => $v->toArray(), $this->reasons);
        $out['relative'] = $this->relative;
        $out['score'] = $this->score;
        $out['varga'] = $this->varga->toArray();
        $out['yogas'] = $this->yogas;
        if ($this->pressure !== null) {
            $out['pressure'] = $this->pressure;
        }
        if ($this->support !== null) {
            $out['support'] = $this->support;
        }

        return $out;
    }
}
