<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreaBasis.lord` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `LifeAreaBasis.lord`.
 */
final readonly class LifeAreaBasisLord
{
    public function __construct(
        public bool $combust,
        public string $dignity,
        public string $functionalClass,
        public int $placedIn,
        public bool $retrograde,
        public ?LabelledId $graha = null,
        public ?int $house = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            combust: Json::bool($data['combust'] ?? null),
            dignity: Json::string($data['dignity'] ?? null),
            functionalClass: Json::string($data['functional_class'] ?? null),
            placedIn: Json::int($data['placed_in'] ?? null),
            retrograde: Json::bool($data['retrograde'] ?? null),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
            house: Json::intOrNull($data['house'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['combust'] = $this->combust;
        $out['dignity'] = $this->dignity;
        $out['functional_class'] = $this->functionalClass;
        $out['placed_in'] = $this->placedIn;
        $out['retrograde'] = $this->retrograde;
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }
        if ($this->house !== null) {
            $out['house'] = $this->house;
        }

        return $out;
    }
}
