<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreasDocument.switches` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `LifeAreasDocument.switches`.
 */
final readonly class LifeAreasDocumentSwitches
{
    public function __construct(
        public LifeAreasDocumentSwitchesFunctional $functional,
        public LifeAreasDocumentSwitchesLifeAreas $lifeAreas,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            functional: LifeAreasDocumentSwitchesFunctional::fromArray(Json::object($data['functional'] ?? null)),
            lifeAreas: LifeAreasDocumentSwitchesLifeAreas::fromArray(Json::object($data['life_areas'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['functional'] = $this->functional->toArray();
        $out['life_areas'] = $this->lifeAreas->toArray();

        return $out;
    }
}
