<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreaBasis.karakas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `LifeAreaBasis.karakas[]`.
 */
final readonly class LifeAreaBasisKarakasItem
{
    public function __construct(
        public bool $combust,
        public string $dignity,
        public int $placedIn,
        public float $score,
        public ?LabelledId $graha = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $grahaRaw = $data['graha'] ?? null;

        return new self(
            combust: Json::bool($data['combust'] ?? null),
            dignity: Json::string($data['dignity'] ?? null),
            placedIn: Json::int($data['placed_in'] ?? null),
            score: Json::float($data['score'] ?? null),
            graha: $grahaRaw === null ? null : LabelledId::fromArray(Json::object($grahaRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['combust'] = $this->combust;
        $out['dignity'] = $this->dignity;
        $out['placed_in'] = $this->placedIn;
        $out['score'] = $this->score;
        if ($this->graha !== null) {
            $out['graha'] = $this->graha->toArray();
        }

        return $out;
    }
}
