<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreasDocumentSwitches.life_areas` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `LifeAreasDocumentSwitches.life_areas`.
 */
final readonly class LifeAreasDocumentSwitchesLifeAreas
{
    public function __construct(
        public bool $beneficRelief,
        public bool $dusthanaOwnSignExempt,
        public string $influenceNature,
        public bool $karakaBhavaNashaya,
        public bool $lagnaLordLink,
        public bool $nodeAspects,
        public string $retrograde,
        public bool $roleSkipsEvilHouse,
        public bool $upachayaMaleficsHelp,
        public bool $viparitaRelief,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            beneficRelief: Json::bool($data['benefic_relief'] ?? null),
            dusthanaOwnSignExempt: Json::bool($data['dusthana_own_sign_exempt'] ?? null),
            influenceNature: Json::string($data['influence_nature'] ?? null),
            karakaBhavaNashaya: Json::bool($data['karaka_bhava_nashaya'] ?? null),
            lagnaLordLink: Json::bool($data['lagna_lord_link'] ?? null),
            nodeAspects: Json::bool($data['node_aspects'] ?? null),
            retrograde: Json::string($data['retrograde'] ?? null),
            roleSkipsEvilHouse: Json::bool($data['role_skips_evil_house'] ?? null),
            upachayaMaleficsHelp: Json::bool($data['upachaya_malefics_help'] ?? null),
            viparitaRelief: Json::bool($data['viparita_relief'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['benefic_relief'] = $this->beneficRelief;
        $out['dusthana_own_sign_exempt'] = $this->dusthanaOwnSignExempt;
        $out['influence_nature'] = $this->influenceNature;
        $out['karaka_bhava_nashaya'] = $this->karakaBhavaNashaya;
        $out['lagna_lord_link'] = $this->lagnaLordLink;
        $out['node_aspects'] = $this->nodeAspects;
        $out['retrograde'] = $this->retrograde;
        $out['role_skips_evil_house'] = $this->roleSkipsEvilHouse;
        $out['upachaya_malefics_help'] = $this->upachayaMaleficsHelp;
        $out['viparita_relief'] = $this->viparitaRelief;

        return $out;
    }
}
