<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreaBasis.varga` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `LifeAreaBasis.varga`.
 */
final readonly class LifeAreaBasisVarga
{
    /**
     * @param list<LifeAreaBasisVargaChecksItem> $checks
     */
    public function __construct(
        public array $checks,
        public string $signal,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            checks: array_map(
                static fn (mixed $v): LifeAreaBasisVargaChecksItem
                    => LifeAreaBasisVargaChecksItem::fromArray(Json::object($v)),
                Json::list($data['checks'] ?? null),
            ),
            signal: Json::string($data['signal'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['checks'] = array_map(static fn (LifeAreaBasisVargaChecksItem $v): array => $v->toArray(), $this->checks);
        $out['signal'] = $this->signal;

        return $out;
    }
}
