<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `LifeAreasDocument.areas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `LifeAreasDocument.areas[]`.
 */
final readonly class LifeArea
{
    /**
     * @param list<YogaReadingPeriodsItem> $periods
     */
    public function __construct(
        public string $area,
        public LifeAreaBasis $basis,
        public string $level,
        public array $periods,
        public ?LocalizedText $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $textRaw = $data['text'] ?? null;

        return new self(
            area: Json::string($data['area'] ?? null),
            basis: LifeAreaBasis::fromArray(Json::object($data['basis'] ?? null)),
            level: Json::string($data['level'] ?? null),
            periods: array_map(
                static fn (mixed $v): YogaReadingPeriodsItem => YogaReadingPeriodsItem::fromArray(Json::object($v)),
                Json::list($data['periods'] ?? null),
            ),
            text: $textRaw === null ? null : LocalizedText::fromArray(Json::object($textRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['area'] = $this->area;
        $out['basis'] = $this->basis->toArray();
        $out['level'] = $this->level;
        $out['periods'] = array_map(static fn (YogaReadingPeriodsItem $v): array => $v->toArray(), $this->periods);
        if ($this->text !== null) {
            $out['text'] = $this->text->toArray();
        }

        return $out;
    }
}
