<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/MaitriDocument{}{}` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `#/components/schemas/MaitriDocument{}{}`.
 */
final readonly class MaitriRelation
{
    public function __construct(
        public string $compound,
        public string $natural,
        public string $temporary,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            compound: Json::string($data['compound'] ?? null),
            natural: Json::string($data['natural'] ?? null),
            temporary: Json::string($data['temporary'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['compound'] = $this->compound;
        $out['natural'] = $this->natural;
        $out['temporary'] = $this->temporary;

        return $out;
    }
}
