<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `MatchBatchRequest.pairs[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `MatchBatchRequest.pairs[]`.
 */
final readonly class MatchBatchRequestPairsItem
{
    /**
     * @param Birth $bride The bride's birth, in the shape of `birth`. The koota table is read from her side.
     * @param Birth $groom The groom's birth, in the shape of `birth`.
     */
    public function __construct(
        public Birth $bride,
        public Birth $groom,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            bride: Birth::fromArray(Json::object($data['bride'] ?? null)),
            groom: Birth::fromArray(Json::object($data['groom'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['bride'] = $this->bride->toArray();
        $out['groom'] = $this->groom->toArray();

        return $out;
    }
}
