<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/MatchAshtakootDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `match_ashtakoot` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/MatchAshtakootDocument`.
 */
final readonly class MatchAshtakootDocument
{
    /**
     * @param list<MatchAshtakootDocumentKootasItem> $kootas
     */
    public function __construct(
        public bool $brideMangalDosha,
        public bool $groomMangalDosha,
        public array $kootas,
        public bool $mangalDoshaMismatch,
        public float $total,
        public string $verdict,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            brideMangalDosha: Json::bool($data['bride_mangal_dosha'] ?? null),
            groomMangalDosha: Json::bool($data['groom_mangal_dosha'] ?? null),
            kootas: array_map(
                static fn (mixed $v): MatchAshtakootDocumentKootasItem
                    => MatchAshtakootDocumentKootasItem::fromArray(Json::object($v)),
                Json::list($data['kootas'] ?? null),
            ),
            mangalDoshaMismatch: Json::bool($data['mangal_dosha_mismatch'] ?? null),
            total: Json::float($data['total'] ?? null),
            verdict: Json::string($data['verdict'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['bride_mangal_dosha'] = $this->brideMangalDosha;
        $out['groom_mangal_dosha'] = $this->groomMangalDosha;
        $out['kootas'] = array_map(
            static fn (MatchAshtakootDocumentKootasItem $v): array => $v->toArray(),
            $this->kootas,
        );
        $out['mangal_dosha_mismatch'] = $this->mangalDoshaMismatch;
        $out['total'] = $this->total;
        $out['verdict'] = $this->verdict;

        return $out;
    }
}
