<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `MatchAshtakootDocument.kootas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `MatchAshtakootDocument.kootas[]`.
 */
final readonly class MatchAshtakootDocumentKootasItem
{
    public function __construct(
        public LabelledId $koota,
        public float $maxPoints,
        public float $points,
        public ?string $note = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            koota: LabelledId::fromArray(Json::object($data['koota'] ?? null)),
            maxPoints: Json::float($data['max_points'] ?? null),
            points: Json::float($data['points'] ?? null),
            note: Json::stringOrNull($data['note'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['koota'] = $this->koota->toArray();
        $out['max_points'] = $this->maxPoints;
        $out['points'] = $this->points;
        if ($this->note !== null) {
            $out['note'] = $this->note;
        }

        return $out;
    }
}
