<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/match/batch body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/match/batch body`.
 */
final readonly class MatchBatchRequest
{
    /**
     * @param list<MatchBatchRequestPairsItem> $pairs The pairs to match, 1 to 100, each `{bride, groom}` as for `POST
     *     /v1/match/ashtakoot`, all under the one `options`. The batch is priced per pair.
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     */
    public function __construct(
        public array $pairs,
        public ?CalculationOptions $options = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;

        return new self(
            pairs: array_map(
                static fn (mixed $v): MatchBatchRequestPairsItem
                    => MatchBatchRequestPairsItem::fromArray(Json::object($v)),
                Json::list($data['pairs'] ?? null),
            ),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['pairs'] = array_map(static fn (MatchBatchRequestPairsItem $v): array => $v->toArray(), $this->pairs);
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }

        return $out;
    }
}
