<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `Meta.ayanamsa` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `Meta.ayanamsa`.
 */
final readonly class MetaAyanamsa
{
    /**
     * @param string $id The slug that was used, e.g. `lahiri`.
     * @param float|null $value Degrees, when the op reports one.
     */
    public function __construct(
        public string $id,
        public ?float $value = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: Json::string($data['id'] ?? null),
            value: Json::floatOrNull($data['value'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['id'] = $this->id;
        if ($this->value !== null) {
            $out['value'] = $this->value;
        }

        return $out;
    }
}
