<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/MuhurtaDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `muhurta` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/MuhurtaDocument`.
 */
final readonly class MuhurtaDocument
{
    /**
     * @param list<MuhurtaDocumentHoraItem> $hora
     */
    public function __construct(
        public TimeWindow $abhijit,
        public bool $abhijitApplies,
        public float $dayMoonLongitude,
        public string $dayMoonLongitudeDms,
        public TimeWindow $gulikaKaal,
        public array $hora,
        public string $nextSunrise,
        public TimeWindow $rahuKaal,
        public string $sunrise,
        public string $sunset,
        public TimeWindow $yamaganda,
        public ?string $chandraBala = null,
        public ?MuhurtaDocumentChoghadiya $choghadiya = null,
        public ?MuhurtaDocumentTaraBala $taraBala = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $choghadiyaRaw = $data['choghadiya'] ?? null;
        $taraBalaRaw = $data['tara_bala'] ?? null;

        return new self(
            abhijit: TimeWindow::fromArray(Json::object($data['abhijit'] ?? null)),
            abhijitApplies: Json::bool($data['abhijit_applies'] ?? null),
            dayMoonLongitude: Json::float($data['day_moon_longitude'] ?? null),
            dayMoonLongitudeDms: Json::string($data['day_moon_longitude_dms'] ?? null),
            gulikaKaal: TimeWindow::fromArray(Json::object($data['gulika_kaal'] ?? null)),
            hora: array_map(
                static fn (mixed $v): MuhurtaDocumentHoraItem => MuhurtaDocumentHoraItem::fromArray(Json::object($v)),
                Json::list($data['hora'] ?? null),
            ),
            nextSunrise: Json::string($data['next_sunrise'] ?? null),
            rahuKaal: TimeWindow::fromArray(Json::object($data['rahu_kaal'] ?? null)),
            sunrise: Json::string($data['sunrise'] ?? null),
            sunset: Json::string($data['sunset'] ?? null),
            yamaganda: TimeWindow::fromArray(Json::object($data['yamaganda'] ?? null)),
            chandraBala: Json::stringOrNull($data['chandra_bala'] ?? null),
            choghadiya: $choghadiyaRaw === null ? null : MuhurtaDocumentChoghadiya::fromArray(Json::object($choghadiyaRaw)),
            taraBala: $taraBalaRaw === null ? null : MuhurtaDocumentTaraBala::fromArray(Json::object($taraBalaRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['abhijit'] = $this->abhijit->toArray();
        $out['abhijit_applies'] = $this->abhijitApplies;
        $out['day_moon_longitude'] = $this->dayMoonLongitude;
        $out['day_moon_longitude_dms'] = $this->dayMoonLongitudeDms;
        $out['gulika_kaal'] = $this->gulikaKaal->toArray();
        $out['hora'] = array_map(static fn (MuhurtaDocumentHoraItem $v): array => $v->toArray(), $this->hora);
        $out['next_sunrise'] = $this->nextSunrise;
        $out['rahu_kaal'] = $this->rahuKaal->toArray();
        $out['sunrise'] = $this->sunrise;
        $out['sunset'] = $this->sunset;
        $out['yamaganda'] = $this->yamaganda->toArray();
        if ($this->chandraBala !== null) {
            $out['chandra_bala'] = $this->chandraBala;
        }
        if ($this->choghadiya !== null) {
            $out['choghadiya'] = $this->choghadiya->toArray();
        }
        if ($this->taraBala !== null) {
            $out['tara_bala'] = $this->taraBala->toArray();
        }

        return $out;
    }
}
