<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `MuhurtaDocument.hora[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `MuhurtaDocument.hora[]`.
 */
final readonly class MuhurtaDocumentHoraItem
{
    public function __construct(
        public string $end,
        public string $start,
        public mixed $choghadiya = null,
        public mixed $good = null,
        public ?LabelledId $planet = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $planetRaw = $data['planet'] ?? null;

        return new self(
            end: Json::string($data['end'] ?? null),
            start: Json::string($data['start'] ?? null),
            choghadiya: $data['choghadiya'] ?? null,
            good: $data['good'] ?? null,
            planet: $planetRaw === null ? null : LabelledId::fromArray(Json::object($planetRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['end'] = $this->end;
        $out['start'] = $this->start;
        if ($this->choghadiya !== null) {
            $out['choghadiya'] = $this->choghadiya;
        }
        if ($this->good !== null) {
            $out['good'] = $this->good;
        }
        if ($this->planet !== null) {
            $out['planet'] = $this->planet->toArray();
        }

        return $out;
    }
}
