<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `MuhurtaDocumentChoghadiya.day[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `MuhurtaDocumentChoghadiya.day[]`.
 */
final readonly class MuhurtaDocumentChoghadiyaDayItem
{
    public function __construct(
        public string $end,
        public string $start,
        public ?string $choghadiya = null,
        public ?bool $good = null,
        public mixed $planet = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            end: Json::string($data['end'] ?? null),
            start: Json::string($data['start'] ?? null),
            choghadiya: Json::stringOrNull($data['choghadiya'] ?? null),
            good: Json::boolOrNull($data['good'] ?? null),
            planet: $data['planet'] ?? null,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['end'] = $this->end;
        $out['start'] = $this->start;
        if ($this->choghadiya !== null) {
            $out['choghadiya'] = $this->choghadiya;
        }
        if ($this->good !== null) {
            $out['good'] = $this->good;
        }
        if ($this->planet !== null) {
            $out['planet'] = $this->planet;
        }

        return $out;
    }
}
