<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `Nakshatra28Document.moon` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `Nakshatra28Document.moon`.
 */
final readonly class Nakshatra28DocumentMoon
{
    public function __construct(
        public string $abbr,
        public string $deity,
        public int $index,
        public string $name,
        public string $symbol,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            abbr: Json::string($data['abbr'] ?? null),
            deity: Json::string($data['deity'] ?? null),
            index: Json::int($data['index'] ?? null),
            name: Json::string($data['name'] ?? null),
            symbol: Json::string($data['symbol'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['abbr'] = $this->abbr;
        $out['deity'] = $this->deity;
        $out['index'] = $this->index;
        $out['name'] = $this->name;
        $out['symbol'] = $this->symbol;

        return $out;
    }
}
