<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `PaceDocument.entries[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `PaceDocument.entries[]`.
 */
final readonly class PaceDocumentEntriesItem
{
    /**
     * @param list<PaceDocumentEntriesItemAspectedByItem> $aspectedBy
     * @param list<LabelledId> $conjunctWith
     */
    public function __construct(
        public array $aspectedBy,
        public array $conjunctWith,
        public LabelledId $graha,
        public int $influenceCount,
        public bool $isUntouched,
        public PaceDocumentEntriesItemPosition $position,
        public ?LabelledId $exchangeWith = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $exchangeWithRaw = $data['exchange_with'] ?? null;

        return new self(
            aspectedBy: array_map(
                static fn (mixed $v): PaceDocumentEntriesItemAspectedByItem
                    => PaceDocumentEntriesItemAspectedByItem::fromArray(Json::object($v)),
                Json::list($data['aspected_by'] ?? null),
            ),
            conjunctWith: array_map(
                static fn (mixed $v): LabelledId => LabelledId::fromArray(Json::object($v)),
                Json::list($data['conjunct_with'] ?? null),
            ),
            graha: LabelledId::fromArray(Json::object($data['graha'] ?? null)),
            influenceCount: Json::int($data['influence_count'] ?? null),
            isUntouched: Json::bool($data['is_untouched'] ?? null),
            position: PaceDocumentEntriesItemPosition::fromArray(Json::object($data['position'] ?? null)),
            exchangeWith: $exchangeWithRaw === null ? null : LabelledId::fromArray(Json::object($exchangeWithRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['aspected_by'] = array_map(
            static fn (PaceDocumentEntriesItemAspectedByItem $v): array => $v->toArray(),
            $this->aspectedBy,
        );
        $out['conjunct_with'] = array_map(static fn (LabelledId $v): array => $v->toArray(), $this->conjunctWith);
        $out['graha'] = $this->graha->toArray();
        $out['influence_count'] = $this->influenceCount;
        $out['is_untouched'] = $this->isUntouched;
        $out['position'] = $this->position->toArray();
        if ($this->exchangeWith !== null) {
            $out['exchange_with'] = $this->exchangeWith->toArray();
        }

        return $out;
    }
}
