<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `PaceDocumentEntriesItem.position` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `PaceDocumentEntriesItem.position`.
 */
final readonly class PaceDocumentEntriesItemPosition
{
    /**
     * @param list<int> $lordOf
     * @param list<string> $nature
     */
    public function __construct(
        public string $dignity,
        public int $house,
        public array $lordOf,
        public array $nature,
        public LabelledId $sign,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            dignity: Json::string($data['dignity'] ?? null),
            house: Json::int($data['house'] ?? null),
            lordOf: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['lord_of'] ?? null)),
            nature: array_map(static fn (mixed $v): string => Json::string($v), Json::list($data['nature'] ?? null)),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['dignity'] = $this->dignity;
        $out['house'] = $this->house;
        $out['lord_of'] = $this->lordOf;
        $out['nature'] = $this->nature;
        $out['sign'] = $this->sign->toArray();

        return $out;
    }
}
