<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `PaceDocument.bhava_lords[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `PaceDocument.bhava_lords[]`.
 */
final readonly class PaceDocumentBhavaLordsItem
{
    public function __construct(
        public int $house,
        public bool $isInOwnBhava,
        public LabelledId $lord,
        public int $lordHouse,
        public LabelledId $lordSign,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            house: Json::int($data['house'] ?? null),
            isInOwnBhava: Json::bool($data['is_in_own_bhava'] ?? null),
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            lordHouse: Json::int($data['lord_house'] ?? null),
            lordSign: LabelledId::fromArray(Json::object($data['lord_sign'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['house'] = $this->house;
        $out['is_in_own_bhava'] = $this->isInOwnBhava;
        $out['lord'] = $this->lord->toArray();
        $out['lord_house'] = $this->lordHouse;
        $out['lord_sign'] = $this->lordSign->toArray();

        return $out;
    }
}
