<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `PanchangMonthDocumentDaysItem.karanas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `PanchangMonthDocumentDaysItem.karanas[]`.
 */
final readonly class PanchangMonthDocumentDaysItemKaranasItem
{
    public function __construct(
        public string $ends,
        public int $index,
        public LabelledId $name,
        public ?string $starts = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            ends: Json::string($data['ends'] ?? null),
            index: Json::int($data['index'] ?? null),
            name: LabelledId::fromArray(Json::object($data['name'] ?? null)),
            starts: Json::stringOrNull($data['starts'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['ends'] = $this->ends;
        $out['index'] = $this->index;
        $out['name'] = $this->name->toArray();
        if ($this->starts !== null) {
            $out['starts'] = $this->starts;
        }

        return $out;
    }
}
