<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `PanchangMonthDocument.days[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `PanchangMonthDocument.days[]`.
 */
final readonly class PanchangMonthDocumentDaysItem
{
    /**
     * @param list<PanchangMonthDocumentDaysItemKaranasItem> $karanas
     * @param list<PanchangMonthDocumentDaysItemNakshatrasItem> $nakshatras
     * @param list<DailyPanchangDocumentTithisItem> $tithis
     * @param list<PanchangMonthDocumentDaysItemKaranasItem> $yogas
     */
    public function __construct(
        public string $date,
        public array $karanas,
        public VikramSamvatDocument $masa,
        public array $nakshatras,
        public array $tithis,
        public LabelledId $vara,
        public int $varaIndex,
        public array $yogas,
        public ?string $nextSunrise = null,
        public ?string $sunrise = null,
        public ?string $sunset = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            date: Json::string($data['date'] ?? null),
            karanas: array_map(
                static fn (mixed $v): PanchangMonthDocumentDaysItemKaranasItem
                    => PanchangMonthDocumentDaysItemKaranasItem::fromArray(Json::object($v)),
                Json::list($data['karanas'] ?? null),
            ),
            masa: VikramSamvatDocument::fromArray(Json::object($data['masa'] ?? null)),
            nakshatras: array_map(
                static fn (mixed $v): PanchangMonthDocumentDaysItemNakshatrasItem
                    => PanchangMonthDocumentDaysItemNakshatrasItem::fromArray(Json::object($v)),
                Json::list($data['nakshatras'] ?? null),
            ),
            tithis: array_map(
                static fn (mixed $v): DailyPanchangDocumentTithisItem
                    => DailyPanchangDocumentTithisItem::fromArray(Json::object($v)),
                Json::list($data['tithis'] ?? null),
            ),
            vara: LabelledId::fromArray(Json::object($data['vara'] ?? null)),
            varaIndex: Json::int($data['vara_index'] ?? null),
            yogas: array_map(
                static fn (mixed $v): PanchangMonthDocumentDaysItemKaranasItem
                    => PanchangMonthDocumentDaysItemKaranasItem::fromArray(Json::object($v)),
                Json::list($data['yogas'] ?? null),
            ),
            nextSunrise: Json::stringOrNull($data['next_sunrise'] ?? null),
            sunrise: Json::stringOrNull($data['sunrise'] ?? null),
            sunset: Json::stringOrNull($data['sunset'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['date'] = $this->date;
        $out['karanas'] = array_map(
            static fn (PanchangMonthDocumentDaysItemKaranasItem $v): array => $v->toArray(),
            $this->karanas,
        );
        $out['masa'] = $this->masa->toArray();
        $out['nakshatras'] = array_map(
            static fn (PanchangMonthDocumentDaysItemNakshatrasItem $v): array => $v->toArray(),
            $this->nakshatras,
        );
        $out['tithis'] = array_map(
            static fn (DailyPanchangDocumentTithisItem $v): array => $v->toArray(),
            $this->tithis,
        );
        $out['vara'] = $this->vara->toArray();
        $out['vara_index'] = $this->varaIndex;
        $out['yogas'] = array_map(
            static fn (PanchangMonthDocumentDaysItemKaranasItem $v): array => $v->toArray(),
            $this->yogas,
        );
        if ($this->nextSunrise !== null) {
            $out['next_sunrise'] = $this->nextSunrise;
        }
        if ($this->sunrise !== null) {
            $out['sunrise'] = $this->sunrise;
        }
        if ($this->sunset !== null) {
            $out['sunset'] = $this->sunset;
        }

        return $out;
    }
}
