<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `PdfKundliRequest.branding` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * This PDF's branding instead of the account's, **Enterprise plan only** (any other plan gets `403 plan_required`). It
 * replaces the stored branding as a whole: a field left out is not printed.
 *
 * Wire shape: `PdfKundliRequest.branding`.
 */
final readonly class PdfBranding
{
    /**
     * @param string|null $name Your name or your practice's, as it should be printed; up to 300 characters.
     * @param string|null $logo The logo file itself, base64 (a `data:image/png;base64,` prefix is accepted): PNG, JPEG
     *     or SVG, at most 200 KB decoded. Never a URL. An SVG must be self-contained: no scripts, event handlers or
     *     references outside the file.
     * @param string|null $address Postal address, one or more lines; up to 300 characters.
     * @param string|null $phone Phone number as it should be printed, e.g. `+91 98100 00000`; up to 300 characters.
     * @param string|null $email E-mail address; up to 300 characters.
     * @param string|null $website Web address as it should be printed; up to 300 characters.
     * @param string|null $accent Accent colour, `#RRGGBB`, e.g. `#8B1E3F`. Default: the template's own.
     * @param string|null $footer A line printed in every page footer; up to 300 characters.
     * @param bool|null $poweredBy Print "Powered by Kaal Jyoti" on the last page. Default `true`.
     * @param string|null $invocation One line at the top of the cover, e.g. `॥ श्री गणेशाय नमः ॥`: text only, Latin or
     *     Devanagari, up to 120 characters. Default: none.
     * @param string|null $about Your own "about us", printed on a back page: plain text, up to 1500 characters; a blank
     *     line starts a new paragraph. Default: no back page.
     */
    public function __construct(
        public ?string $name = null,
        public ?string $logo = null,
        public ?string $address = null,
        public ?string $phone = null,
        public ?string $email = null,
        public ?string $website = null,
        public ?string $accent = null,
        public ?string $footer = null,
        public ?bool $poweredBy = null,
        public ?string $invocation = null,
        public ?string $about = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: Json::stringOrNull($data['name'] ?? null),
            logo: Json::stringOrNull($data['logo'] ?? null),
            address: Json::stringOrNull($data['address'] ?? null),
            phone: Json::stringOrNull($data['phone'] ?? null),
            email: Json::stringOrNull($data['email'] ?? null),
            website: Json::stringOrNull($data['website'] ?? null),
            accent: Json::stringOrNull($data['accent'] ?? null),
            footer: Json::stringOrNull($data['footer'] ?? null),
            poweredBy: Json::boolOrNull($data['powered_by'] ?? null),
            invocation: Json::stringOrNull($data['invocation'] ?? null),
            about: Json::stringOrNull($data['about'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->name !== null) {
            $out['name'] = $this->name;
        }
        if ($this->logo !== null) {
            $out['logo'] = $this->logo;
        }
        if ($this->address !== null) {
            $out['address'] = $this->address;
        }
        if ($this->phone !== null) {
            $out['phone'] = $this->phone;
        }
        if ($this->email !== null) {
            $out['email'] = $this->email;
        }
        if ($this->website !== null) {
            $out['website'] = $this->website;
        }
        if ($this->accent !== null) {
            $out['accent'] = $this->accent;
        }
        if ($this->footer !== null) {
            $out['footer'] = $this->footer;
        }
        if ($this->poweredBy !== null) {
            $out['powered_by'] = $this->poweredBy;
        }
        if ($this->invocation !== null) {
            $out['invocation'] = $this->invocation;
        }
        if ($this->about !== null) {
            $out['about'] = $this->about;
        }

        return $out;
    }
}
