<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/pdf/kundli options` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The kundli PDF's options: `CalculationOptions` plus `houseSystem`.
 *
 * `houseSystem` picks the bhava chalit the PDF prints (default
 * `placidus`); every other route refuses it with a `400`.
 *
 * Wire shape: `POST /v1/pdf/kundli options`.
 */
final readonly class PdfKundliOptions
{
    /**
     * @param string|null $ayanamsa The ayanamsa: where the sidereal zodiac starts, which shifts every longitude, sign
     *     and nakshatra. Default `lahiri`. The full list with names is `GET /v1/reference/ayanamsas` (free); the one
     *     used, with its value in degrees, is reported in `meta.ayanamsa`.
     * @param list<string>|null $language The languages labels should come back in. Always a list here — `language:
     *     ['en', 'hi']` — and a single language is written to the wire as the bare string the API documents.
     * @param string|null $engine The engine version you built against, e.g. `0.14.2`, up to 32 characters. Accepted for
     *     forward compatibility and not acted on yet: every answer is computed by the current engine, whose version is
     *     in `meta.engine`.
     * @param string|Disclaimer|null $disclaimer The line a written reading ends with, on the report routes, `POST
     *     /v1/horoscope` and the PDFs; other routes ignore it. `"default"` (the default): "…consult an astrologer".
     *     `{"name", "url"}`: names your own astrologer instead. `"off"`: no line, e.g. for a reading an astrologer
     *     hands to their own client.
     * @param string|null $houseSystem The house system of the bhava chalit this PDF prints. Default `placidus`. The
     *     chalit takes the system's points as house middles (madhyas), with each boundary halfway between two:
     *     `placidus`, the Placidus cusps; `equal`, every 30° from the ascendant; `sripati`, the Porphyry cusps. `kp`
     *     takes the Placidus cusps as house starts. `whole_sign` and `porphyry` print a Sripati chalit. It does not
     *     change the sign charts or the readings, which are whole sign from the lagna. (`POST /v1/kundli/chalit` takes
     *     its own `system`.)
     */
    public function __construct(
        public ?string $ayanamsa = null,
        public ?array $language = null,
        public ?string $engine = null,
        public string|Disclaimer|null $disclaimer = null,
        public ?string $houseSystem = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $disclaimerRaw = $data['disclaimer'] ?? null;
        $disclaimer = is_string($disclaimerRaw) || $disclaimerRaw === null
            ? $disclaimerRaw
            : Disclaimer::fromArray(Json::object($disclaimerRaw));

        return new self(
            ayanamsa: Json::stringOrNull($data['ayanamsa'] ?? null),
            language: Json::languagesOrNull($data['language'] ?? null),
            engine: Json::stringOrNull($data['engine'] ?? null),
            disclaimer: $disclaimer,
            houseSystem: Json::stringOrNull($data['house_system'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->ayanamsa !== null) {
            $out['ayanamsa'] = $this->ayanamsa;
        }
        if ($this->language !== null) {
            $out['language'] = count($this->language) === 1 ? $this->language[0] : $this->language;
        }
        if ($this->engine !== null) {
            $out['engine'] = $this->engine;
        }
        if ($this->disclaimer !== null) {
            $out['disclaimer'] = is_string($this->disclaimer) ? $this->disclaimer : $this->disclaimer->toArray();
        }
        if ($this->houseSystem !== null) {
            $out['house_system'] = $this->houseSystem;
        }

        return $out;
    }
}
