<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/pdf/kundli body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/pdf/kundli body`.
 */
final readonly class PdfKundliRequest
{
    /**
     * @param Birth $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its zone
     *     (`timezone` or `utc_offset`, not both).
     * @param PdfKundliOptions|null $options Settings for the calculation and the answer: ayanamsa, house system (of the
     *     bhava chalit), language, disclaimer. Every field has a default, so `options` may be left out.
     * @param string|null $template The look: `classic` (serif type, a framed cover), `modern` (sans type, accent
     *     bands), `minimal` (black on white, for a monochrome printer) or `traditional` (maroon, saffron and gold, an
     *     ornamental border). Default: the one set on your Branding page, else `classic`.
     * @param string|null $chartStyle How the charts are drawn: `north` (North Indian, the default) or `south` (South
     *     Indian).
     * @param PdfBranding|null $branding This PDF's branding instead of the account's, **Enterprise plan only** (any
     *     other plan gets `403 plan_required`). It replaces the stored branding as a whole: a field left out is not
     *     printed.
     * @param string|null $name The person's name, printed on the cover and used in the file name; 1 to 120 characters.
     *     Default: none (the cover carries the title only).
     * @param string|null $edition How much the kundli prints: `basic` (the default, about 12 to 27 pages),
     *     `professional` (the astrologer's edition, every technical section, about 30 to 45) or `life` (the Life
     *     Report, written for the person it is about: who they are, each area of life in depth, Manglik, Sade Sati and
     *     the dasha timeline). All three cost the same.
     * @param list<string>|null $sections The sections to print, by id, in any order (the PDF keeps its own), e.g.
     *     `["details", "charts", "kp_planets", "kp_cusps"]`. Default: the edition's. The cover always prints.
     * @param list<string>|null $vargas The charts drawn, by id, `d1` to `d60`: 1 or 2 beside the Moon chart, or up to
     *     16 when the `vargas` section is printed. Default `["d1", "d9"]`; the professional edition adds D2, D3, D4,
     *     D7, D10, D12, D16, D20, D24, D30 and D60.
     */
    public function __construct(
        public Birth $birth,
        public ?PdfKundliOptions $options = null,
        public ?string $template = null,
        public ?string $chartStyle = null,
        public ?PdfBranding $branding = null,
        public ?string $name = null,
        public ?string $edition = null,
        public ?array $sections = null,
        public ?array $vargas = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;
        $brandingRaw = $data['branding'] ?? null;
        $sectionsRaw = $data['sections'] ?? null;
        $vargasRaw = $data['vargas'] ?? null;

        return new self(
            birth: Birth::fromArray(Json::object($data['birth'] ?? null)),
            options: $optionsRaw === null ? null : PdfKundliOptions::fromArray(Json::object($optionsRaw)),
            template: Json::stringOrNull($data['template'] ?? null),
            chartStyle: Json::stringOrNull($data['chart_style'] ?? null),
            branding: $brandingRaw === null ? null : PdfBranding::fromArray(Json::object($brandingRaw)),
            name: Json::stringOrNull($data['name'] ?? null),
            edition: Json::stringOrNull($data['edition'] ?? null),
            sections: $sectionsRaw === null ? null : array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($sectionsRaw),
            ),
            vargas: $vargasRaw === null ? null : array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($vargasRaw),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['birth'] = $this->birth->toArray();
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }
        if ($this->template !== null) {
            $out['template'] = $this->template;
        }
        if ($this->chartStyle !== null) {
            $out['chart_style'] = $this->chartStyle;
        }
        if ($this->branding !== null) {
            $out['branding'] = $this->branding->toArray();
        }
        if ($this->name !== null) {
            $out['name'] = $this->name;
        }
        if ($this->edition !== null) {
            $out['edition'] = $this->edition;
        }
        if ($this->sections !== null) {
            $out['sections'] = $this->sections;
        }
        if ($this->vargas !== null) {
            $out['vargas'] = $this->vargas;
        }

        return $out;
    }
}
