<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/pdf/varshphal body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/pdf/varshphal body`.
 */
final readonly class PdfVarshphalRequest
{
    /**
     * @param Birth $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its zone
     *     (`timezone` or `utc_offset`, not both).
     * @param int $year The year, e.g. `2026`, required: the annual chart runs from that year's birthday to the next.
     *     Not before the birth year; at most 2399.
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     * @param string|null $template The look: `classic` (serif type, a framed cover), `modern` (sans type, accent
     *     bands), `minimal` (black on white, for a monochrome printer) or `traditional` (maroon, saffron and gold, an
     *     ornamental border). Default: the one set on your Branding page, else `classic`.
     * @param string|null $chartStyle How the charts are drawn: `north` (North Indian, the default) or `south` (South
     *     Indian).
     * @param PdfBranding|null $branding This PDF's branding instead of the account's, **Enterprise plan only** (any
     *     other plan gets `403 plan_required`). It replaces the stored branding as a whole: a field left out is not
     *     printed.
     * @param string|null $name The person's name, printed on the cover and used in the file name; 1 to 120 characters.
     *     Default: none (the cover carries the title only).
     */
    public function __construct(
        public Birth $birth,
        public int $year,
        public ?CalculationOptions $options = null,
        public ?string $template = null,
        public ?string $chartStyle = null,
        public ?PdfBranding $branding = null,
        public ?string $name = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;
        $brandingRaw = $data['branding'] ?? null;

        return new self(
            birth: Birth::fromArray(Json::object($data['birth'] ?? null)),
            year: Json::int($data['year'] ?? null),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
            template: Json::stringOrNull($data['template'] ?? null),
            chartStyle: Json::stringOrNull($data['chart_style'] ?? null),
            branding: $brandingRaw === null ? null : PdfBranding::fromArray(Json::object($brandingRaw)),
            name: Json::stringOrNull($data['name'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['birth'] = $this->birth->toArray();
        $out['year'] = $this->year;
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }
        if ($this->template !== null) {
            $out['template'] = $this->template;
        }
        if ($this->chartStyle !== null) {
            $out['chart_style'] = $this->chartStyle;
        }
        if ($this->branding !== null) {
            $out['branding'] = $this->branding->toArray();
        }
        if ($this->name !== null) {
            $out['name'] = $this->name;
        }

        return $out;
    }
}
