<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `GET /v1/places meta` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `GET /v1/places meta`.
 */
final readonly class PlacesMeta
{
    /**
     * @param list<string>|null $language
     * @param int|null $credits Credits this search cost.
     */
    public function __construct(
        public ?string $query = null,
        public ?array $language = null,
        public ?int $count = null,
        public ?string $source = null,
        public ?int $credits = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $languageRaw = $data['language'] ?? null;

        return new self(
            query: Json::stringOrNull($data['query'] ?? null),
            language: $languageRaw === null ? null : array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($languageRaw),
            ),
            count: Json::intOrNull($data['count'] ?? null),
            source: Json::stringOrNull($data['source'] ?? null),
            credits: Json::intOrNull($data['credits'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->query !== null) {
            $out['query'] = $this->query;
        }
        if ($this->language !== null) {
            $out['language'] = $this->language;
        }
        if ($this->count !== null) {
            $out['count'] = $this->count;
        }
        if ($this->source !== null) {
            $out['source'] = $this->source;
        }
        if ($this->credits !== null) {
            $out['credits'] = $this->credits;
        }

        return $out;
    }
}
