<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `ReadingNakshatraDocument.nakshatra` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `ReadingNakshatraDocument.nakshatra`.
 */
final readonly class ReadingNakshatra
{
    public function __construct(
        public LabelledId $nakshatra,
        public ?ReadingEntry $entry = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $entryRaw = $data['entry'] ?? null;

        return new self(
            nakshatra: LabelledId::fromArray(Json::object($data['nakshatra'] ?? null)),
            entry: $entryRaw === null ? null : ReadingEntry::fromArray(Json::object($entryRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['nakshatra'] = $this->nakshatra->toArray();
        if ($this->entry !== null) {
            $out['entry'] = $this->entry->toArray();
        }

        return $out;
    }
}
