<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/ReadingHouseLordsDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `reading` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/ReadingHouseLordsDocument`.
 */
final readonly class ReadingHouseLordsDocument
{
    /**
     * @param list<HouseLord>|null $houseLords
     * @param LocalizedText|null $disclaimer The closing line: "these predictions are indicative…", naming the
     *     astrologer in `options.disclaimer` when one is given. Absent when `options.disclaimer` is `"off"`.
     */
    public function __construct(
        public ?array $houseLords = null,
        public ?LocalizedText $disclaimer = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $houseLordsRaw = $data['house_lords'] ?? null;
        $disclaimerRaw = $data['disclaimer'] ?? null;

        return new self(
            houseLords: $houseLordsRaw === null ? null : array_map(
                static fn (mixed $v): HouseLord => HouseLord::fromArray(Json::object($v)),
                Json::list($houseLordsRaw),
            ),
            disclaimer: $disclaimerRaw === null ? null : LocalizedText::fromArray(Json::object($disclaimerRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->houseLords !== null) {
            $out['house_lords'] = array_map(static fn (HouseLord $v): array => $v->toArray(), $this->houseLords);
        }
        if ($this->disclaimer !== null) {
            $out['disclaimer'] = $this->disclaimer->toArray();
        }

        return $out;
    }
}
