<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `ReadingLagna.entry` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `ReadingLagna.entry`.
 */
final readonly class ReadingEntry
{
    /**
     * @param LocalizedText $text One piece of text, keyed by language: one entry for each language in
     *     `options.language`, in that order (`{"hi": "…"}` or `{"en": "…", "hi": "…"}`).
     */
    public function __construct(
        public LocalizedText $text,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            text: LocalizedText::fromArray(Json::object($data['text'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['text'] = $this->text->toArray();

        return $out;
    }
}
