<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/ReadingYogasDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `reading` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/ReadingYogasDocument`.
 */
final readonly class ReadingYogasDocument
{
    /**
     * @param list<YogaReading>|null $yogas
     * @param LocalizedText|null $disclaimer The closing line: "these predictions are indicative…", naming the
     *     astrologer in `options.disclaimer` when one is given. Absent when `options.disclaimer` is `"off"`.
     */
    public function __construct(
        public ?array $yogas = null,
        public ?LocalizedText $disclaimer = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $yogasRaw = $data['yogas'] ?? null;
        $disclaimerRaw = $data['disclaimer'] ?? null;

        return new self(
            yogas: $yogasRaw === null ? null : array_map(
                static fn (mixed $v): YogaReading => YogaReading::fromArray(Json::object($v)),
                Json::list($yogasRaw),
            ),
            disclaimer: $disclaimerRaw === null ? null : LocalizedText::fromArray(Json::object($disclaimerRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->yogas !== null) {
            $out['yogas'] = array_map(static fn (YogaReading $v): array => $v->toArray(), $this->yogas);
        }
        if ($this->disclaimer !== null) {
            $out['disclaimer'] = $this->disclaimer->toArray();
        }

        return $out;
    }
}
