<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `GET /v1/reference/{list} meta` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `GET /v1/reference/{list} meta`.
 */
final readonly class ReferenceMeta
{
    /**
     * @param list<string>|null $language
     */
    public function __construct(
        public ?string $engine = null,
        public ?array $language = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $languageRaw = $data['language'] ?? null;

        return new self(
            engine: Json::stringOrNull($data['engine'] ?? null),
            language: $languageRaw === null ? null : array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($languageRaw),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->engine !== null) {
            $out['engine'] = $this->engine;
        }
        if ($this->language !== null) {
            $out['language'] = $this->language;
        }

        return $out;
    }
}
