<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/reports/nakshatra body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/reports/nakshatra body`.
 */
final readonly class ReportNakshatraRequest
{
    /**
     * @param Birth|null $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its
     *     zone (`timezone` or `utc_offset`, not both). The report reads the Moon's nakshatra. Give this or `nakshatra`,
     *     not both.
     * @param string|null $nakshatra The nakshatra to read, e.g. `rohini`, when there is no birth. Give this or `birth`,
     *     not both.
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     */
    public function __construct(
        public ?Birth $birth = null,
        public ?string $nakshatra = null,
        public ?CalculationOptions $options = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $birthRaw = $data['birth'] ?? null;
        $optionsRaw = $data['options'] ?? null;

        return new self(
            birth: $birthRaw === null ? null : Birth::fromArray(Json::object($birthRaw)),
            nakshatra: Json::stringOrNull($data['nakshatra'] ?? null),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->birth !== null) {
            $out['birth'] = $this->birth->toArray();
        }
        if ($this->nakshatra !== null) {
            $out['nakshatra'] = $this->nakshatra;
        }
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }

        return $out;
    }
}
