<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `SadeSatiDocument.phases[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `SadeSatiDocument.phases[]`.
 */
final readonly class SadeSatiDocumentPhasesItem
{
    public function __construct(
        public string $end,
        public string $kind,
        public LabelledId $sign,
        public string $start,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            end: Json::string($data['end'] ?? null),
            kind: Json::string($data['kind'] ?? null),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            start: Json::string($data['start'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['end'] = $this->end;
        $out['kind'] = $this->kind;
        $out['sign'] = $this->sign->toArray();
        $out['start'] = $this->start;

        return $out;
    }
}
