<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `SadeSatiDocument.arc_spans[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `SadeSatiDocument.arc_spans[]`.
 */
final readonly class SadeSatiDocumentArcSpansItem
{
    public function __construct(
        public string $end,
        public string $kind,
        public string $start,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            end: Json::string($data['end'] ?? null),
            kind: Json::string($data['kind'] ?? null),
            start: Json::string($data['start'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['end'] = $this->end;
        $out['kind'] = $this->kind;
        $out['start'] = $this->start;

        return $out;
    }
}
