<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/SadeSatiDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `sade_sati` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/SadeSatiDocument`.
 */
final readonly class SadeSatiDocument
{
    /**
     * @param list<SadeSatiDocumentArcSpansItem> $arcSpans
     * @param list<SadeSatiDocumentDegreeWindowsItem> $degreeWindows
     * @param list<SadeSatiDocumentPhasesItem> $phases
     */
    public function __construct(
        public array $arcSpans,
        public array $degreeWindows,
        public array $phases,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            arcSpans: array_map(
                static fn (mixed $v): SadeSatiDocumentArcSpansItem
                    => SadeSatiDocumentArcSpansItem::fromArray(Json::object($v)),
                Json::list($data['arc_spans'] ?? null),
            ),
            degreeWindows: array_map(
                static fn (mixed $v): SadeSatiDocumentDegreeWindowsItem
                    => SadeSatiDocumentDegreeWindowsItem::fromArray(Json::object($v)),
                Json::list($data['degree_windows'] ?? null),
            ),
            phases: array_map(
                static fn (mixed $v): SadeSatiDocumentPhasesItem
                    => SadeSatiDocumentPhasesItem::fromArray(Json::object($v)),
                Json::list($data['phases'] ?? null),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['arc_spans'] = array_map(
            static fn (SadeSatiDocumentArcSpansItem $v): array => $v->toArray(),
            $this->arcSpans,
        );
        $out['degree_windows'] = array_map(
            static fn (SadeSatiDocumentDegreeWindowsItem $v): array => $v->toArray(),
            $this->degreeWindows,
        );
        $out['phases'] = array_map(static fn (SadeSatiDocumentPhasesItem $v): array => $v->toArray(), $this->phases);

        return $out;
    }
}
