<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/kundli/sade-sati body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/kundli/sade-sati body`.
 */
final readonly class SadeSatiRequest
{
    /**
     * @param Birth $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its zone
     *     (`timezone` or `utc_offset`, not both).
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     * @param string|null $from Start of the window: a UTC instant, `YYYY-MM-DDTHH:MM:SS` (optionally `.sss`), `Z`
     *     optional, e.g. `2026-01-01T00:00:00Z`. Default: today's midnight, UTC.
     * @param string|null $to End of the window: a UTC instant, `YYYY-MM-DDTHH:MM:SS` (optionally `.sss`), `Z` optional,
     *     e.g. `2026-01-01T00:00:00Z`. Default: 365 days after `from`; at most 366 days after it.
     */
    public function __construct(
        public Birth $birth,
        public ?CalculationOptions $options = null,
        public ?string $from = null,
        public ?string $to = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;

        return new self(
            birth: Birth::fromArray(Json::object($data['birth'] ?? null)),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
            from: Json::stringOrNull($data['from'] ?? null),
            to: Json::stringOrNull($data['to'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['birth'] = $this->birth->toArray();
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }
        if ($this->from !== null) {
            $out['from'] = $this->from;
        }
        if ($this->to !== null) {
            $out['to'] = $this->to;
        }

        return $out;
    }
}
