<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/SarvatobhadraDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `sarvatobhadra` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/SarvatobhadraDocument`.
 */
final readonly class SarvatobhadraDocument
{
    /**
     * @param array<string, list<int>> $nakCell
     * @param array<string, list<int>> $rashiCell
     * @param list<int> $tithiCell
     * @param list<int> $varaCell
     * @param array<string, list<list<int>>> $vedhas
     */
    public function __construct(
        public array $nakCell,
        public array $rashiCell,
        public array $tithiCell,
        public array $varaCell,
        public array $vedhas,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $nakCell = [];
        foreach (Json::object($data['nak_cell'] ?? null) as $key => $value) {
            $nakCell[$key] = array_map(static fn (mixed $item): int => Json::int($item), Json::list($value));
        }
        $rashiCell = [];
        foreach (Json::object($data['rashi_cell'] ?? null) as $key => $value) {
            $rashiCell[$key] = array_map(static fn (mixed $item): int => Json::int($item), Json::list($value));
        }
        $vedhas = [];
        foreach (Json::object($data['vedhas'] ?? null) as $key => $value) {
            $vedhas[$key] = array_map(
                static fn (mixed $item): array
                    => array_map(static fn (mixed $v3): int => Json::int($v3), Json::list($item)),
                Json::list($value),
            );
        }

        return new self(
            nakCell: $nakCell,
            rashiCell: $rashiCell,
            tithiCell: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['tithi_cell'] ?? null)),
            varaCell: array_map(static fn (mixed $v): int => Json::int($v), Json::list($data['vara_cell'] ?? null)),
            vedhas: $vedhas,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['nak_cell'] = $this->nakCell;
        $out['rashi_cell'] = $this->rashiCell;
        $out['tithi_cell'] = $this->tithiCell;
        $out['vara_cell'] = $this->varaCell;
        $out['vedhas'] = $this->vedhas;

        return $out;
    }
}
