<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/ShadbalaDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `shadbala` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/ShadbalaDocument`.
 */
final readonly class ShadbalaDocument
{
    /**
     * @param list<ShadbalaDocumentPlanetsItem> $planets
     */
    public function __construct(
        public array $planets,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            planets: array_map(
                static fn (mixed $v): ShadbalaDocumentPlanetsItem
                    => ShadbalaDocumentPlanetsItem::fromArray(Json::object($v)),
                Json::list($data['planets'] ?? null),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['planets'] = array_map(static fn (ShadbalaDocumentPlanetsItem $v): array => $v->toArray(), $this->planets);

        return $out;
    }
}
