<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `SpecialLagnasDocument.points[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `SpecialLagnasDocument.points[]`.
 */
final readonly class SpecialLagnasDocumentPointsItem
{
    public function __construct(
        public string $kind,
        public LabelledId $sign,
        public ?float $longitude = null,
        public ?string $longitudeDms = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            kind: Json::string($data['kind'] ?? null),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            longitude: Json::floatOrNull($data['longitude'] ?? null),
            longitudeDms: Json::stringOrNull($data['longitude_dms'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['kind'] = $this->kind;
        $out['sign'] = $this->sign->toArray();
        if ($this->longitude !== null) {
            $out['longitude'] = $this->longitude;
        }
        if ($this->longitudeDms !== null) {
            $out['longitude_dms'] = $this->longitudeDms;
        }

        return $out;
    }
}
