<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/SpecialLagnasDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `special_lagnas` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/SpecialLagnasDocument`.
 */
final readonly class SpecialLagnasDocument
{
    /**
     * @param list<SpecialLagnasDocumentPointsItem> $points
     */
    public function __construct(
        public array $points,
        public ?float $sunriseJd = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            points: array_map(
                static fn (mixed $v): SpecialLagnasDocumentPointsItem
                    => SpecialLagnasDocumentPointsItem::fromArray(Json::object($v)),
                Json::list($data['points'] ?? null),
            ),
            sunriseJd: Json::floatOrNull($data['sunrise_jd'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['points'] = array_map(
            static fn (SpecialLagnasDocumentPointsItem $v): array => $v->toArray(),
            $this->points,
        );
        if ($this->sunriseJd !== null) {
            $out['sunrise_jd'] = $this->sunriseJd;
        }

        return $out;
    }
}
