<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/Timezone` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `#/components/schemas/Timezone`.
 */
final readonly class Timezone
{
    /**
     * @param string $source `derived` means the gateway looked the zone up from the coordinates.
     * @param string|null $name IANA zone, or null when a bare offset was given.
     */
    public function __construct(
        public string $utcOffset,
        public string $source,
        public ?string $name = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            utcOffset: Json::string($data['utc_offset'] ?? null),
            source: Json::string($data['source'] ?? null),
            name: Json::stringOrNull($data['name'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['utc_offset'] = $this->utcOffset;
        $out['source'] = $this->source;
        if ($this->name !== null) {
            $out['name'] = $this->name;
        }

        return $out;
    }
}
