<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `GET /v1/timezone data` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `GET /v1/timezone data`.
 */
final readonly class TimezoneDocument
{
    public function __construct(
        public string $name,
        public string $utcOffset,
        public string $source,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: Json::string($data['name'] ?? null),
            utcOffset: Json::string($data['utc_offset'] ?? null),
            source: Json::string($data['source'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['name'] = $this->name;
        $out['utc_offset'] = $this->utcOffset;
        $out['source'] = $this->source;

        return $out;
    }
}
