<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `TransitEventsDocument.events[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `TransitEventsDocument.events[]`.
 */
final readonly class TransitEvent
{
    public function __construct(
        public bool $isRetrograde,
        public string $kind,
        public string $local,
        public float $longitude,
        public string $longitudeDms,
        public LabelledId $nakshatra,
        public LabelledId $planet,
        public LabelledId $sign,
        public string $time,
        public int $utcOffsetMinutes,
        public ?LabelledId $fromNakshatra = null,
        public ?LabelledId $fromSign = null,
        public ?LabelledId $toNakshatra = null,
        public ?LabelledId $toSign = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $fromNakshatraRaw = $data['from_nakshatra'] ?? null;
        $fromSignRaw = $data['from_sign'] ?? null;
        $toNakshatraRaw = $data['to_nakshatra'] ?? null;
        $toSignRaw = $data['to_sign'] ?? null;

        return new self(
            isRetrograde: Json::bool($data['is_retrograde'] ?? null),
            kind: Json::string($data['kind'] ?? null),
            local: Json::string($data['local'] ?? null),
            longitude: Json::float($data['longitude'] ?? null),
            longitudeDms: Json::string($data['longitude_dms'] ?? null),
            nakshatra: LabelledId::fromArray(Json::object($data['nakshatra'] ?? null)),
            planet: LabelledId::fromArray(Json::object($data['planet'] ?? null)),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            time: Json::string($data['time'] ?? null),
            utcOffsetMinutes: Json::int($data['utc_offset_minutes'] ?? null),
            fromNakshatra: $fromNakshatraRaw === null ? null : LabelledId::fromArray(Json::object($fromNakshatraRaw)),
            fromSign: $fromSignRaw === null ? null : LabelledId::fromArray(Json::object($fromSignRaw)),
            toNakshatra: $toNakshatraRaw === null ? null : LabelledId::fromArray(Json::object($toNakshatraRaw)),
            toSign: $toSignRaw === null ? null : LabelledId::fromArray(Json::object($toSignRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['is_retrograde'] = $this->isRetrograde;
        $out['kind'] = $this->kind;
        $out['local'] = $this->local;
        $out['longitude'] = $this->longitude;
        $out['longitude_dms'] = $this->longitudeDms;
        $out['nakshatra'] = $this->nakshatra->toArray();
        $out['planet'] = $this->planet->toArray();
        $out['sign'] = $this->sign->toArray();
        $out['time'] = $this->time;
        $out['utc_offset_minutes'] = $this->utcOffsetMinutes;
        if ($this->fromNakshatra !== null) {
            $out['from_nakshatra'] = $this->fromNakshatra->toArray();
        }
        if ($this->fromSign !== null) {
            $out['from_sign'] = $this->fromSign->toArray();
        }
        if ($this->toNakshatra !== null) {
            $out['to_nakshatra'] = $this->toNakshatra->toArray();
        }
        if ($this->toSign !== null) {
            $out['to_sign'] = $this->toSign->toArray();
        }

        return $out;
    }
}
