<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/TransitNowDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * The document the `transit_now` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/TransitNowDocument`.
 */
final readonly class TransitNowDocument
{
    /**
     * @param array<string, list<string>> $placements
     * @param array<string, KundliDocumentPositionsValue> $positions
     */
    public function __construct(
        public float $ascendant,
        public string $ascendantDms,
        public string $at,
        public int $ayanamsaId,
        public float $ayanamsaValue,
        public string $ayanamsaValueDms,
        public LabelledId $lagnaSign,
        public float $latitude,
        public float $longitude,
        public string $longitudeDms,
        public array $placements,
        public array $positions,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $placements = [];
        foreach (Json::object($data['placements'] ?? null) as $key => $value) {
            $placements[$key] = array_map(static fn (mixed $item): string => Json::string($item), Json::list($value));
        }
        $positions = [];
        foreach (Json::object($data['positions'] ?? null) as $key => $value) {
            $positions[$key] = KundliDocumentPositionsValue::fromArray(Json::object($value));
        }

        return new self(
            ascendant: Json::float($data['ascendant'] ?? null),
            ascendantDms: Json::string($data['ascendant_dms'] ?? null),
            at: Json::string($data['at'] ?? null),
            ayanamsaId: Json::int($data['ayanamsa_id'] ?? null),
            ayanamsaValue: Json::float($data['ayanamsa_value'] ?? null),
            ayanamsaValueDms: Json::string($data['ayanamsa_value_dms'] ?? null),
            lagnaSign: LabelledId::fromArray(Json::object($data['lagna_sign'] ?? null)),
            latitude: Json::float($data['latitude'] ?? null),
            longitude: Json::float($data['longitude'] ?? null),
            longitudeDms: Json::string($data['longitude_dms'] ?? null),
            placements: $placements,
            positions: $positions,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['ascendant'] = $this->ascendant;
        $out['ascendant_dms'] = $this->ascendantDms;
        $out['at'] = $this->at;
        $out['ayanamsa_id'] = $this->ayanamsaId;
        $out['ayanamsa_value'] = $this->ayanamsaValue;
        $out['ayanamsa_value_dms'] = $this->ayanamsaValueDms;
        $out['lagna_sign'] = $this->lagnaSign->toArray();
        $out['latitude'] = $this->latitude;
        $out['longitude'] = $this->longitude;
        $out['longitude_dms'] = $this->longitudeDms;
        $out['placements'] = $this->placements;
        $out['positions'] = array_map(
            static fn (KundliDocumentPositionsValue $v): array => $v->toArray(),
            $this->positions,
        );

        return $out;
    }
}
