<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/transit/now body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/transit/now body`.
 */
final readonly class TransitNowRequest
{
    /**
     * @param float $latitude Latitude in decimal degrees, north positive, from -89.9 to 89.9, e.g. `28.6139`.
     * @param float $longitude Longitude in decimal degrees, east positive, from -180 to 180, e.g. `77.209`.
     * @param string|null $timezone IANA time zone name, e.g. `Asia/Kolkata`. The offset in force there at that date is
     *     used, so daylight saving and historical changes (India's +06:30 war time) are handled. Give this or
     *     `utc_offset`, not both. With neither, the zone is worked out from `latitude` and `longitude`, and
     *     `meta.timezone.source` says `derived`.
     * @param string|null $utcOffset Fixed offset from UTC, `±HH:MM`, e.g. `+05:30`; from `-14:00` to `+14:00`. An
     *     alternative to `timezone`, taken literally: no daylight saving or historical changes are applied. Give this
     *     or `timezone`, not both.
     * @param string|null $place A label for the place, e.g. `New Delhi`, up to 120 characters. Shown back to you (and
     *     on a PDF cover); never used in the calculation, which uses the coordinates.
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     * @param string|null $at The moment to show: a UTC instant, `YYYY-MM-DDTHH:MM:SS` (optionally `.sss`), `Z`
     *     optional, e.g. `2026-01-01T00:00:00Z`. Default: now (and then the answer is never cached).
     */
    public function __construct(
        public float $latitude,
        public float $longitude,
        public ?string $timezone = null,
        public ?string $utcOffset = null,
        public ?string $place = null,
        public ?CalculationOptions $options = null,
        public ?string $at = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;

        return new self(
            latitude: Json::float($data['latitude'] ?? null),
            longitude: Json::float($data['longitude'] ?? null),
            timezone: Json::stringOrNull($data['timezone'] ?? null),
            utcOffset: Json::stringOrNull($data['utc_offset'] ?? null),
            place: Json::stringOrNull($data['place'] ?? null),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
            at: Json::stringOrNull($data['at'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['latitude'] = $this->latitude;
        $out['longitude'] = $this->longitude;
        if ($this->timezone !== null) {
            $out['timezone'] = $this->timezone;
        }
        if ($this->utcOffset !== null) {
            $out['utc_offset'] = $this->utcOffset;
        }
        if ($this->place !== null) {
            $out['place'] = $this->place;
        }
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }
        if ($this->at !== null) {
            $out['at'] = $this->at;
        }

        return $out;
    }
}
