<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/TransitScanDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `transit_scan` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/TransitScanDocument`.
 */
final readonly class TransitScanDocument
{
    /**
     * @param list<TransitScanDocumentEventsItem> $events
     */
    public function __construct(
        public array $events,
        public string $from,
        public TransitScanDocumentNatalPoints $natalPoints,
        public string $to,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            events: array_map(
                static fn (mixed $v): TransitScanDocumentEventsItem
                    => TransitScanDocumentEventsItem::fromArray(Json::object($v)),
                Json::list($data['events'] ?? null),
            ),
            from: Json::string($data['from'] ?? null),
            natalPoints: TransitScanDocumentNatalPoints::fromArray(Json::object($data['natal_points'] ?? null)),
            to: Json::string($data['to'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['events'] = array_map(static fn (TransitScanDocumentEventsItem $v): array => $v->toArray(), $this->events);
        $out['from'] = $this->from;
        $out['natal_points'] = $this->natalPoints->toArray();
        $out['to'] = $this->to;

        return $out;
    }
}
