<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/transit/events body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/transit/events body`.
 */
final readonly class TransitEventsRequest
{
    /**
     * @param int|null $year A calendar year, e.g. `2026`: from local midnight on 1 January to local midnight on the
     *     next, in the zone below. Year 1800 to 2400. Give this or `from` and `to`, not both.
     * @param string|null $from Start of the window instead of `year`: a UTC instant, `YYYY-MM-DDTHH:MM:SS` (optionally
     *     `.sss`), `Z` optional, e.g. `2026-01-01T00:00:00Z`. With `to`.
     * @param string|null $to End of the window: a UTC instant, `YYYY-MM-DDTHH:MM:SS` (optionally `.sss`), `Z` optional,
     *     e.g. `2026-01-01T00:00:00Z`; after `from` and at most 366 days later. With `from`.
     * @param string|null $timezone IANA time zone each event's `local` time is written in (at the offset in force at
     *     that moment, so daylight saving is followed), and whose midnights bound `year`, e.g. `America/New_York`.
     *     Default `Asia/Kolkata` when `utc_offset` is absent too. Give this or `utc_offset`, not both.
     * @param string|null $utcOffset A fixed offset for the `local` times and the `year` boundaries instead, `±HH:MM`,
     *     e.g. `+05:30`; from `-14:00` to `+14:00`. Give this or `timezone`, not both.
     * @param bool|null $moon Also list the Moon's sign ingresses, about 160 a year (one every two and a half days).
     *     Default `false`: the list is the calendar of the Sun, the planets and the nodes.
     * @param bool|null $nakshatras Also list when Jupiter, Saturn, Rahu and Ketu enter a nakshatra. Default `false`.
     *     The Moon's (about 330 a year) are never listed.
     * @param bool|null $combustion Also list when Mars, Mercury, Jupiter, Venus and Saturn become combust (asta, within
     *     their orb of the Sun) and leave it (uday). The orbs are the engine's own: Mars 17°, Mercury 14°, Jupiter 11°,
     *     Venus 10°, Saturn 15°. Default `false`.
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     */
    public function __construct(
        public ?int $year = null,
        public ?string $from = null,
        public ?string $to = null,
        public ?string $timezone = null,
        public ?string $utcOffset = null,
        public ?bool $moon = null,
        public ?bool $nakshatras = null,
        public ?bool $combustion = null,
        public ?CalculationOptions $options = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;

        return new self(
            year: Json::intOrNull($data['year'] ?? null),
            from: Json::stringOrNull($data['from'] ?? null),
            to: Json::stringOrNull($data['to'] ?? null),
            timezone: Json::stringOrNull($data['timezone'] ?? null),
            utcOffset: Json::stringOrNull($data['utc_offset'] ?? null),
            moon: Json::boolOrNull($data['moon'] ?? null),
            nakshatras: Json::boolOrNull($data['nakshatras'] ?? null),
            combustion: Json::boolOrNull($data['combustion'] ?? null),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->year !== null) {
            $out['year'] = $this->year;
        }
        if ($this->from !== null) {
            $out['from'] = $this->from;
        }
        if ($this->to !== null) {
            $out['to'] = $this->to;
        }
        if ($this->timezone !== null) {
            $out['timezone'] = $this->timezone;
        }
        if ($this->utcOffset !== null) {
            $out['utc_offset'] = $this->utcOffset;
        }
        if ($this->moon !== null) {
            $out['moon'] = $this->moon;
        }
        if ($this->nakshatras !== null) {
            $out['nakshatras'] = $this->nakshatras;
        }
        if ($this->combustion !== null) {
            $out['combustion'] = $this->combustion;
        }
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }

        return $out;
    }
}
