<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `POST /v1/kundli/vargas body` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `POST /v1/kundli/vargas body`.
 */
final readonly class VargasRequest
{
    /**
     * @param Birth $birth The birth: the local clock time at the birth place, its coordinates and, optionally, its zone
     *     (`timezone` or `utc_offset`, not both).
     * @param CalculationOptions|null $options Settings for the calculation and the answer: ayanamsa, language,
     *     disclaimer. Every field has a default, so `options` may be left out.
     * @param list<string>|null $vargas The divisional charts to return, by id, e.g. `["d1", "d9"]`: 1 to 16 of `d1`
     *     (the rashi chart) to `d60`. Default: all sixteen. The answer keeps the standard order whatever order you ask
     *     in.
     */
    public function __construct(
        public Birth $birth,
        public ?CalculationOptions $options = null,
        public ?array $vargas = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $optionsRaw = $data['options'] ?? null;
        $vargasRaw = $data['vargas'] ?? null;

        return new self(
            birth: Birth::fromArray(Json::object($data['birth'] ?? null)),
            options: $optionsRaw === null ? null : CalculationOptions::fromArray(Json::object($optionsRaw)),
            vargas: $vargasRaw === null ? null : array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($vargasRaw),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['birth'] = $this->birth->toArray();
        if ($this->options !== null) {
            $out['options'] = $this->options->toArray();
        }
        if ($this->vargas !== null) {
            $out['vargas'] = $this->vargas;
        }

        return $out;
    }
}
