<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VargasDocument.lagna` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VargasDocument.lagna`.
 */
final readonly class VargasDocumentLagna
{
    public function __construct(
        public ?string $d1 = null,
        public ?string $d10 = null,
        public ?string $d12 = null,
        public ?string $d16 = null,
        public ?string $d2 = null,
        public ?string $d20 = null,
        public ?string $d24 = null,
        public ?string $d27 = null,
        public ?string $d3 = null,
        public ?string $d30 = null,
        public ?string $d4 = null,
        public ?string $d40 = null,
        public ?string $d45 = null,
        public ?string $d60 = null,
        public ?string $d7 = null,
        public ?string $d9 = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            d1: Json::stringOrNull($data['d1'] ?? null),
            d10: Json::stringOrNull($data['d10'] ?? null),
            d12: Json::stringOrNull($data['d12'] ?? null),
            d16: Json::stringOrNull($data['d16'] ?? null),
            d2: Json::stringOrNull($data['d2'] ?? null),
            d20: Json::stringOrNull($data['d20'] ?? null),
            d24: Json::stringOrNull($data['d24'] ?? null),
            d27: Json::stringOrNull($data['d27'] ?? null),
            d3: Json::stringOrNull($data['d3'] ?? null),
            d30: Json::stringOrNull($data['d30'] ?? null),
            d4: Json::stringOrNull($data['d4'] ?? null),
            d40: Json::stringOrNull($data['d40'] ?? null),
            d45: Json::stringOrNull($data['d45'] ?? null),
            d60: Json::stringOrNull($data['d60'] ?? null),
            d7: Json::stringOrNull($data['d7'] ?? null),
            d9: Json::stringOrNull($data['d9'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->d1 !== null) {
            $out['d1'] = $this->d1;
        }
        if ($this->d10 !== null) {
            $out['d10'] = $this->d10;
        }
        if ($this->d12 !== null) {
            $out['d12'] = $this->d12;
        }
        if ($this->d16 !== null) {
            $out['d16'] = $this->d16;
        }
        if ($this->d2 !== null) {
            $out['d2'] = $this->d2;
        }
        if ($this->d20 !== null) {
            $out['d20'] = $this->d20;
        }
        if ($this->d24 !== null) {
            $out['d24'] = $this->d24;
        }
        if ($this->d27 !== null) {
            $out['d27'] = $this->d27;
        }
        if ($this->d3 !== null) {
            $out['d3'] = $this->d3;
        }
        if ($this->d30 !== null) {
            $out['d30'] = $this->d30;
        }
        if ($this->d4 !== null) {
            $out['d4'] = $this->d4;
        }
        if ($this->d40 !== null) {
            $out['d40'] = $this->d40;
        }
        if ($this->d45 !== null) {
            $out['d45'] = $this->d45;
        }
        if ($this->d60 !== null) {
            $out['d60'] = $this->d60;
        }
        if ($this->d7 !== null) {
            $out['d7'] = $this->d7;
        }
        if ($this->d9 !== null) {
            $out['d9'] = $this->d9;
        }

        return $out;
    }
}
