<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocumentMonthlyItem.best` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VarshphalReadingDocumentMonthlyItem.best`.
 */
final readonly class VarshphalReadingDocumentMonthlyItemBest
{
    public function __construct(
        public string $from,
        public string $to,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            from: Json::string($data['from'] ?? null),
            to: Json::string($data['to'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['from'] = $this->from;
        $out['to'] = $this->to;

        return $out;
    }
}
