<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocumentBasis.five_lords[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalReadingDocumentBasis.five_lords[]`.
 */
final readonly class VarshphalReadingDocumentBasisFiveLordsItem
{
    /**
     * @param list<string> $roles
     */
    public function __construct(
        public LabelledId $graha,
        public int $house,
        public array $roles,
        public bool $strong,
        public float $vb,
        public bool $weak,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            graha: LabelledId::fromArray(Json::object($data['graha'] ?? null)),
            house: Json::int($data['house'] ?? null),
            roles: array_map(static fn (mixed $v): string => Json::string($v), Json::list($data['roles'] ?? null)),
            strong: Json::bool($data['strong'] ?? null),
            vb: Json::float($data['vb'] ?? null),
            weak: Json::bool($data['weak'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['graha'] = $this->graha->toArray();
        $out['house'] = $this->house;
        $out['roles'] = $this->roles;
        $out['strong'] = $this->strong;
        $out['vb'] = $this->vb;
        $out['weak'] = $this->weak;

        return $out;
    }
}
