<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalVarshaYearDocument.maasa[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalVarshaYearDocument.maasa[]`.
 */
final readonly class VarshphalVarshaYearDocumentMaasaItem
{
    public function __construct(
        public float $ascendant,
        public string $ascendantDms,
        public bool $dayPravesha,
        public LabelledId $lagnaSign,
        public int $month,
        public VarshphalVarshaYearDocumentYearLord $monthLord,
        public LabelledId $muntha,
        public string $pravesh,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            ascendant: Json::float($data['ascendant'] ?? null),
            ascendantDms: Json::string($data['ascendant_dms'] ?? null),
            dayPravesha: Json::bool($data['day_pravesha'] ?? null),
            lagnaSign: LabelledId::fromArray(Json::object($data['lagna_sign'] ?? null)),
            month: Json::int($data['month'] ?? null),
            monthLord: VarshphalVarshaYearDocumentYearLord::fromArray(Json::object($data['month_lord'] ?? null)),
            muntha: LabelledId::fromArray(Json::object($data['muntha'] ?? null)),
            pravesh: Json::string($data['pravesh'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['ascendant'] = $this->ascendant;
        $out['ascendant_dms'] = $this->ascendantDms;
        $out['day_pravesha'] = $this->dayPravesha;
        $out['lagna_sign'] = $this->lagnaSign->toArray();
        $out['month'] = $this->month;
        $out['month_lord'] = $this->monthLord->toArray();
        $out['muntha'] = $this->muntha->toArray();
        $out['pravesh'] = $this->pravesh;

        return $out;
    }
}
