<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/VarshphalTajikaDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `varshphal` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/VarshphalTajikaDocument`.
 */
final readonly class VarshphalTajikaDocument
{
    public function __construct(
        public VarshphalTajikaDocumentTajika $tajika,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            tajika: VarshphalTajikaDocumentTajika::fromArray(Json::object($data['tajika'] ?? null)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['tajika'] = $this->tajika->toArray();

        return $out;
    }
}
