<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocumentBasisAreasEducation.yogas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalReadingDocumentBasisAreasEducation.yogas[]`.
 */
final readonly class VarshphalReadingDocumentBasisAreasEducationYogasItem
{
    /**
     * @param list<string> $kinds
     */
    public function __construct(
        public string $factor,
        public LabelledId $graha,
        public int $house,
        public LabelledId $karyesha,
        public array $kinds,
        public string $source,
        public float $weight,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            factor: Json::string($data['factor'] ?? null),
            graha: LabelledId::fromArray(Json::object($data['graha'] ?? null)),
            house: Json::int($data['house'] ?? null),
            karyesha: LabelledId::fromArray(Json::object($data['karyesha'] ?? null)),
            kinds: array_map(static fn (mixed $v): string => Json::string($v), Json::list($data['kinds'] ?? null)),
            source: Json::string($data['source'] ?? null),
            weight: Json::float($data['weight'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['factor'] = $this->factor;
        $out['graha'] = $this->graha->toArray();
        $out['house'] = $this->house;
        $out['karyesha'] = $this->karyesha->toArray();
        $out['kinds'] = $this->kinds;
        $out['source'] = $this->source;
        $out['weight'] = $this->weight;

        return $out;
    }
}
