<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocumentBasis.year_lord` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalReadingDocumentBasis.year_lord`.
 */
final readonly class VarshphalReadingDocumentBasisYearLord
{
    /**
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $reasons
     */
    public function __construct(
        public bool $combust,
        public LabelledId $graha,
        public int $placementHouse,
        public array $reasons,
        public bool $retrograde,
        public float $score,
        public string $strengthClass,
        public string $vbClass,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            combust: Json::bool($data['combust'] ?? null),
            graha: LabelledId::fromArray(Json::object($data['graha'] ?? null)),
            placementHouse: Json::int($data['placement_house'] ?? null),
            reasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            retrograde: Json::bool($data['retrograde'] ?? null),
            score: Json::float($data['score'] ?? null),
            strengthClass: Json::string($data['strength_class'] ?? null),
            vbClass: Json::string($data['vb_class'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['combust'] = $this->combust;
        $out['graha'] = $this->graha->toArray();
        $out['placement_house'] = $this->placementHouse;
        $out['reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->reasons,
        );
        $out['retrograde'] = $this->retrograde;
        $out['score'] = $this->score;
        $out['strength_class'] = $this->strengthClass;
        $out['vb_class'] = $this->vbClass;

        return $out;
    }
}
