<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocument.sahams[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalReadingDocument.sahams[]`.
 */
final readonly class VarshphalReadingDocumentSahamsItem
{
    /**
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $reasons
     */
    public function __construct(
        public string $key,
        public LabelledId $lord,
        public array $reasons,
        public LabelledId $sign,
        public string $verdict,
        public ?string $day = null,
        public ?string $half = null,
        public ?LocalizedText $name = null,
        public ?VarshphalReadingDocumentSahamsItemPeriod $period = null,
        public ?LocalizedText $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $nameRaw = $data['name'] ?? null;
        $periodRaw = $data['period'] ?? null;
        $textRaw = $data['text'] ?? null;

        return new self(
            key: Json::string($data['key'] ?? null),
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            reasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            sign: LabelledId::fromArray(Json::object($data['sign'] ?? null)),
            verdict: Json::string($data['verdict'] ?? null),
            day: Json::stringOrNull($data['day'] ?? null),
            half: Json::stringOrNull($data['half'] ?? null),
            name: $nameRaw === null ? null : LocalizedText::fromArray(Json::object($nameRaw)),
            period: $periodRaw === null ? null : VarshphalReadingDocumentSahamsItemPeriod::fromArray(Json::object($periodRaw)),
            text: $textRaw === null ? null : LocalizedText::fromArray(Json::object($textRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['key'] = $this->key;
        $out['lord'] = $this->lord->toArray();
        $out['reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->reasons,
        );
        $out['sign'] = $this->sign->toArray();
        $out['verdict'] = $this->verdict;
        if ($this->day !== null) {
            $out['day'] = $this->day;
        }
        if ($this->half !== null) {
            $out['half'] = $this->half;
        }
        if ($this->name !== null) {
            $out['name'] = $this->name->toArray();
        }
        if ($this->period !== null) {
            $out['period'] = $this->period->toArray();
        }
        if ($this->text !== null) {
            $out['text'] = $this->text->toArray();
        }

        return $out;
    }
}
