<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalVarshaYearDocument.varsha` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalVarshaYearDocument.varsha`.
 */
final readonly class VarshphalVarshaYearDocumentVarsha
{
    /**
     * @param list<float> $houseCusps
     * @param list<string> $houseCuspsDms
     * @param array<string, DailyPanchangDocumentPositionsValue> $positions
     */
    public function __construct(
        public float $ascendant,
        public string $ascendantDms,
        public array $houseCusps,
        public array $houseCuspsDms,
        public LabelledId $lagnaSign,
        public array $positions,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $positions = [];
        foreach (Json::object($data['positions'] ?? null) as $key => $value) {
            $positions[$key] = DailyPanchangDocumentPositionsValue::fromArray(Json::object($value));
        }

        return new self(
            ascendant: Json::float($data['ascendant'] ?? null),
            ascendantDms: Json::string($data['ascendant_dms'] ?? null),
            houseCusps: array_map(
                static fn (mixed $v): float => Json::float($v),
                Json::list($data['house_cusps'] ?? null),
            ),
            houseCuspsDms: array_map(
                static fn (mixed $v): string => Json::string($v),
                Json::list($data['house_cusps_dms'] ?? null),
            ),
            lagnaSign: LabelledId::fromArray(Json::object($data['lagna_sign'] ?? null)),
            positions: $positions,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['ascendant'] = $this->ascendant;
        $out['ascendant_dms'] = $this->ascendantDms;
        $out['house_cusps'] = $this->houseCusps;
        $out['house_cusps_dms'] = $this->houseCuspsDms;
        $out['lagna_sign'] = $this->lagnaSign->toArray();
        $out['positions'] = array_map(
            static fn (DailyPanchangDocumentPositionsValue $v): array => $v->toArray(),
            $this->positions,
        );

        return $out;
    }
}
