<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalTajikaDocumentTajika.relations{}{}` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VarshphalTajikaDocumentTajika.relations{}{}`.
 */
final readonly class VarshphalTajikaDocumentTajikaRelationsValueValue
{
    public function __construct(
        public bool $mutualEnemies,
        public string $relation,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            mutualEnemies: Json::bool($data['mutual_enemies'] ?? null),
            relation: Json::string($data['relation'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['mutual_enemies'] = $this->mutualEnemies;
        $out['relation'] = $this->relation;

        return $out;
    }
}
