<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/VarshphalReadingDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `varshphal_reading` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/VarshphalReadingDocument`.
 */
final readonly class VarshphalReadingDocument
{
    /**
     * @param list<AreaSummary> $areas
     * @param list<VarshphalPeriod> $months
     * @param LocalizedText|null $disclaimer The closing line: "these predictions are indicative…", naming the
     *     astrologer in `options.disclaimer` when one is given. Absent when `options.disclaimer` is `"off"`.
     */
    public function __construct(
        public array $areas,
        public VarshphalReadingDocumentBasis $basis,
        public string $from,
        public array $months,
        public ReadingSummary $summary,
        public string $to,
        public int $varshaYear,
        public int $year,
        public ?LocalizedText $disclaimer = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $disclaimerRaw = $data['disclaimer'] ?? null;

        return new self(
            areas: array_map(
                static fn (mixed $v): AreaSummary => AreaSummary::fromArray(Json::object($v)),
                Json::list($data['areas'] ?? null),
            ),
            basis: VarshphalReadingDocumentBasis::fromArray(Json::object($data['basis'] ?? null)),
            from: Json::string($data['from'] ?? null),
            months: array_map(
                static fn (mixed $v): VarshphalPeriod => VarshphalPeriod::fromArray(Json::object($v)),
                Json::list($data['months'] ?? null),
            ),
            summary: ReadingSummary::fromArray(Json::object($data['summary'] ?? null)),
            to: Json::string($data['to'] ?? null),
            varshaYear: Json::int($data['varsha_year'] ?? null),
            year: Json::int($data['year'] ?? null),
            disclaimer: $disclaimerRaw === null ? null : LocalizedText::fromArray(Json::object($disclaimerRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['areas'] = array_map(static fn (AreaSummary $v): array => $v->toArray(), $this->areas);
        $out['basis'] = $this->basis->toArray();
        $out['from'] = $this->from;
        $out['months'] = array_map(static fn (VarshphalPeriod $v): array => $v->toArray(), $this->months);
        $out['summary'] = $this->summary->toArray();
        $out['to'] = $this->to;
        $out['varsha_year'] = $this->varshaYear;
        $out['year'] = $this->year;
        if ($this->disclaimer !== null) {
            $out['disclaimer'] = $this->disclaimer->toArray();
        }

        return $out;
    }
}
