<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocumentBasis.months[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalReadingDocumentBasis.months[]`.
 */
final readonly class VarshphalReadingDocumentBasisMonthsItem
{
    /**
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $reasons
     */
    public function __construct(
        public LabelledId $lord,
        public array $reasons,
        public float $score,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            reasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            score: Json::float($data['score'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['lord'] = $this->lord->toArray();
        $out['reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->reasons,
        );
        $out['score'] = $this->score;

        return $out;
    }
}
