<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalHarshaBalaDocument.harsha_bala[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalHarshaBalaDocument.harsha_bala[]`.
 */
final readonly class VarshphalHarshaBalaDocumentHarshaBalaItem
{
    public function __construct(
        public int $first,
        public int $fourth,
        public LabelledId $planet,
        public int $second,
        public int $third,
        public float $total,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            first: Json::int($data['first'] ?? null),
            fourth: Json::int($data['fourth'] ?? null),
            planet: LabelledId::fromArray(Json::object($data['planet'] ?? null)),
            second: Json::int($data['second'] ?? null),
            third: Json::int($data['third'] ?? null),
            total: Json::float($data['total'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['first'] = $this->first;
        $out['fourth'] = $this->fourth;
        $out['planet'] = $this->planet->toArray();
        $out['second'] = $this->second;
        $out['third'] = $this->third;
        $out['total'] = $this->total;

        return $out;
    }
}
