<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocumentPeriodsItem.subs[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VarshphalReadingDocumentPeriodsItem.subs[]`.
 */
final readonly class VarshphalReadingDocumentPeriodsItemSubsItem
{
    public function __construct(
        public string $from,
        public string $to,
        public ?bool $good = null,
        public mixed $lord = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            from: Json::string($data['from'] ?? null),
            to: Json::string($data['to'] ?? null),
            good: Json::boolOrNull($data['good'] ?? null),
            lord: $data['lord'] ?? null,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['from'] = $this->from;
        $out['to'] = $this->to;
        if ($this->good !== null) {
            $out['good'] = $this->good;
        }
        if ($this->lord !== null) {
            $out['lord'] = $this->lord;
        }

        return $out;
    }
}
