<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/VarshphalHarshaBalaDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `varshphal` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/VarshphalHarshaBalaDocument`.
 */
final readonly class VarshphalHarshaBalaDocument
{
    /**
     * @param list<VarshphalHarshaBalaDocumentHarshaBalaItem> $harshaBala
     * @param list<VarshphalHarshaBalaDocumentPanchavargiyaItem> $panchavargiya
     */
    public function __construct(
        public array $harshaBala,
        public array $panchavargiya,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            harshaBala: array_map(
                static fn (mixed $v): VarshphalHarshaBalaDocumentHarshaBalaItem
                    => VarshphalHarshaBalaDocumentHarshaBalaItem::fromArray(Json::object($v)),
                Json::list($data['harsha_bala'] ?? null),
            ),
            panchavargiya: array_map(
                static fn (mixed $v): VarshphalHarshaBalaDocumentPanchavargiyaItem
                    => VarshphalHarshaBalaDocumentPanchavargiyaItem::fromArray(Json::object($v)),
                Json::list($data['panchavargiya'] ?? null),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['harsha_bala'] = array_map(
            static fn (VarshphalHarshaBalaDocumentHarshaBalaItem $v): array => $v->toArray(),
            $this->harshaBala,
        );
        $out['panchavargiya'] = array_map(
            static fn (VarshphalHarshaBalaDocumentPanchavargiyaItem $v): array => $v->toArray(),
            $this->panchavargiya,
        );

        return $out;
    }
}
