<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalMuddaDocument.mudda[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalMuddaDocument.mudda[]`.
 */
final readonly class VarshphalMuddaDocumentMuddaItem
{
    /**
     * @param list<VarshphalMuddaDocumentMuddaItemSubPeriodsItem> $subPeriods
     */
    public function __construct(
        public string $end,
        public bool $isLagna,
        public string $start,
        public array $subPeriods,
        public ?LabelledId $lord = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $lordRaw = $data['lord'] ?? null;

        return new self(
            end: Json::string($data['end'] ?? null),
            isLagna: Json::bool($data['is_lagna'] ?? null),
            start: Json::string($data['start'] ?? null),
            subPeriods: array_map(
                static fn (mixed $v): VarshphalMuddaDocumentMuddaItemSubPeriodsItem
                    => VarshphalMuddaDocumentMuddaItemSubPeriodsItem::fromArray(Json::object($v)),
                Json::list($data['sub_periods'] ?? null),
            ),
            lord: $lordRaw === null ? null : LabelledId::fromArray(Json::object($lordRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['end'] = $this->end;
        $out['is_lagna'] = $this->isLagna;
        $out['start'] = $this->start;
        $out['sub_periods'] = array_map(
            static fn (VarshphalMuddaDocumentMuddaItemSubPeriodsItem $v): array => $v->toArray(),
            $this->subPeriods,
        );
        if ($this->lord !== null) {
            $out['lord'] = $this->lord->toArray();
        }

        return $out;
    }
}
