<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalReadingDocument.natal_promise[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalReadingDocument.natal_promise[]`.
 */
final readonly class VarshphalReadingDocumentNatalPromiseItem
{
    /**
     * @param list<VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem> $reasons
     */
    public function __construct(
        public bool $active,
        public int $house,
        public LabelledId $lord,
        public array $reasons,
        public string $with,
        public ?LocalizedText $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $textRaw = $data['text'] ?? null;

        return new self(
            active: Json::bool($data['active'] ?? null),
            house: Json::int($data['house'] ?? null),
            lord: LabelledId::fromArray(Json::object($data['lord'] ?? null)),
            reasons: array_map(
                static fn (mixed $v): VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
                    => VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem::fromArray(Json::object($v)),
                Json::list($data['reasons'] ?? null),
            ),
            with: Json::string($data['with'] ?? null),
            text: $textRaw === null ? null : LocalizedText::fromArray(Json::object($textRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['active'] = $this->active;
        $out['house'] = $this->house;
        $out['lord'] = $this->lord->toArray();
        $out['reasons'] = array_map(
            static fn (VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem $v): array => $v->toArray(),
            $this->reasons,
        );
        $out['with'] = $this->with;
        if ($this->text !== null) {
            $out['text'] = $this->text->toArray();
        }

        return $out;
    }
}
