<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalTajikaDocument.tajika` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalTajikaDocument.tajika`.
 */
final readonly class VarshphalTajikaDocumentTajika
{
    /**
     * @param list<VarshphalTajikaDocumentTajikaChartYogasItem> $chartYogas
     * @param list<VarshphalTajikaDocumentTajikaPairYogasItem> $pairYogas
     * @param array<string, array<string, VarshphalTajikaDocumentTajikaRelationsValueValue>> $relations
     */
    public function __construct(
        public array $chartYogas,
        public LabelledId $karyesha,
        public LabelledId $lagnesha,
        public array $pairYogas,
        public array $relations,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $relations = [];
        foreach (Json::object($data['relations'] ?? null) as $key => $value) {
            $inner = [];
            foreach (Json::object($value) as $innerKey => $innerValue) {
                $inner[$innerKey] = VarshphalTajikaDocumentTajikaRelationsValueValue::fromArray(Json::object($innerValue));
            }
            $relations[$key] = $inner;
        }

        return new self(
            chartYogas: array_map(
                static fn (mixed $v): VarshphalTajikaDocumentTajikaChartYogasItem
                    => VarshphalTajikaDocumentTajikaChartYogasItem::fromArray(Json::object($v)),
                Json::list($data['chart_yogas'] ?? null),
            ),
            karyesha: LabelledId::fromArray(Json::object($data['karyesha'] ?? null)),
            lagnesha: LabelledId::fromArray(Json::object($data['lagnesha'] ?? null)),
            pairYogas: array_map(
                static fn (mixed $v): VarshphalTajikaDocumentTajikaPairYogasItem
                    => VarshphalTajikaDocumentTajikaPairYogasItem::fromArray(Json::object($v)),
                Json::list($data['pair_yogas'] ?? null),
            ),
            relations: $relations,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['chart_yogas'] = array_map(
            static fn (VarshphalTajikaDocumentTajikaChartYogasItem $v): array => $v->toArray(),
            $this->chartYogas,
        );
        $out['karyesha'] = $this->karyesha->toArray();
        $out['lagnesha'] = $this->lagnesha->toArray();
        $out['pair_yogas'] = array_map(
            static fn (VarshphalTajikaDocumentTajikaPairYogasItem $v): array => $v->toArray(),
            $this->pairYogas,
        );
        $relations = [];
        foreach ($this->relations as $key => $value) {
            $relations[$key] = array_map(
                static fn (VarshphalTajikaDocumentTajikaRelationsValueValue $item): array => $item->toArray(),
                $value,
            );
        }
        $out['relations'] = $relations;

        return $out;
    }
}
