<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VarshphalTajikaDocumentTajika.chart_yogas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VarshphalTajikaDocumentTajika.chart_yogas[]`.
 */
final readonly class VarshphalTajikaDocumentTajikaChartYogasItem
{
    /**
     * @param list<LabelledId> $planets
     */
    public function __construct(
        public array $planets,
        public string $type,
        public mixed $linker = null,
        public mixed $orb = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            planets: array_map(
                static fn (mixed $v): LabelledId => LabelledId::fromArray(Json::object($v)),
                Json::list($data['planets'] ?? null),
            ),
            type: Json::string($data['type'] ?? null),
            linker: $data['linker'] ?? null,
            orb: $data['orb'] ?? null,
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['planets'] = array_map(static fn (LabelledId $v): array => $v->toArray(), $this->planets);
        $out['type'] = $this->type;
        if ($this->linker !== null) {
            $out['linker'] = $this->linker;
        }
        if ($this->orb !== null) {
            $out['orb'] = $this->orb;
        }

        return $out;
    }
}
