<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VikramSamvatDocument.amanta` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VikramSamvatDocument.amanta`.
 */
final readonly class VikramSamvatDocumentAmanta
{
    public function __construct(
        public bool $isAdhik,
        public int $monthIndex,
        public LabelledId $monthName,
        public int $samvatYear,
        public string $system,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            isAdhik: Json::bool($data['is_adhik'] ?? null),
            monthIndex: Json::int($data['month_index'] ?? null),
            monthName: LabelledId::fromArray(Json::object($data['month_name'] ?? null)),
            samvatYear: Json::int($data['samvat_year'] ?? null),
            system: Json::string($data['system'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['is_adhik'] = $this->isAdhik;
        $out['month_index'] = $this->monthIndex;
        $out['month_name'] = $this->monthName->toArray();
        $out['samvat_year'] = $this->samvatYear;
        $out['system'] = $this->system;

        return $out;
    }
}
