<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VimshottariReadingDocumentBasisFunctionalValueMaraka.basis` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `VimshottariReadingDocumentBasisFunctionalValueMaraka.basis`.
 */
final readonly class VimshottariReadingDocumentBasisFunctionalValueMarakaBasis
{
    public function __construct(
        public string $kind,
        public ?LabelledId $planet = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $planetRaw = $data['planet'] ?? null;

        return new self(
            kind: Json::string($data['kind'] ?? null),
            planet: $planetRaw === null ? null : LabelledId::fromArray(Json::object($planetRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['kind'] = $this->kind;
        if ($this->planet !== null) {
            $out['planet'] = $this->planet->toArray();
        }

        return $out;
    }
}
