<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VimshottariReadingDocumentBasisFunctionalValue.dasha_role_reasons[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VimshottariReadingDocumentBasisFunctionalValue.dasha_role_reasons[]`.
 */
final readonly class VimshottariReadingDocumentBasisFunctionalValueDashaRoleReasonsItem
{
    public function __construct(
        public string $code,
        public string $source,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            code: Json::string($data['code'] ?? null),
            source: Json::string($data['source'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['code'] = $this->code;
        $out['source'] = $this->source;

        return $out;
    }
}
