<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VimshottariReadingDocumentBasisFunctionalValue.yogakaraka` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VimshottariReadingDocumentBasisFunctionalValue.yogakaraka`.
 */
final readonly class VimshottariReadingDocumentBasisFunctionalValueYogakaraka
{
    public function __construct(
        public string $kind,
        public ?int $kendra = null,
        public ?int $trikona = null,
        public ?string $with = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            kind: Json::string($data['kind'] ?? null),
            kendra: Json::intOrNull($data['kendra'] ?? null),
            trikona: Json::intOrNull($data['trikona'] ?? null),
            with: Json::stringOrNull($data['with'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['kind'] = $this->kind;
        if ($this->kendra !== null) {
            $out['kendra'] = $this->kendra;
        }
        if ($this->trikona !== null) {
            $out['trikona'] = $this->trikona;
        }
        if ($this->with !== null) {
            $out['with'] = $this->with;
        }

        return $out;
    }
}
