<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/VimshottariReadingDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `vimshottari_reading` op of the Kaal Jyoti engine 0.16.0 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/VimshottariReadingDocument`.
 */
final readonly class VimshottariReadingDocument
{
    /**
     * @param list<MahadashaReading> $periods
     * @param LocalizedText|null $disclaimer The closing line: "these predictions are indicative…", naming the
     *     astrologer in `options.disclaimer` when one is given. Absent when `options.disclaimer` is `"off"`.
     */
    public function __construct(
        public VimshottariReadingDocumentBasis $basis,
        public array $periods,
        public ?LocalizedText $disclaimer = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $disclaimerRaw = $data['disclaimer'] ?? null;

        return new self(
            basis: VimshottariReadingDocumentBasis::fromArray(Json::object($data['basis'] ?? null)),
            periods: array_map(
                static fn (mixed $v): MahadashaReading => MahadashaReading::fromArray(Json::object($v)),
                Json::list($data['periods'] ?? null),
            ),
            disclaimer: $disclaimerRaw === null ? null : LocalizedText::fromArray(Json::object($disclaimerRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['basis'] = $this->basis->toArray();
        $out['periods'] = array_map(static fn (MahadashaReading $v): array => $v->toArray(), $this->periods);
        if ($this->disclaimer !== null) {
            $out['disclaimer'] = $this->disclaimer->toArray();
        }

        return $out;
    }
}
