<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `VimshottariReadingDocumentBasisSwitches.dasha` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * Wire shape: `VimshottariReadingDocumentBasisSwitches.dasha`.
 */
final readonly class VimshottariReadingDocumentBasisSwitchesDasha
{
    public function __construct(
        public bool $inauspiciousLightSoftens,
        public bool $lowMarakaSoftens,
        public bool $marakaPushesLevel,
        public bool $mixedStrengthTilt,
        public bool $mutualDusthanaWorsens,
        public bool $rajaYogaDasha,
        public int $rajaYogaMinRelation,
        public bool $raoBeneficAssociation,
        public bool $raoDebilitatedDusthana,
        public bool $raoNodeTrikonaYk,
        public bool $raoVsOwnBhukti,
        public bool $raoYogaBhukti,
        public bool $raoYogaSurvivesMaraka,
        public string $s19RelatedPapaInYk,
        public string $s31Order,
        public string $s32Unrelated,
        public string $s34UnrelatedAuspiciousInYk,
        public bool $s35PeakRequiresStrongYk,
        public string $s36Houses,
        public bool $s40UkInversion,
        public bool $s40UnrelatedOnly,
        public bool $sandwich,
        public bool $seventhLordMarakaTrikona,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            inauspiciousLightSoftens: Json::bool($data['inauspicious_light_softens'] ?? null),
            lowMarakaSoftens: Json::bool($data['low_maraka_softens'] ?? null),
            marakaPushesLevel: Json::bool($data['maraka_pushes_level'] ?? null),
            mixedStrengthTilt: Json::bool($data['mixed_strength_tilt'] ?? null),
            mutualDusthanaWorsens: Json::bool($data['mutual_dusthana_worsens'] ?? null),
            rajaYogaDasha: Json::bool($data['raja_yoga_dasha'] ?? null),
            rajaYogaMinRelation: Json::int($data['raja_yoga_min_relation'] ?? null),
            raoBeneficAssociation: Json::bool($data['rao_benefic_association'] ?? null),
            raoDebilitatedDusthana: Json::bool($data['rao_debilitated_dusthana'] ?? null),
            raoNodeTrikonaYk: Json::bool($data['rao_node_trikona_yk'] ?? null),
            raoVsOwnBhukti: Json::bool($data['rao_vs_own_bhukti'] ?? null),
            raoYogaBhukti: Json::bool($data['rao_yoga_bhukti'] ?? null),
            raoYogaSurvivesMaraka: Json::bool($data['rao_yoga_survives_maraka'] ?? null),
            s19RelatedPapaInYk: Json::string($data['s19_related_papa_in_yk'] ?? null),
            s31Order: Json::string($data['s31_order'] ?? null),
            s32Unrelated: Json::string($data['s32_unrelated'] ?? null),
            s34UnrelatedAuspiciousInYk: Json::string($data['s34_unrelated_auspicious_in_yk'] ?? null),
            s35PeakRequiresStrongYk: Json::bool($data['s35_peak_requires_strong_yk'] ?? null),
            s36Houses: Json::string($data['s36_houses'] ?? null),
            s40UkInversion: Json::bool($data['s40_uk_inversion'] ?? null),
            s40UnrelatedOnly: Json::bool($data['s40_unrelated_only'] ?? null),
            sandwich: Json::bool($data['sandwich'] ?? null),
            seventhLordMarakaTrikona: Json::bool($data['seventh_lord_maraka_trikona'] ?? null),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['inauspicious_light_softens'] = $this->inauspiciousLightSoftens;
        $out['low_maraka_softens'] = $this->lowMarakaSoftens;
        $out['maraka_pushes_level'] = $this->marakaPushesLevel;
        $out['mixed_strength_tilt'] = $this->mixedStrengthTilt;
        $out['mutual_dusthana_worsens'] = $this->mutualDusthanaWorsens;
        $out['raja_yoga_dasha'] = $this->rajaYogaDasha;
        $out['raja_yoga_min_relation'] = $this->rajaYogaMinRelation;
        $out['rao_benefic_association'] = $this->raoBeneficAssociation;
        $out['rao_debilitated_dusthana'] = $this->raoDebilitatedDusthana;
        $out['rao_node_trikona_yk'] = $this->raoNodeTrikonaYk;
        $out['rao_vs_own_bhukti'] = $this->raoVsOwnBhukti;
        $out['rao_yoga_bhukti'] = $this->raoYogaBhukti;
        $out['rao_yoga_survives_maraka'] = $this->raoYogaSurvivesMaraka;
        $out['s19_related_papa_in_yk'] = $this->s19RelatedPapaInYk;
        $out['s31_order'] = $this->s31Order;
        $out['s32_unrelated'] = $this->s32Unrelated;
        $out['s34_unrelated_auspicious_in_yk'] = $this->s34UnrelatedAuspiciousInYk;
        $out['s35_peak_requires_strong_yk'] = $this->s35PeakRequiresStrongYk;
        $out['s36_houses'] = $this->s36Houses;
        $out['s40_uk_inversion'] = $this->s40UkInversion;
        $out['s40_unrelated_only'] = $this->s40UnrelatedOnly;
        $out['sandwich'] = $this->sandwich;
        $out['seventh_lord_maraka_trikona'] = $this->seventhLordMarakaTrikona;

        return $out;
    }
}
