<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `#/components/schemas/YogasDocument` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;

/**
 * The document the `yogas` op of the Kaal Jyoti engine 0.15.2 returns, inferred from real responses by
 * harness/gen_response_schemas.py. Regenerated on every engine tag.
 *
 * Wire shape: `#/components/schemas/YogasDocument`.
 */
final readonly class YogasDocument
{
    /**
     * @param list<KundliDocumentYogasItem> $yogas
     */
    public function __construct(
        public array $yogas,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            yogas: array_map(
                static fn (mixed $v): KundliDocumentYogasItem => KundliDocumentYogasItem::fromArray(Json::object($v)),
                Json::list($data['yogas'] ?? null),
            ),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['yogas'] = array_map(static fn (KundliDocumentYogasItem $v): array => $v->toArray(), $this->yogas);

        return $out;
    }
}
