<?php

/**
 * GENERATED by `pnpm --filter sdk-php run gen` from openapi/openapi.json.
 * Do not edit by hand: `pnpm --filter sdk-php run gen:check` fails the build
 * when this file and the snapshot disagree.
 *
 * `ReadingYogasDocument.yogas[]` as a PHP class.
 */

declare(strict_types=1);

namespace Kaaljyoti\Models;

use Kaaljyoti\Generated\Json;
use Kaaljyoti\Generated\LabelledId;

/**
 * Wire shape: `ReadingYogasDocument.yogas[]`.
 */
final readonly class YogaReading
{
    /**
     * @param list<YogaReadingFormationsItem> $formations
     * @param LocalizedText $name One piece of text, keyed by language: one entry for each language in
     *     `options.language`, in that order (`{"hi": "…"}` or `{"en": "…", "hi": "…"}`).
     * @param list<LabelledId> $participants
     * @param list<YogaReadingPeriodsItem> $periods
     */
    public function __construct(
        public string $category,
        public string $code,
        public int $count,
        public array $formations,
        public LocalizedText $name,
        public array $participants,
        public array $periods,
        public ?ReadingEntry $entry = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $entryRaw = $data['entry'] ?? null;

        return new self(
            category: Json::string($data['category'] ?? null),
            code: Json::string($data['code'] ?? null),
            count: Json::int($data['count'] ?? null),
            formations: array_map(
                static fn (mixed $v): YogaReadingFormationsItem
                    => YogaReadingFormationsItem::fromArray(Json::object($v)),
                Json::list($data['formations'] ?? null),
            ),
            name: LocalizedText::fromArray(Json::object($data['name'] ?? null)),
            participants: array_map(
                static fn (mixed $v): LabelledId => LabelledId::fromArray(Json::object($v)),
                Json::list($data['participants'] ?? null),
            ),
            periods: array_map(
                static fn (mixed $v): YogaReadingPeriodsItem => YogaReadingPeriodsItem::fromArray(Json::object($v)),
                Json::list($data['periods'] ?? null),
            ),
            entry: $entryRaw === null ? null : ReadingEntry::fromArray(Json::object($entryRaw)),
        );
    }

    /**
     * This value as an array, with every null key left out.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['category'] = $this->category;
        $out['code'] = $this->code;
        $out['count'] = $this->count;
        $out['formations'] = array_map(
            static fn (YogaReadingFormationsItem $v): array => $v->toArray(),
            $this->formations,
        );
        $out['name'] = $this->name->toArray();
        $out['participants'] = array_map(static fn (LabelledId $v): array => $v->toArray(), $this->participants);
        $out['periods'] = array_map(static fn (YogaReadingPeriodsItem $v): array => $v->toArray(), $this->periods);
        if ($this->entry !== null) {
            $out['entry'] = $this->entry->toArray();
        }

        return $out;
    }
}
